%\documentclass[english, handout]{beamer}
% handout options: version without solutions for the participants
\documentclass[english]{beamer}

% Leos shortcuts
\input{newCommands.tex}
\def\SE{\mbox{se}}
\def\PE{\mbox{PE}}
\def\OR{\mbox{OR}}
\def\HR{\mbox{HR}}
\def\RR{\mbox{RR}}
\def\EF{\mbox{EF}}
\def\RV{\mbox{RV}}
\def\RD{\mbox{RD}}
\def\ARR{\mbox{ARR}}
\def\RRR{\mbox{RRR}}
\def\NNT{\mbox{NNT}}
% nicer tables
\usepackage{booktabs}
% \usepackage{soul}
% \makeatletter
% \let\HL\hl
% \renewcommand\hl{%
%   \let\set@color\beamerorig@set@color
%   \let\reset@color\beamerorig@reset@color
%   \HL}
% \makeatother
% \sethlcolor{red!25}

% define same colors as in plots
\definecolor{purple3}{RGB}{125,38,205}
\definecolor{springgreen4}{RGB}{0, 139, 69}
\definecolor{Rred}{RGB}{255,0,0}
\definecolor{tan3}{RGB}{205,133,63}
\definecolor{foo}{rgb}{0.2,0.2,0.7}

\usepackage{colortbl}
\definecolor{Gray}{gray}{0.85}
\newcolumntype{a}{>{\columncolor{Gray}}c}
% citing
\usepackage[round]{natbib}

% biostat beamer theme
\usepackage{beamerthemebiostat}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{wasysym}
\definecolor{darkred}{rgb}{0.8,0,0}
\usepackage{color}
\definecolor{magenta}{cmyk}{0,1,0,0}
\newcommand{\dmin}{d_{\tiny \mbox{min}}}
\setbeamertemplate{footline}[page number]


% hyperref options
\usepackage{hyperref}  
\hypersetup{
  bookmarksopen=true, 
  breaklinks=true,
  pdftitle={Design and Analysis of Replication Studies}, 
  pdfauthor={Leonhard Held, Charlotte Micheloud, Samuel Pawel},
  colorlinks=false
}

% Installation of non-free fonts in ubuntu 18.04:
% cd Downloads/
% wget -q https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts
% sudo texlua ./install-getnonfreefonts
% sudo getnonfreefonts --sys -a
\def\uzhunit{}
\def\uzhunitext{}
\title{\centering Analysis and Design of Replication Studies}
\author{\centering \bf  Leonhard Held, Charlotte Micheloud}
\institute{University of Zurich}

  
\date{Feb 6-9, 2022}


% ----------------------------------------------------------------------------
<< include = FALSE, purl = FALSE >>=
library(knitr)
library(scales)
library(biostatUZH)
opts_chunk$set(fig.path = "figures/fig", 
               cache = TRUE, 
               fig.align = "center",
               fig.height = 8,
               fig.width = 10,
               dpi = 1000,
               echo = TRUE,
               size = "scriptsize",
               warning = FALSE,
               message = FALSE)
@
% ----------------------------------------------------------------------------

\begin{document}

\begin{frame}
\vspace{1cm}
\maketitle
\vspace{-0.5cm}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{center}
\includegraphics[width=0.6\textwidth]{images_presentation/CRS.png}
  \end{center}
  \end{column}
    \begin{column}{0.5\textwidth}
  \includegraphics[width=0.8\textwidth]{images_presentation/logo.png}
    \end{column}
  \end{columns}
    \begin{center}
    {\color{darkred} 24th SINAPE, Gramado-RS}
    \end{center}
\end{frame}

\begin{frame}
\section{Introduction}
  \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Introduction}} 
   \end{center}
  \end{block}
\end{frame}

\begin{frame}{Replication studies}
\begin{block}{Direct replication}
  \begin{itemize}
    \item Repeating original study using the same methodology
    \item[$\rightarrow$] Tool to assess credibility of scientific discoveries
    \item[$\rightarrow$] Regulatory requirement
  \end{itemize}
\end{block}
\pause
\begin{block}{Replication crisis}
  \begin{itemize}
    \item Low replicability of many scientific discoveries
    \item[$\rightarrow$] Large-scale replication projects
  \end{itemize}
\end{block}
\end{frame}


\begin{frame}{Large-scale replication projects}
\begin{block}{}
  \begin{itemize}
    \item<1-> \color<1>{gray}{2015: Reproducibility project psychology}
    \item<1-> \color<1>{gray}{2016: Experimental economics replication project}
    \item<1-> \color<1>{gray}{2018: Experimental philosophy replicability project}
    \item<1-> \color<1>{red}{2018: Social sciences replication project}
    \item<1-> \color<1>{gray}{2021: Reproducibility Project: Cancer Biology}
  \end{itemize}
\end{block}
\begin{minipage}[t][5cm][t]{\textwidth}
  \centering
  \only<1>{
  \includegraphics[width=0.7\textwidth]{images_presentation/camerer2018.png}
  }
\end{minipage}
\end{frame}


\begin{frame}[fragile]{Social sciences replication project}
  \framesubtitle{Correlation scale}
<< echo = FALSE >>=
library(ReplicationSuccess)
library(ggplot2)
data("RProjects")
SSRP <- subset(RProjects, project == "Social Sciences")

gg_r <-  ggplot(data = SSRP, aes(x = ro, y = rr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 7, shape = 21, 
             fill = "midnightblue") +
  labs(x = expression(paste("Original effect estimate ", r[o])), 
       y = expression(paste("Replication effect estimate ", r[r]))) +
  lims(x = c(-0.15, 1), y = c(-0.15, 1)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)); gg_r
@
\end{frame}




\begin{frame}[fragile]{Statistical framework of package}
\begin{block}{}
\begin{itemize}
\item Effect estimates are assumed to be {\color{red} normally distributed} after suitable transformation \\
$\rightarrow$ {\color{red} Fisher's $z$-transformation} for correlation 
coefficients $r$ with (effective) sample size $n - 3$
\end{itemize}
\end{block}
<< fig.height = 4.5, echo = FALSE>>=
r <- seq(-1, 1, 0.001)
ztrans_df <- data.frame(r, z = atanh(r))
ggplot(data = ztrans_df, aes(x = r, y = z)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, size = 1,
              alpha = 0.6) +
  geom_line(size = 1) + 
  labs(x = expression(paste("Correlation ", italic(r))), 
       y = expression(paste("Fisher-", italic(z)))) +
  theme_bw() +
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30))
@
\end{frame}

\begin{frame}[fragile]{Social sciences replication project}
  \framesubtitle{Fisher-$z$ scale}
<< echo = FALSE >>=
library(ReplicationSuccess)
library(ggplot2)
data("RProjects")
SSRP <- subset(RProjects, project == "Social Sciences")

gg_z <- ggplot(data = SSRP, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 7, shape = 21, 
             fill = "midnightblue") +
  labs(x = expression(paste("Original effect estimate ", hat(theta)[o])), 
       y = expression(paste("Replication effect estimate ", hat(theta)[r]))) +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)); gg_z
@
\end{frame}


\begin{frame}[fragile]{Correlation vs Fisher-$z$ scale}
<< echo = FALSE >>=
library(ReplicationSuccess)
library(ggplot2)
library(gridExtra)

gg_r2 <- ggplot(data = SSRP, aes(x = ro, y = rr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 5, shape = 21, 
             fill = "midnightblue") +
  labs(x = "Original effect estimate", 
       y = "Replication effect estimate") +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 15), 
        axis.title = element_text(size = 15)) + 
  ggtitle("Correlation scale ") + 
  theme(plot.title = element_text(color = "red", size = 25))

gg_z2 <- ggplot(data = SSRP, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 5, shape = 21, 
             fill = "midnightblue") +
  labs(x = "Original effect estimate", 
       y = "Replication effect estimate") +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 15), 
        axis.title = element_text(size = 15)) +
  ggtitle("Fisher-z scale") + 
  theme(plot.title = element_text(color = "red", size = 25))

grid.arrange(gg_r2, gg_z2, 
             ncol = 2)
@
\end{frame}

\begin{frame}{Social sciences replication project}
  \framesubtitle{Pyc and Rawson (2010), Science}
<< echo = FALSE >>=
study <- subset(SSRP,
                study == "Pyc and Rawson (2010), Science")
study$c <- with(study, se_fiso^2/se_fisr^2)

ggplot(data = SSRP, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.2, size = 7, shape = 21, 
             fill = "midnightblue") +
  geom_point(data = study,
             alpha = 1, size = 7, shape = 21, 
             fill = "red") +
  
   labs(x = expression(paste("Original effect estimate ", hat(theta)[o])), 
       y = expression(paste("Replication effect estimate ", hat(theta)[r]))) +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
@
\end{frame}

\begin{frame}{\citet{Pyc2010}. Science}
\framesubtitle{Original discovery: ``Testing improves memory'' }
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
library(biostatUZH)
options(scipen = 5)
plot_df <- data.frame(Study = c("Original study", 
                                "Replication study"),
                      z = c(study$fiso, study$fisr),
                      r = c(study$ro, study$rr),
                      p = formatPval(x = c(study$po/2,
                                           study$pr/2)),
                      se = c(study$se_fiso, study$se_fisr),
                      n = c(1/study$se_fiso^2 + 3, 
                            1/study$se_fisr^2 + 3)) 
study_plot <- ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
   labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
study_plot
@
\begin{center}
\vspace{-.6cm}
\hspace{.75cm}
{\small
\begin{tabular}{rcl}
$n_o$ $\qquad$ & Sample size & $\qquad$ $n_r$ \\
$\hat \theta_o$ $\qquad$ & Effect estimate & $\qquad$ $\hat \theta_r$ \\
$\sigma_o$ $\qquad$ & Standard error & $\qquad$ $\sigma_r$ \\
 $p_o$ $\qquad$ & one-sided $p$-value &$\qquad$  $p_r$ \\
  &&
  \end{tabular}
}
\end{center}
\end{minipage}
\end{frame}

\begin{frame}{\citet{Pyc2010}. Science}
\framesubtitle{Original discovery: ``Testing improves memory'' }
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
library(biostatUZH)
options(scipen = 5)
plot_df <- data.frame(Study = c("Original study", 
                                "Replication study"),
                      z = c(study$fiso, study$fisr),
                      r = c(study$ro, study$rr),
                      p = formatPval(x = c(study$po/2,
                                           study$pr/2)),
                      se = c(study$se_fiso, study$se_fisr),
                      n = c(1/study$se_fiso^2 + 3, 
                            1/study$se_fisr^2 + 3)) 
study_plot <- ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  annotate("text", x = 1.5, y = study$ro, 
           label = "?", size = 55, 
           color = "red") + 
  ylim(-0.05, 1) +
   labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
study_plot
@
\vspace{-0.5cm}
\begin{block}{}
\begin{itemize}
  \item[] {\color{red} Relative effect size} $d = \hat\theta_r/\hat\theta_o = 
  \Sexpr{round(study$fisr/study$fiso, 2)}$
  \item[] {\color{red} Relative sample size} $c = n_r/n_o = 9$
\end{itemize}
\end{block}
\end{minipage}
\end{frame}

\begin{frame}{When is a replication successful?}
\section{When is a replication successful?}
\begin{minipage}[t][3cm][t]{\textwidth}
\vspace{-1.5em}
\begin{block}{Some proposed criteria}
  \begin{enumerate}
    \item Two-trials rule (statistical significance)
    \item Compatibility of effect estimates
    \item Meta-analysis of estimates
  \end{enumerate}
  \pause
  \begin{enumerate}
    \item[4.]{\color{black!25} Sceptical $p$-value (tomorrow)}
  \end{enumerate}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
study_plot
@
\end{minipage}
\end{frame}


\begin{frame}{1. Two-trials rule}
\begin{minipage}[t][3cm][t]{\textwidth}
\begin{block}{}
{\large \textit{Are both estimates statistically significant in the same direction?}} 

$\rightarrow$ Which threshold? \\
$\rightarrow$ one-sided {$\color{red} \alpha = 0.025$} 
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 10, color = "red") +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 10, color = "red") +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
   labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
@
\end{minipage}
\end{frame}

\begin{frame}{2. Compatibility of effect estimates}
\begin{minipage}[t][3cm][t]{\textwidth}
\begin{block}{}
% {\large \textit{Is the replication estimate contained in its prediction interval?}} \\
{\large \textit{Is the meta-analytic $Q$-test of the estimates statistically 
significant?}} 

% Replication effect contained in its prediction interval? \\ 
% $\rightarrow$ function \texttt{predictionInterval()} \\
% $\rightarrow$ $Q$-test statistically significant at two-sided $\alpha = 0.05$? \\ 
$\rightarrow$ Which threshold? \\
$\rightarrow$ two-sided {\color{springgreen4}$\alpha = 0.05$}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
pi_df <- predictionInterval(thetao = study$fiso,
                            seo = study$se_fiso,
                            ser = study$se_fisr)
pi_df <- tanh(pi_df)
q_pval <- Qtest(thetao = study$fiso, thetar = study$fisr, 
                seo = study$se_fiso, ser = study$se_fisr)

ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  annotate(geom = "text", x = 1.47, y = 0.8,
           label = paste("italic(p)[Q] ==~", formatPval(q_pval)),
           color = "springgreen4", size = 10, parse = TRUE) +
   geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
  labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
@
\end{minipage}
\end{frame}

\begin{frame}{3. Meta-analysis of effect estimates}
\begin{minipage}[t][3cm][t]{\textwidth}
\begin{block}{}
{\large \textit{Is a meta-analytic estimate statistically significant?}} 

$\rightarrow$ Which threshold? \\
$\rightarrow$ {\color{tan3} two-sided $\alpha = 0.05$ or $0.005$} used in 
practice\\
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
var_ma_estimate <- with(study, 1/(1/se_fiso^2 + 1/se_fisr^2))
ma_estimate <- with(study, fiso/se_fiso^2 + fisr/se_fisr^2)*
               var_ma_estimate
p_ma <- pnorm(abs(ma_estimate/sqrt(var_ma_estimate)),
              lower.tail = FALSE)*2
ma_data <- data.frame(se = sqrt(var_ma_estimate),
                      ma_estimate = ma_estimate,
                      ma_estimate_r = tanh(ma_estimate),
                      p_ma = formatPval(p_ma),
                      stringsAsFactors = FALSE)

ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_pointrange(data = ma_data,
                  aes(x = 1.5, y = ma_estimate_r, 
                      ymin = ma_estimate - qnorm(0.975)*se,
                      ymax = ma_estimate + qnorm(0.975)*se),
                  size = 1.5, color = "tan3") +
  geom_text(data = ma_data, color = "tan3",
            aes(x = 1.4, y = ma_estimate_r, 
                label = paste("italic(p)[M] ==~", p_ma)),
            nudge_y = 0.31, nudge_x = 0.12, 
            size = 10, parse = TRUE) +
    geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
  labs(x = " ", y = "Effect Size") + 
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 30))
@
\end{minipage}
\end{frame}




\begin{frame}
\section{Exercise 1 -- Analysis of replication studies}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Package ReplicationSuccess}} 
   \end{center}
  % \end{block}
\end{frame}


\begin{frame}[fragile]{Package ReplicationSuccess}
% \begin{itemize}
  % \item Statistical methods and functionality for the design and analysis of replication studies \\
  %% $\rightarrow$ Traditional methods \\
  %% $\rightarrow$ Sceptical $p$-value \citep{Held2020}
  % \end{itemize}
%%   \centering
%% \includegraphics[width=0.75\textwidth]{images_presentation/Held2019.png}
  
%% \end{frame}
\vspace{-0.8cm}
%% \begin{frame}[fragile]{Installation}
  \begin{block}{}
    \begin{itemize}
      %% \item Statistical methods and functionality for the design and analysis of replication studies (work in progress!)
      \item Installation
<< eval = FALSE, size = "footnotesize" >>=
# development version 
devtools::install_github(repo = "SamCH93/ReplicationSuccess",
                         ref = "T1Econtrol")

# CRAN version 
install.packages("ReplicationSuccess")
@
      \item Usage
    << size = "small", eval = FALSE >>=
library(ReplicationSuccess)
vignette("ReplicationSuccess")
?pSceptical # documentation
news(package = "ReplicationSuccess") # news page
@
  \end{itemize}
  \end{block}
\end{frame}

\begin{frame}[fragile]{Statistical framework}
\begin{block}{}
\begin{itemize}
\item Effect estimates are assumed to be {\color{red} normally distributed} 
after suitable transformation \\
$\rightarrow$ {\color{red} Fisher's $z$-transformation} for correlation 
coefficients $r$ with (effective) sample size $n - 3$
\end{itemize}
\end{block}
<< echo = FALSE, fig.height = 4.5 >>=
# Second axis for Fisher z-scale
lims_r <- tanh(seq(0, 1, 0.5))
labs_r <- round(lims_r, 2)

ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.25) +
  geom_text(aes(label = paste("italic(r) ==~", 
                              round(r, 2), 
                              sep = "")), parse = TRUE, 
            nudge_x = c(-0.31, 0.27), nudge_y = 0.1, size = 6) +
  geom_text(aes(label = paste("'fis' ==~", 
                              round(z, 2), 
                              sep = "")), parse = TRUE, 
            nudge_x = c(-0.31, 0.27), nudge_y = -0.1, size = 6) +
  scale_y_continuous(limits = c(-0.05, 1.2), 
                     breaks = seq(0, 2.5, 0.5),
                     sec.axis = sec_axis(trans = ~tanh(.), 
                                         breaks = lims_r,
                                         labels = labs_r,
                                         name = expression(paste("Correlation ", italic(r))))) + 
  labs(x = " ", y = expression(paste("Fisher-",italic(z)))) + 
  theme_bw() + 
  theme(axis.text = element_text(size = 20), 
        axis.title = element_text(size = 25)) 
@
\end{frame}

\begin{frame}[fragile]{Data sets}
<<eval=FALSE, size = "small" >>=
?RProjects # Documentation
@
\begin{block}{Most important variables}
\begin{table}
\centering
\begin{tabular}{l l}
  \texttt{project} & Replication project \\
  \texttt{ro} & Original effect on correlation scale \\
  \texttt{rr} & Replication effect on correlation scale \\
  \texttt{fiso} & Original effect on Fisher-$z$ scale \\
  \texttt{fisr} & Replication effect on Fisher-$z$ scale \\
  \texttt{se\_fiso} & Standard error of \texttt{fiso} \\
  \texttt{se\_fisr} & Standard error of \texttt{fisr} 
\end{tabular}
\end{table}
\end{block}
\end{frame}

\begin{frame}[fragile]{Statistical framework of package}
<< echo = FALSE >>=
po <- study$po
pr <- study$pr
to <- study$fiso/study$se_fiso
tr <- study$fisr/study$se_fisr
c <- study$se_fiso^2/study$se_fisr^2
@

\begin{block}{Key quantities}
\begin{itemize}
\item $z$-value $z_o$ or (one-sided) $p$-value $p_o$ of original study
<< size = "small" >>=
RProjects$zo <- RProjects$fiso/RProjects$se_fiso
RProjects$po1 <- z2p(RProjects$zo, 
                     alternative = "one.sided")
@
\pause
\item $z$-value $z_r$ or (one-sided) $p$-value $p_r$ of replication study
<< size = "small" >>=
RProjects$zr <- RProjects$fisr/RProjects$se_fisr
RProjects$pr1 <- z2p(RProjects$zr, 
                     alternative = "one.sided")
@
\pause
\item relative sample size (or variance ratio) $c = \sigma_o^2/\sigma_r^2 =  n_r/n_o$
<< size = "small" >>=
RProjects$c <- RProjects$se_fiso^2/RProjects$se_fisr^2
@
\end{itemize}
\end{block}
\end{frame}


\begin{frame}
\section{Exercise 1 -- Analysis of replication studies}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Preparatory exercises}} 
   \end{center}
  % \end{block}
\end{frame}

\begin{frame}[fragile]{Preparatory exercises}
\begin{block}{}
\begin{enumerate}
\item Install the development version of the package + other required packages
<<eval = F>>=
install.packages("devtools")
install.packages("meta")
install.packages("ggplot2")
devtools::install_github(repo = "SamCH93/ReplicationSuccess",
                         ref = "T1Econtrol")

@


\item Load the packages and the data sets with
\vspace{-0.5em}
<<eval = FALSE >>=

library(meta)
library(ReplicationSuccess)
data("RProjects") 

@
\end{enumerate}
\end{block}
\end{frame}


\begin{frame}[fragile]{Preparatory exercises}
\begin{block}{}
\begin{enumerate}
\item[3.] Compute the key quantities $z_o$, $z_r$, $c$, and the one-sided $p$-values $p_o$ and $p_r$ with
<<>>=
RProjects$zo <- RProjects$fiso/RProjects$se_fiso
RProjects$zr <- RProjects$fisr/RProjects$se_fisr
RProjects$c <- RProjects$se_fiso^2/RProjects$se_fisr^2
RProjects$po1 <- z2p(RProjects$zo, 
                     alternative = "one.sided")
RProjects$pr1 <- z2p(RProjects$zr, 
                     alternative = "one.sided")
@


\item[4.] Explore the \texttt{ReplicationSuccess} package
<<>>=
# for example
vignette("ReplicationSuccess")
?RProjects
@
\end{enumerate}
\end{block}
\end{frame}


\begin{frame}
\section{Exercise 1 -- Analysis of replication studies}
  % \begin{block}{}
  \begin{center}
  {\color{uzh@blue}\Huge \textbf{Exercise Session 1}} 
  \\~\\
  {\LARGE Analysis of replication studies with traditional methods}
   \end{center}
  % \end{block}
\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
For all study pairs from the replication projects
\end{block}
  \begin{block}{Exercise 1.1}
Plot the original effect estimate against the replication effect estimate 
(on Fisher $z$-scale). What do you observe?
  \end{block}
    \begin{block}{}
{\color{darkred} Useful function: \texttt{plot()}}
    \end{block}
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
For all studies from the replication projects investigate
\end{block}
  \begin{block}{Exercise 1.2}
     How many study pairs fulfill the \textbf{two-trials rule} criterion for 
     replication success? Use a threshold of $\alpha = 0.025$ for the one-sided 
     $p$-values.
  \end{block}
    \begin{block}{}
{\color{darkred} Useful function: \texttt{z2p(..., alternative = "one.sided")}}
    \end{block}
\end{frame}
  
\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
For all studies from the replication projects investigate
\end{block}
  \begin{block}{Exercise 1.3}
    \begin{itemize}
    \item [(a)] For how many study pairs do you find evidence for \textbf{incompatible} effect 
    estimates (on Fisher $z$-scale)? Use a threshold of $\alpha = 0.05$ for the resulting $p$-value.
    \end{itemize}
  \end{block}
  
      \begin{block}{}
{\color{darkred} Useful function: \texttt{Qtest()}}
    \end{block}
\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
{\color{white} For all studies from the replication projects investigate}
\end{block}
  \begin{block}{Exercise 1.3}
    \begin{itemize}
    \item [(b)] {\bf Compare} the results from exercises 1.2 and 1.3 a). 
    \item[] Do all the study pairs with evidence for {\bf incompatibility} 
    also fail the {\bf two-trials rule?}
    \item[] Do all the study pairs without evidence for {\bf incompatibility}
    fulfill the two-trials rule?
    \end{itemize}
  \end{block}
  \end{frame}
  
  
  
  \begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
For all studies from the replication projects
\end{block}
  \begin{block}{Exercise 1.4}
    \begin{itemize}
\item[a)] Compute the {\bf fixed effect meta-analytic} $p$-value $p_M$.
How many study pairs
fulfill the meta-analysis criterion? Use a threshold of
$\alpha = 0.05$ for the {\bf two-sided $p_M$}.
  \end{itemize}
  \end{block}

    \begin{block}{}
{\color{darkred} Useful function: \texttt{metagen(...)\$pval.fixed}}
    \end{block}
\end{frame}


  \begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
{\color{white} For all studies from the replication projects investigate}
\end{block}
  \begin{block}{Exercise 1.4}
    \begin{itemize}
      \item[b)] Compare the results from exercises 1.3 a) and 1.4 a). 
      Can studies with {\bf incompatible effect estimates} and which 
      {\bf fail the two-trials rule} fulfill the 
      {\bf meta-analysis criterion}?
    \end{itemize}


  \end{block}
\end{frame}


\begin{frame}{}
  \begin{center}
  {\color{foo} \Huge\bf  Solutions}
  \end{center}
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.1}

<<echo = F>>=



gg_zAll <- ggplot(data = RProjects, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.5, size = 7, shape = 21, 
             fill = "midnightblue") +
  labs(x = expression(paste("Original effect estimate ", hat(theta)[o])), 
       y = expression(paste("Replication effect estimate ", hat(theta)[r]))) +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 18), 
        axis.title = element_text(size = 25)); gg_zAll
@

\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.2}
<< echo = FALSE, results = "asis" >>=
# for (p in unique(RProjects$project)) {
#   data_project <- subset(RProjects, project == p)
#   significant_O <- data_project$po < 0.05
#   significant_R <- data_project$pr < 0.05
#   success <- significant_O & significant_R & 
#       (sign(data_project$fiso) == sign(data_project$fisr))
#   cat(paste0(p, ": \n"))
#   cat(paste0(round(mean(significant_O)*100, 1), "% original studies significant (", 
#              sum(significant_O), "/", length(significant_O), ")\n"))
#   cat(paste0(round(mean(significant_R)*100, 1), "% replications significant (", 
#              sum(significant_R), "/", length(significant_R), ")\n"))
#   cat(paste0(round(mean(success)*100, 1), 
#              "% both significant, same direction (",
#              sum(success), "/", length(success), ") \n \n"))
# }

## compute for all projects
significant_O <- RProjects$po1 < 0.025
significant_R <- RProjects$pr1 < 0.025
RProjects$TTR <- significant_O & significant_R
allDF <- data.frame(project = "all", success = mean(RProjects$TTR)*100, 
                    type = "significance",
                    successFormat = paste0(round(mean(RProjects$TTR)*100, 0), "\\% (", 
                                           sum(RProjects$TTR), "/", 
                                           length(RProjects$TTR), ")"))

## compute for each project
signSuccessList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  success <- data_project$TTR
  data.frame(project = p, success = mean(success)*100, type = "significance",
             successFormat = paste0(round(mean(success)*100, 0), "\\% (", 
                                    sum(success), "/", length(success), ")"))
})
signSuccessDF <- do.call("rbind", signSuccessList)

## table
library(xtable)
dfTable1 <- rbind(signSuccessDF, allDF)[,c(1, 4)]
Table1 <- xtable(dfTable1, digits = 1)
colnames(Table1) <- c("Project", "Both $p$-values < 0.025")
print(Table1, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x})
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.2}
<< echo = FALSE >>=
## Plots of effect estimates
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  data_project <- subset(RProjects, project == p)
  significant_O <- data_project$po1 < 0.025
  significant_R <- data_project$pr1 < 0.025
  success <- significant_O & significant_R
  col_success <- color <- ifelse(success == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(mean(success)*100, 0), 
                  "% (", sum(success), "/", length(success), ")")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_success, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", 
         legend = c(expression(paste("both ", italic(p), "-values < 0.025")), 
                    expression(paste("not both ", italic(p), "-values < 0.025"))),
         # c("both significant", "not both significant"), 
         pch = 20, pt.cex = 2, cex = 1.4,
         # title = "signficant in same direction (5%)",
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.3}
\framesubtitle{Part a)}
\makebox[1 \textwidth][c]{  
  \resizebox{1\textwidth}{!} {
<< echo = FALSE, results = "asis" >>=
## computing zo, zr, c
RProjects$zo <- with(RProjects, fiso/se_fiso)
RProjects$zr <- with(RProjects, fisr/se_fisr)
RProjects$c <- with(RProjects, se_fiso^2/se_fisr^2)

## compute for all projects
RProjects$pQ <- Qtest(thetao = RProjects$fiso, thetar = RProjects$fisr,
                      seo = RProjects$se_fiso, ser = RProjects$se_fisr)
RProjects$Qincompatible <- RProjects$pQ <= 0.05
allQDF <- data.frame(project = "all", incomp = mean(RProjects$Qincompatible)*100, 
                     type = "Q-test",
                     incompFormat = paste0(round(mean(RProjects$Qincompatible)*100, 0),
                                           "\\% (", sum(RProjects$Qincompatible),
                                           "/", length(RProjects$Qincompatible), ")"))

## compute for each project
QList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  data.frame(project = p, incomp = mean(data_project$Qincompatible)*100, type = "Q-test",
             incompFormat = paste0(round(mean(data_project$Qincompatible)*100, 0), 
                                    "\\% (", sum(data_project$Qincompatible), "/", 
                                    length(data_project$Qincompatible), ")"))
})
QDF <- do.call("rbind", QList)


## table
dfTable2 <- rbind(QDF, allQDF)[,c(1, 4)]
Table2 <- xtable(dfTable2, digits = 1)
colnames(Table2) <- c("Project", 
                      "Incompatible estimates ($p_Q < 0.05$)")
print(Table2, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x}, floating = FALSE)
@
  }
}
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.3}
  \framesubtitle{Part a)}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  pval_Q_project <- Qtest(thetao = data_project$fiso,
                          thetar = data_project$fisr,
                          seo = data_project$se_fiso,
                          ser = data_project$se_fisr)
  incompatible <- pval_Q_project < 0.05
  PropIncomp <- mean(incompatible)
  color <- ifelse(incompatible == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(PropIncomp*100, 0), '% incompatible')
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = color, pch = 20,
       cex.main = 1.7, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", 
         c(expression(italic(p)[Q] < 0.05), expression(italic(p)[Q] >= 0.05)),
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.3}
  \framesubtitle{Part b) Example I}

<<echo = F, fig.height = 2, fig.width = 5>>=
library(ReplicationSuccess)
library(tidyverse)
library(meta) 
source("functions.R") 
ind.Qincompatible <- which(RProjects$Qincompatible)
incomp <- RProjects[ind.Qincompatible, ]
no.incomp <- RProjects[-ind.Qincompatible,]
ex1 <- incomp[1,]
ex2 <- incomp[23,]
ex3 <- no.incomp[42,]

pQ_ex1 <- with(ex1, Qtest(thetao = fiso, thetar = fisr, 
                          seo = se_fiso, ser = se_fisr))
scepticalCI_ex1 <- with(ex1, scepticalCI(thetao = fiso, thetar = fisr, 
                          seo = se_fiso, ser = se_fisr))$CI

with(ex1, ForestPlot(thetahat = c(fiso, fisr), 
                    se = c(se_fiso, se_fisr), 
                    title = study))

@
  \begin{block}{}
    \begin{itemize}
      \item $Q$-test $p$-value: $p_Q = \Sexpr{biostatUZH::formatPval(pQ_ex1)}$; 
      {\color{red} conflict}
      % \item sceptical 95\%-CI: $\Sexpr{biostatUZH::formatCI(scepticalCI_ex1)}$
      \item {\color{red} Two-trials rule unsuccessful}
    \end{itemize}
  \end{block}
  
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.3}
  \framesubtitle{Part b)}
<<results = 'asis', echo = F>>=
library(xtable)
incompSuccess <- paste("\\cellcolor{red!25}{", sum(RProjects$pQ <= 0.05 & RProjects$TTR), "}")
compSuccess <-  sum(RProjects$pQ > 0.05 & RProjects$TTR)
incompNoSuccess <- sum(RProjects$pQ <= 0.05 & !RProjects$TTR)
compNoSuccess <- paste("\\cellcolor{red!25}{", sum(RProjects$pQ > 0.05 & !RProjects$TTR), "}")


comp <- c("$p_Q > 0.05$", compSuccess, compNoSuccess)
incomp <- c("$p_Q \\leq 0.05$", incompSuccess, incompNoSuccess)

mat <- matrix(c(comp, incomp), nrow = 2, byrow = T)
colnames(mat) <- c(" ", "yes", "no")


xt.mat <- xtable(mat, align = "cc|cc")
addtorow <- list()
addtorow$pos <- list( -1)
addtorow$command <- c(" & \\multicolumn{2}{c}{Success two-trials rule} \\\\\n")
print(xt.mat, 
      sanitize.text.function=identity, 
      add.to.row = addtorow, 
       hline.after = c(0,2), 
      include.rownames = F)

@

\begin{itemize}
  \item[] $\rightarrow$ {\color{red!75} Incompatible} effect estimates can fulfill the 
  {\color{red!75} two-trials rule}
  \item[] $\rightarrow$ $Q$-test {\color{red!75}
  does not take into account significance} 
  of the effect estimates
\end{itemize}
  
  \end{frame}
  
  



\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.3}
  \framesubtitle{Parts b) Example II}

<<echo = F, fig.height = 2, fig.width = 5>>=

pQ_ex2 <- with(ex2, Qtest(thetao = fiso, thetar = fisr,   
                          seo = se_fiso, ser = se_fisr))
scepticalCI_ex2 <- with(ex1, scepticalCI(thetao = fiso, thetar = fisr, 
                          seo = se_fiso, ser = se_fisr))$CI

with(ex2, ForestPlot(thetahat = c(fiso, fisr), 
                    se = c(se_fiso, se_fisr), 
                    title = study))

@
  \begin{block}{}
    \begin{itemize}
      \item $Q$-test $p$-value: $p_Q = \Sexpr{formatPval(pQ_ex2)}$; 
      {\color{red} conflict}
      % \item sceptical 95\%-CI: $\Sexpr{formatCI(scepticalCI_ex2)}$
      \item {\color{olive} Two-trials rule successful}
    \end{itemize}
  \end{block}
  
\end{frame}

 % 
 \begin{frame}<handout:0>[fragile]{Solution: Exercise 1.3}
  \framesubtitle{Part b) Example III}

<<echo = F, fig.height = 2, fig.width = 5>>=

pQ_ex3 <- with(ex3, Qtest(thetao = fiso, thetar = fisr, 
                          seo = se_fiso, ser = se_fisr))
scepticalCI_ex3 <- with(ex1, scepticalCI(thetao = fiso, thetar = fisr, 
                          seo = se_fiso, ser = se_fisr))$CI

with(ex3, ForestPlot(thetahat = c(fiso, fisr), 
                    se = c(se_fiso, se_fisr), 
                    title = study))
@
  \begin{block}{}
    \begin{itemize}
      \item $Q$-test $p$-value: $p_Q = \Sexpr{formatPval(pQ_ex3)}$; 
      {\color{olive} no conflict}
      % \item sceptical 95\%-CI: $\Sexpr{formatCI(scepticalCI_ex3)}$
      \item {\color{red} Two-trials rule unsuccessful}
    \end{itemize}
  \end{block}
  
\end{frame}



\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.4}
  \framesubtitle{Part a)}
<<echo = F, results = 'asis'>>=

pval_meta <- c()
for(i in 1:nrow(RProjects)){
  pval_meta[length(pval_meta) + 1] <- with(RProjects[i, ],
                                           metagen(TE = c(fiso, fisr),
                                                   seTE = c(se_fiso, se_fisr))$pval.fixed)
}

RProjects$pMeta <- pval_meta
RProjects$pMsuccess <- RProjects$pMeta < 0.05

allMetaDF <- data.frame(project = "all", meta = mean(RProjects$pMsuccess)*100, 
                     type = "Q-test",
                     metaFormat = paste0(round(mean(RProjects$pMsuccess)*100, 0),
                                           "\\% (", sum(RProjects$pMsuccess),
                                           "/", length(RProjects$pMsuccess), ")"))
## compute for each project
MetaList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  data.frame(project = p, meta = mean(data_project$pMsuccess)*100, type = "meta-analysis",
             metaFormat = paste0(round(mean(data_project$pMsuccess)*100, 0), 
                                    "\\% (", sum(data_project$pMsuccess), "/", 
                                    length(data_project$pMsuccess), ")"))
})
MetaDF <- do.call("rbind", MetaList) 

## table
dfTableMeta <- rbind(MetaDF, allMetaDF)[,c(1, 4)]
TableMeta <- xtable(dfTableMeta, digits = 1)
colnames(TableMeta) <- c("Project", 
                      "$p_M < 0.05$")
print(TableMeta, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x}, floating = FALSE)
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.4}
  \framesubtitle{Part a)}
<<echo = F>>=

par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  success <- data_project$pMeta < 0.05
  col_success <- ifelse(success == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(mean(success)*100, 0), "% (",
                  sum(success), "/",  length(success), ")")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_success, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", c(expression(italic(p)[M] < 0.05),
                      expression(italic(p)[M] >= 0.05)),
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 1.4}
  \framesubtitle{Part b)}
  
<<echo = F, fig.height = 2, fig.width = 5>>=
source("functions.R")
ind.weird <- which(RProjects$pMsuccess & RProjects$Qincompatible & !RProjects$TTR )
ex1.4 <- RProjects[ind.weird[3],]
with(ex1.4, 
     ForestPlot(thetahat = c(fiso, fisr), se = c(se_fiso, se_fisr), 
                metaAn = TRUE, 
                scepticalCI = F, 
                title = study))
@
   \begin{block}{}
    \begin{itemize}
      \item $Q$-test $p$-value: $p_Q = \Sexpr{formatPval(ex1.4$pQ)}$; 
      {\color{darkred} conflict}
      \item {\color{red} Two-trials rule unsuccessful}
      \item[] $\rightarrow$ {\bf Success with the meta-analysis criterion!}
    \end{itemize}
  \end{block}
\end{frame}


\begin{frame}{}
\begin{center}
  \color{uzh@blue}{\Huge \textbf{Conclusion}} \\[1cm]
  \color{uzh@blue}{\Large Traditional methods}
   \end{center}
\end{frame}



\begin{frame}{Assessement of replication success}
\begin{minipage}[t][3cm][t]{\textwidth}
\vspace{-1.5em}
\begin{block}{}
  \begin{itemize}
    \item {\color{Rred} Two-trials rule} doesn't take into account effect size
    \item {\color{springgreen4}$Q$-test} doesn't take into account significance
    \item {\color{tan3}Meta-analysis} assumes exchangeability and doesn't take 
    into account compatibility
  \end{itemize} 
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  # geom_text(data = data.frame(x = 1.5, y = 0.9, 
  #                             ps = formatPval(ps)),
  #           aes(x = x, y = y, 
  #               label = paste("italic(p)[S] ==~", ps, sep = "")),
  #           parse = TRUE, size = 10, color = "purple3") +
  geom_text(data = ma_data, color = "tan3",
            aes(x = 1.4, y = ma_estimate_r, 
                label = paste("italic(p)[M] ==~", p_ma)),
            nudge_y = 0.31, nudge_x = 0.12, 
            size = 10, parse = TRUE)  +
    annotate(geom = "text", x = 1.47, y = 0.7, 
             label = paste("italic(p)[Q] ==~", formatPval(q_pval)),
             color = "springgreen4", size = 10, parse = TRUE) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8, color = "red") +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8, color = "red") +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  geom_pointrange(data = ma_data,
                  aes(x = 1.5, y = ma_estimate_r, 
                      ymin = ma_estimate - qnorm(0.975)*se,
                      ymax = ma_estimate + qnorm(0.975)*se),
                  size = 1.5, color = "tan3") + 
   labs(x = " ", y = "Effect Size") +  
  ylim(-0.05, 1) +
  theme_bw() +
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30))
@
\end{minipage}
\end{frame}


\begin{frame}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Day two}}
   \end{center}
\end{frame}

\begin{frame}{When is a replication successful?}
\section{When is a replication successful?}
\begin{minipage}[t][3cm][t]{\textwidth}
\vspace{-1.5em}
\begin{block}{Some proposed criteria}
  \begin{enumerate}
    \item Two-trials rule (statistical significance)
    \item Compatibility of effect estimates
    \item Meta-analysis of estimates
  \end{enumerate}
  \begin{enumerate}
    \item[4.] \textbf{Sceptical $p$-value}
  \end{enumerate}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
study_plot
@
\end{minipage}
\end{frame}

\begin{frame}{4. Sceptical $p$-value}
\framesubtitle{New definition of replication success}
\vspace{1cm}
\begin{columns}
\begin{column}{0.3\textwidth}
  % \centering
\includegraphics[width=1.1\textwidth]{images_presentation/Held2020.png}

\vspace{6em}
\begin{center}
{\scriptsize \url{https://doi.org/10.1111/rssa.12493}}\\
  \color{white}{\scriptsize published in JRSSA}
\end{center}
\end{column}

\begin{column}{0.3\textwidth}
\includegraphics[width=0.95\textwidth]{images_presentation/Heldetal2021.png}

\vspace{0.8em}
\begin{center}
{\scriptsize \url{https://doi.org/10.1214/21-AOAS1502}}\\
  \end{center}
\end{column}

\begin{column}{0.3\textwidth}
\includegraphics[width=1.3\textwidth]{images_presentation/Held-etal2022.png}

\vspace{0.8em}
\begin{center}
{\scriptsize \url{https://arxiv.org/abs/2207.00464}}\\
  \color{darkred}{\scriptsize preprint}
  \end{center}
\end{column}
\end{columns}
\end{frame}

\begin{frame}{4. Sceptical $p$-value}
\framesubtitle{New definition of replication success}
\begin{minipage}[t][2.7cm][t]{\textwidth}
\vspace{-2.5em}
\begin{block}{}
\vspace{0.5em}
% 
% $\rightarrow$ \texttt{pSceptical()} returns one-sided sceptical $p$-value $p_S$ \\
% % per default 
% $\rightarrow$ recalibration by default

\vspace{.15cm}
\begin{center}
{\color{red} If $p_S \leq \alpha$ we have replication success at level $\alpha$} 
\end{center}
Two types of sceptical $p$-values: 
  \begin{itemize}
    \item {\color{orange} golden}
    \item {\color{blue} controlled}
  \end{itemize}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
ssv <- function(zo, so, a) {
  tau2 <- so^2/(zo^2/qnorm(p = a/2, lower.tail = FALSE)^2 - 1)
  return(tau2)
}
S <- function(U, L) (U - L)^2/(4*sqrt(U*L))

ps_uncalibrated <- pSceptical(zo = study$fiso/study$se_fiso, 
                              zr = study$fisr/study$se_fisr, 
                              c = study$se_fiso^2/study$se_fisr^2,
                              alternative = "one.sided", 
                              type = "nominal")
ps <- pSceptical(zo = study$fiso/study$se_fiso, 
                 zr = study$fisr/study$se_fisr, 
                 c = study$se_fiso^2/study$se_fisr^2,
                 alternative = "one.sided",
                 type = "golden")
psC <- pSceptical(zo = study$fiso/study$se_fiso, 
                 zr = study$fisr/study$se_fisr, 
                 c = study$se_fiso^2/study$se_fisr^2,
                 alternative = "one.sided",
                 type = "controlled")

s <- S(U = study$fiso + qnorm(0.975)*study$se_fiso,
       L = study$fiso - qnorm(0.975)*study$se_fiso)
tau2 <- ssv(zo = study$fiso/study$se_fiso, 
            so = study$se_fiso, a = ps_uncalibrated*2)
sprior_df <- data.frame(x = 1.5, mu = 0,
                        upper = qnorm(p = 0.975)*sqrt(tau2),
                        lower = qnorm(p = 0.025)*sqrt(tau2))
scept_plot <- ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  # geom_pointrange(data = sprior_df, 
  #                 aes(x = 1.5, y = 0, 
  #                     ymin = lower, ymax = upper),
  #                 color = "purple3", size = 1.5) +
  # geom_text(data = sprior_df, 
  #           aes(x = 1.5, y = upper,
  #               label = "sceptical prior"),
  #           nudge_y = 0.15, nudge_x = 0,
  #           color = "purple3", size = 9) +
  geom_text(data = data.frame(x = 1.5, y = 0.9, 
                              ps = formatPval(ps)),
            aes(x = x, y = y, 
                label = paste("italic(p)[S] ==~", ps, sep = "")),
            parse = TRUE, size = 10, color = "orange") +
  
    geom_text(data = data.frame(x = 1.5, y = 0.4, 
                              ps = formatPval(psC)),
            aes(x = x, y = y, 
                label = paste("italic(p)[S] ==~", formatPval(psC), sep = "")),
            parse = TRUE, size = 10, color = "blue") +
  
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  labs(x = " ", y = "Effect Size") + 
  ylim(-0.35, 1) +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
scept_plot
@
\end{minipage}
\end{frame}



\begin{frame}{Sceptical $p$-value}
<<echo = FALSE>>=
alpha = 0.025
alphaU_g <- levelSceptical(level = alpha, alternative = "one.sided", 
                           type = "golden")

@
  
      \begin{block}{Golden $p_S$}
        \begin{itemize}
        \item penalizes {\color{foo} shrinkage} of replication effect estimate
          \begin{itemize}
            \item[] $\rightarrow$ a {\color{red} borderline significant original 
            study} can only 
            lead to success if there is {\color{red} no shrinkage}
          \end{itemize}
          \pause
        \item controls Type-I error rate for $c > 1$, but {\color{red} not exactly}
        \pause
        \item {\color{red} Necessary condition:} $p_o$ and $p_r$
        $< \Sexpr{biostatUZH::formatPval(alphaU_g)}$.
        \end{itemize}
      \end{block}
  
\end{frame}

\begin{frame}{Shrinkage penalization}
  \framesubtitle{Relative effect size perspective}
<<echo = F, fig.height = 4.5>>=
# Figure 5 - preparation
par(las = 1, mfrow = c(1, 2))

zalpha = p2z(alpha, alternative = "one.sided")

eps <-  10e-4
myplim <- c(eps, 0.15)
mydlim <- c(0.15, 15)

pos <-  seq(10e-200, 0.15, length.out = 1000)
zos <- p2z(pos, alternative = "one.sided")

c.seq <-  c(0.5, 1, 2, 5, 10)
col.seq <- c(5, 4, 3 , 2, 1)

resultsCont <- results2TR <- resultsGold <-  matrix(NA, nrow = length(zos), ncol = length(c.seq))

for(i in 1:length(c.seq)){
    resultsCont[, i] <- effectSizeReplicationSuccess(zo = zos, c = c.seq[i], level = alpha, 
                                                     alternative = "one.sided",
                                                     type = "controlled")
    results2TR[, i] <- ifelse(zos > zalpha,  effectSizeSignificance(zo = zos, c = c.seq[i], level = alpha, 
                                              alternative = "one.sided"), NA)
    resultsGold[, i]  <- effectSizeReplicationSuccess(zo = zos, c = c.seq[i], level = alpha, 
                                                      type = "golden", alternative = "one.sided")
}


# bound on p-value
u_seq <- levelSceptical(level = alpha, 
                        c = c.seq, 
                        alternative = "one.sided", 
                        type = "controlled")


### golden plot
plot(NULL , 
     xlim = myplim, 
     ylim = mydlim, 
     xlab = expression(paste("Original ", italic(p), "-value ", italic(p[o]))), 
     ylab = expression(paste("Relative effect size ", italic(d))), 
     log = "xy", 
     xaxt = "n")##, axes=FALSE)
title(main = "golden", line = 3)


box()
abline(v = c(alpha), 
       lty = 2, 
       col = "darkgrey")

axis(1, at = c(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1), 
     labels = c(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1))


axis(3, at = alpha, labels = alpha, cex.axis = 0.75, las = 2, col.ticks = "darkgrey", col.axis = "darkgrey")



yi =  exp(seq(log(1.5), log(0.325), length.out = 5))

for(i in 1:length(c.seq)){
    lines(pos, 
          resultsGold[, i], 
          type = "l", , 
          col = col.seq[i], 
          lwd = 2)
  lines(pos, 
        lty = 2,
        results2TR[, i], 
        col = alpha(col.seq[i], 0.9), 
        lwd = 2)
    # where <- which.min((pos - alpha)^2)
    # 
    #     text(0.01, yi[i],
    #      labels = bquote(italic(c) == .(c.seq[i])),
    #      col = alpha(col.seq[i], 0.75),
    #      cex = 0.8)
}

axis(3, at = alphaU_g, labels = formatPval(alphaU_g), 
     las = 2)

legend("topleft", 
       c("c = 10", "c = 5", "c = 2", "c = 1", "c = 0.5", "c = 0.2"), 
       col = rev(col.seq), 
       lty = 1, 
       bty = "n")

legend("bottomright", 
       c("golden", "two-trials rule"), 
       col = "black", 
       lty = 1:2,
         lwd = 2, 
       bg = "white", 
       bty = "n")





@

\end{frame}


\begin{frame}{Sceptical $p$-value}
<<echo = FALSE>>=
alpha = 0.025
alphaU_g <- levelSceptical(level = alpha, alternative = "one.sided", 
                           type = "golden")

@

      \begin{block}{Controlled $p_S$}
        \begin{itemize}
          \item {\color{red} exact} Type-I error control {\color{red} at level 
          $\alpha^2 = \Sexpr{format(alpha^2, scientific = FALSE)}$.}
          \item no shrinkage penalization
          \item {\color{red} Necessary condition:} 
          upper bound on $p_o$ and $p_r$ {\color{red} depends on $c$}.
        \pause
        \item Allow calculation of {\bf sceptical confidence interval}
        and {\bf $p$-value function}.
        \end{itemize}
      \end{block}
  
\end{frame}

\begin{frame}{Shrinkage penalization}
  \framesubtitle{Relative effect size perspective}
<<echo = F, fig.height = 4.5>>=
# Figure 5 - preparation
par(las = 1, mfrow = c(1, 2))

zalpha = p2z(alpha, alternative = "one.sided")

eps <-  10e-4
myplim <- c(eps, 0.15)
mydlim <- c(0.15, 15)

pos <-  seq(10e-200, 0.15, length.out = 1000)
zos <- p2z(pos, alternative = "one.sided")

c.seq <-  c(0.5, 1, 2, 5, 10)
col.seq <- c(5, 4, 3 , 2, 1)

resultsCont <- results2TR <- resultsGold <-  matrix(NA, nrow = length(zos), ncol = length(c.seq))

for(i in 1:length(c.seq)){
    resultsCont[, i] <- effectSizeReplicationSuccess(zo = zos, c = c.seq[i], level = alpha, 
                                                     alternative = "one.sided",
                                                     type = "controlled")
    results2TR[, i] <- ifelse(zos > zalpha,  effectSizeSignificance(zo = zos, c = c.seq[i], level = alpha, 
                                              alternative = "one.sided"), NA)
    resultsGold[, i]  <- effectSizeReplicationSuccess(zo = zos, c = c.seq[i], level = alpha, 
                                                      type = "golden", alternative = "one.sided")
}


# bound on p-value
u_seq <- levelSceptical(level = alpha, 
                        c = c.seq, 
                        alternative = "one.sided", 
                        type = "controlled")


### golden plot
plot(NULL , 
     xlim = myplim, 
     ylim = mydlim, 
     xlab = expression(paste("Original ", italic(p), "-value ", italic(p[o]))), 
     ylab = expression(paste("Relative effect size ", italic(d))), 
     log = "xy", 
     xaxt = "n")##, axes=FALSE)
title(main = "golden", line = 3)


box()
abline(v = c(alpha), 
       lty = 2, 
       col = "darkgrey")

axis(1, at = c(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1), 
     labels = c(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1))


axis(3, at = alpha, labels = alpha, cex.axis = 0.75, las = 2, col.ticks = "darkgrey", col.axis = "darkgrey")



yi =  exp(seq(log(1.5), log(0.325), length.out = 5))

for(i in 1:length(c.seq)){
    lines(pos, 
          resultsGold[, i], 
          type = "l", , 
          col = col.seq[i], 
          lwd = 2)
  lines(pos, 
        lty = 2,
        results2TR[, i], 
        col = alpha(col.seq[i], 0.9), 
        lwd = 2)
    # where <- which.min((pos - alpha)^2)
    # 
    #     text(0.01, yi[i],
    #      labels = bquote(italic(c) == .(c.seq[i])),
    #      col = alpha(col.seq[i], 0.75),
    #      cex = 0.8)
}

axis(3, at = alphaU_g, labels = formatPval(alphaU_g), 
     las = 2)

legend("topleft", 
       c("c = 10", "c = 5", "c = 2", "c = 1", "c = 0.5"), 
       col = rev(col.seq), 
       lty = 1, 
       bty = "n")

legend("bottomright", 
       c("golden", "two-trials rule"), 
       col = "black", 
       lty = 1:2,
         lwd = 2, 
       bg = "white", 
       bty = "n")


# controlled


plot(NULL , 
     xlim = myplim, 
     ylim = mydlim, 
     xlab = expression(paste("Original ", italic(p), "-value ", italic(p[o]))), 
     ylab = expression(paste("Relative effect size ", italic(d))), 
     log = "xy", 
     xaxt = "n") ##, axes=FALSE)
title(main = "controlled", line = 3)


box()
abline(v = c(alpha), 
       lty = 2, 
       col = "darkgrey")

axis(1, at = c(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1), 
     labels = c(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1))

for (i in 1:length(u_seq)){
axis(3, at = u_seq[i], label = round(u_seq[i], 3), col.ticks= col.seq[i], 
     col.axis = col.seq[i], 
     las = 2, 
     cex.axis = 0.75)
  }
axis(3, at = alpha, labels = alpha, cex.axis = 0.75, las = 2, col.ticks = "darkgrey", col.axis = "darkgrey")



yi =  exp(seq(log(1.5), log(0.325), length.out = 5))

for(i in 1:length(c.seq)){
    lines(pos, 
          resultsCont[, i], 
          type = "l", , 
          col = col.seq[i], 
          lwd = 2)
  lines(pos, 
        lty = 2,
        results2TR[, i], 
        col = alpha(col.seq[i], 0.9), 
        lwd = 2)
    # where <- which.min((pos - alpha)^2)
    # 
    #     text(0.01, yi[i],
    #      labels = bquote(italic(c) == .(c.seq[i])),
    #      col = alpha(col.seq[i], 0.75),
    #      cex = 0.8)
}

legend("bottomright", 
       c("controlled", "two-trials rule"), 
       col = "black", 
       lty = 1:2,
         lwd = 2, 
       bg = "white", 
       bty = "n")


@
\end{frame}

\begin{frame}{Controlled sceptical $p$-value}
  \framesubtitle{Upper bound on $p_o$ and $p_r$ for $\alpha = 0.025$.}
  \begin{block}{}
$\rightarrow$ {\color{red} Necessary,} but not sufficient condition for replication success
\end{block}
\vspace{-1cm}
<<echo = F, fig.height = 3.3, fig.width = 4.5>>=
par(las = 1, 
    mar = c(5.1, 4.1, 4.1, 3.2))
alpha = 0.025
cval <- c(0.5, 1, 2, 5, 10)
aval <- levelSceptical(c = cval, alternative = "one.sided", level = alpha, 
                        type = "controlled")


addon = 0.003
alphaU <- seq(alpha+.001, 0.145, 0.001)
mycol <- col.seq


alphaU <- c(alpha, alphaU)
c <- c(0, c)  

c_plot <- seq(0.5, 20, by = 0.01)
alphaU_plot <- levelSceptical(level = alpha, 
                              c = c_plot, 
                              alternative = "one.sided", 
                              type = "controlled")
c_sub2 <- c(0.5, 1, 2, 5, 10)



plot(c_plot + addon, alphaU_plot, type="l", lwd=1.5, xlab=bquote(paste("Relative sample size ", c)),
     ylab = "upper bound", axes=FALSE, 
                  log = "xy", cex.lab = 0.8, ylim = c(0.05, 0.15), xlim = c(0.4, 10))
            axis(2, at = aval, labels =formatPval(aval), cex.axis = 0.6, 
                 mgp = c(1, 0.9, 0))
            
            myalphaU <- numeric()
            for(i in 1:length(c_sub2)){
              axis(1, at = c_sub2[i] + addon, labels = c_sub2[i], cex.axis = 0.65, 
                   col.ticks = mycol[i], col.axis = mycol[i])
               myalphaU[i] <- levelSceptical(c = c_sub2[i], level = alpha, type = "controlled")
              points(c_sub2[i] + addon, myalphaU[i], pch=19, col = mycol[i], cex = 0.75)
              lines( c(10e-10, c_sub2[i] + addon), rep(myalphaU[i],2), lty=2, col = mycol[i], 
                    lwd = 1.5)
              lines(rep(c_sub2[i] + addon,2), c(10e-10, myalphaU[i]), lty=2, col = mycol[i], lwd = 1.5)
            }
            box()
@

\end{frame}



\begin{frame}
\section{Exercise 1 -- Analysis of replication studies}
  % \begin{block}{}
  \begin{center}
  {\color{uzh@blue} \Huge \textbf{Exercise Session 2}} 
  \\~\\
  {\LARGE Analysis of replication studies with the sceptical $p$-value}
   \end{center}
  % \end{block}
\end{frame}



\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}

For all studies from the replication projects 
  \begin{block}{Exercise 2.1}
  
  \begin{itemize}
    \item[a)]  Compute the one-sided \textbf{golden sceptical $p$-value}.
    How many replication 
    studies are successful at level $0.025$? 
  \end{itemize}
  \end{block}
  
    \begin{block}{}
{\color{darkred} Useful function: \texttt{pSceptical(..., type = "golden")}
}
    \end{block}
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}

For all studies from the replication projects 
  \begin{block}{Exercise 2.1}
  
  \begin{itemize}
    \item[b)]  Compute the one-sided \textbf{controlled sceptical $p$-value}.
    How many replication 
    studies are successful at level $0.025$? 
  \end{itemize}
  \end{block}
  
    \begin{block}{}
{\color{darkred} Useful function: \texttt{pSceptical(..., type = "controlled")}
}
    \end{block}
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 2.1}
  
  \begin{itemize}
    \item[c)]  Plot the {\bf golden sceptical $p$-value} against the 
    {\bf controlled one}.
    How many study pairs disagree at the 0.025 level? Have a closer look at 
    these studies. 
  \end{itemize}
  \end{block}
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 2.2}
  \begin{itemize}
    \item[a)] Look closer at the studies which show \textbf{discrepancies} in terms of replication 
    success based on the \textbf{two-trials rule} and the sceptical $p$-value 
    \textbf{\color{red}(controlled)}.
    What do you observe?
  \end{itemize}
  \end{block}
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 2.2}
  \begin{itemize}
    \item[b)] Look closer at the studies which show \textbf{discrepancies} in terms of replication 
    success based on the \textbf{two-trials rule} and the sceptical $p$-value 
    \textbf{\color{red} (golden)}.
    What do you observe?
  \end{itemize}
  \end{block}
\end{frame}





\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
{\color{white}For all studies from the replication projects investigate}
\end{block}
  \begin{block}{Exercise 2.3}
    \begin{itemize}
    \item [a)] Choose one study pair where the estimates are
    incompatible (according to $p_Q$). \\
    Calculate the 95\% sceptical confidence interval. What do you observe?
    \end{itemize}
  \end{block}
  
      \begin{block}{}
{\color{darkred} Useful function: \texttt{scepticalCI(..., 
levelCI = 0.95)}}
    \end{block}
\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
{\color{white} For all studies from the replication projects investigate}
\end{block}
  \begin{block}{Exercise 2.3}
    \begin{itemize}
    \item [b)] For the same study, 
    plot the $p$-value function.
    \end{itemize}
  \end{block}
  
      \begin{block}{}
{\color{darkred} Useful function: \texttt{pValFunPlot(..., 
levelCI = 0.95)}}
    \end{block}
\end{frame}

\begin{frame}{}
  \begin{center}
  {\color{foo} \Huge\bf  Solutions}
  \end{center}
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.1}
\framesubtitle{Parts a) and b)}
<< echo = FALSE, fig.height = 4, results = "asis" >>=
## computing one.sided sceptical p-value for replication projects

RProjects$ps <- with(RProjects, pSceptical(zo = zo, zr = zr, c = c, 
                                           alternative = "one.sided",
                                           type = "golden"))
RProjects$psC <- with(RProjects, pSceptical(zo = zo, zr = zr, c = c, 
                                           alternative = "one.sided",
                                           type = "controlled"))

## compute for all projects
RProjects$pSsuccess <- RProjects$ps < 0.025
RProjects$pSsuccessC <- RProjects$psC < 0.025
allpsDF <- data.frame(project = "all", success = mean(RProjects$pSsuccess)*100, 
                      type = "psceptical",
                      successFormat = paste0(round(mean(RProjects$pSsuccess)*100, 0),
                                             "\\% (", sum(RProjects$pSsuccess), 
                                             "/", length(RProjects$pSsuccess), ")"))

allpsDFC <- data.frame(project = "all", success = mean(RProjects$pSsuccessC)*100, 
                      type = "pscepticalC",
                      successFormat = paste0(round(mean(RProjects$pSsuccessC)*100, 0),
                                             "\\% (", sum(RProjects$pSsuccessC), 
                                             "/", length(RProjects$pSsuccessC), ")"))


## compute for each project
psList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  data.frame(project = p, success = mean(data_project$pSsuccess)*100, 
             type = "psceptical",
             successFormat = paste0(round(mean(data_project$pSsuccess)*100, 0), 
                                    "\\% (", sum(data_project$pSsuccess), "/",
                                    length(data_project$pSsuccess), ")"))
})
psDF <- do.call("rbind", psList)

# also for type = "controlled
psList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  data.frame(project = p, success = mean(data_project$pSsuccessC)*100, 
             type = "pscepticalC",
             successFormat = paste0(round(mean(data_project$pSsuccessC)*100, 0), 
                                    "\\% (", sum(data_project$pSsuccessC), "/",
                                    length(data_project$pSsuccessC), ")"))
})
psDFC <- do.call("rbind", psList)

## table
dfTable3 <- cbind(rbind(psDF, allpsDF), rbind(psDFC, allpsDFC))[,c(1, 4, 8)]
Table3 <- xtable(dfTable3, digits = 1)
colnames(Table3) <- c("Project", "$p_S$ (golden) $< 0.025$", 
                      "$p_S$ (controlled) $< 0.025$")
print(Table3, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x}, 
      scalebox = '0.8')
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.1}
\framesubtitle{golden recalibration}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  success <- data_project$ps < 0.025
  col_success <- ifelse(success == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(mean(success)*100, 0), "% (",
                  sum(success), "/",  length(success), ")")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_success, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", c(expression(italic(p)[s] < 0.025),
                      expression(italic(p)[s] >= 0.025)),
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.1}
\framesubtitle{controlled recalibration}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  success <- data_project$psC < 0.025
  col_success <- ifelse(success == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(mean(success)*100, 0), "% (",
                  sum(success), "/",  length(success), ")")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_success, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", c(expression(italic(p)[s] < 0.025),
                      expression(italic(p)[s] >= 0.025)),
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.1}
  \framesubtitle{Part c)}
<<echo = F, fig.height = 4, fig.width = 5>>=


discrepantDF2 <- subset(RProjects, pSsuccess != pSsuccessC)[, c("study", "c", "ro", 
                                                        "rr", "po1", "pr1", "ps",
                                                        "psC", "zo", "se_fiso", "se_fisr", "fiso", "fisr")]

col_success2 <- ifelse(RProjects$pSsuccess == RProjects$pSsuccessC, "#333333B3", "#8B0000B3")
ggplot(data= RProjects, aes(x = ps, y = psC)) +
    geom_point(aes(size = c), color = col_success2) +
  coord_cartesian(xlim = c(10e-5, 1), ylim = c(10e-5, 1)) + 
  geom_abline(intercept = 0, slope = 1, color = "grey") + 
  geom_hline(yintercept = alpha, linetype = "dashed") +
   geom_vline(xintercept = alpha, linetype = "dashed") +
  xlab(expression(paste(italic(p[S]), " (golden)"))) + 
  ylab(expression(paste(italic(p[S]), " (controlled)"))) + 
    theme_bw()  +
  theme(axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10), 
        panel.background = element_blank()) + 
  scale_size_continuous(breaks = c(0.2, 1, 2, 3, 4)) +
   scale_y_continuous(trans='log', 
                      breaks = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1),
                      labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1)) + 
  scale_x_continuous(trans='log', 
                     breaks = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1),
                      labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1))  

@

\end{frame}

\begin{frame}{Exercise 2.1}
  \framesubtitle{Part c)}
<<echo = FALSE>>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  discrep <- data_project$pSsuccess != data_project$pSsuccessC
  col_discord <- ifelse(discrep == TRUE,
                 ifelse(data_project$pSsuccess == TRUE,
                        "#8B0000B3", "#00008AB3"), "#B2B2B299")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = p, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_discord, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", legend = c(expression(paste("golden ", italic(p)[s], " only")),
    expression(paste("controlled ", italic(p)[s], " only"))),
         title = "success",
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#00008AB3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.1}
\framesubtitle{Part c)}

\makebox[1 \textwidth][c]{  
  \resizebox{1.1\textwidth}{!} {
<<echo = F, results = 'asis'>>=

phighlighfun <- function(p) {
 ifelse(p > 0.025,
        paste0("\\textcolor{red}{", biostatUZH::formatPval(p), "}"),
        paste0("\\textcolor{black}{",  biostatUZH::formatPval(p), "}"))
}



discrepantDF2$c <- as.character(round(discrepantDF2$c, 1))
discrepantDF2$ro <- as.character(round(discrepantDF2$ro, 2))
discrepantDF2$rr <- as.character(round(discrepantDF2$rr, 2))
discrepantDF2$po1 <- phighlighfun(discrepantDF2$po1)
discrepantDF2$pr1 <- phighlighfun(discrepantDF2$pr1)
discrepantDF2$ps <- phighlighfun(discrepantDF2$ps)
discrepantDF2$psC <- phighlighfun(discrepantDF2$psC)

discTab2 <- xtable(discrepantDF2[, 1:(ncol(discrepantDF2)-5)])
colnames(discTab2) <- c("Study", "$n_r / n_o$", "$r_o$", "$r_r$", "$p_o$", 
                       "$p_r$", "$p_s$ (gold)", "$p_S$ (contr)")
print(discTab2, include.rownames = FALSE, booktabs = TRUE,
      sanitize.text.function = function(x) {x}, size = "small",
      floating = FALSE)
@
  }
}
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.2}
\framesubtitle{Part a)}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  discrep <- data_project$pSsuccessC != data_project$TTR
  col_discord <- ifelse(discrep == TRUE,
                 ifelse(data_project$pSsuccessC == TRUE,
                        "#8B0000B3", "#00008AB3"), "#B2B2B299")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = p, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_discord, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", legend = c(expression(paste("controlled ", italic(p)[s], " only")),
                      "two-trials rule only"),
         title = "success",
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#00008AB3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.2}
\framesubtitle{Part a)}
\makebox[1 \textwidth][c]{  
  \resizebox{1.2\textwidth}{!} {
<< echo = FALSE, fig.height = 4, results = "asis" >>=
RProjects$study2 <- RProjects$study
RProjects$study2[RProjects$study == "K Oberauer"] <- "Oberauer (2008)"
RProjects$study2[RProjects$study == "JR Schmidt, D Besner"] <- 
  "Schmidt and Besner (2008)"
RProjects$study2[RProjects$study == "BK Payne, MA Burkley, MB Stokes"] <- 
  "Payne, Burkley, and Stokes (2008)"
RProjects$study2[RProjects$study == "Balafoutas and Sutter (2012), Science"] <- 
  "Balafoutas and Sutter (2012)"
RProjects$study2[RProjects$study == "Pyc and Rawson (2010), Science"] <- 
  "Pyc and Rawson (2010)"
RProjects$study2[RProjects$study == "Nichols (2006)"] <- 
  "Nichols (2006)"

## discrepant studies
discrepantDF <- subset(RProjects, pSsuccessC != TTR)[, c("study", "c", "ro", 
                                                        "rr", "po1", "pr1",
                                                        "psC", "zo", "se_fiso", "se_fisr", "fiso", "fisr")]
discrepantDF$c <- as.character(round(discrepantDF$c, 1))
discrepantDF$ro <- as.character(round(discrepantDF$ro, 2))
discrepantDF$rr <- as.character(round(discrepantDF$rr, 2))
discrepantDF$po1 <- phighlighfun(discrepantDF$po1)
discrepantDF$pr1 <- phighlighfun(discrepantDF$pr1)
discrepantDF$psC <- phighlighfun(discrepantDF$psC)

discTab <- xtable(discrepantDF[, 1:(ncol(discrepantDF)-5)])
colnames(discTab) <- c("Study", "$n_r / n_o$", "$r_o$", "$r_r$", "$p_o$", 
                       "$p_r$", "$p_s$ (controlled)")
print(discTab, include.rownames = FALSE, booktabs = TRUE,
      sanitize.text.function = function(x) {x}, size = "small",
      floating = FALSE)
@
 }
}
\end{frame}



\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.2}
\framesubtitle{Part b)}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  discrep <- data_project$pSsuccess != data_project$TTR
  col_discord <- ifelse(discrep == TRUE,
                 ifelse(data_project$pSsuccess == TRUE,
                        "#8B0000B3", "#00008AB3"), "#B2B2B299")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = p, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_discord, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", legend = c(expression(paste("golden ", italic(p)[s], " only")),
                      "two-trials rule only"),
         title = "success",
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#00008AB3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.2}
\framesubtitle{Part b)}
\makebox[1 \textwidth][c]{  
  \resizebox{1.2\textwidth}{!} {
<< echo = FALSE, fig.height = 4, results = "asis" >>=
RProjects$study2 <- RProjects$study
RProjects$study2[RProjects$study == "K Oberauer"] <- "Oberauer (2008)"
RProjects$study2[RProjects$study == "JR Schmidt, D Besner"] <- 
  "Schmidt and Besner (2008)"
RProjects$study2[RProjects$study == "BK Payne, MA Burkley, MB Stokes"] <- 
  "Payne, Burkley, and Stokes (2008)"
RProjects$study2[RProjects$study == "Balafoutas and Sutter (2012), Science"] <- 
  "Balafoutas and Sutter (2012)"
RProjects$study2[RProjects$study == "Pyc and Rawson (2010), Science"] <- 
  "Pyc and Rawson (2010)"
RProjects$study2[RProjects$study == "Nichols (2006)"] <- 
  "Nichols (2006)"

## discrepant studies
discrepantDF <- subset(RProjects, pSsuccess != TTR)[, c("study", "c", "ro", 
                                                        "rr", "po1", "pr1",
                                                        "ps", "zo", "se_fiso", "se_fisr", "fiso", "fisr")]
discrepantDF$c <- as.character(round(discrepantDF$c, 1))
discrepantDF$ro <- as.character(round(discrepantDF$ro, 2))
discrepantDF$rr <- as.character(round(discrepantDF$rr, 2))
discrepantDF$po1 <- phighlighfun(discrepantDF$po1)
discrepantDF$pr1 <- phighlighfun(discrepantDF$pr1)
discrepantDF$ps <- phighlighfun(discrepantDF$ps)

discTab <- xtable(discrepantDF[, 1:(ncol(discrepantDF)-5)])
colnames(discTab) <- c("Study", "$n_r / n_o$", "$r_o$", "$r_r$", "$p_o$", 
                       "$p_r$", "$p_s$ (golden)")
print(discTab, include.rownames = FALSE, booktabs = TRUE,
      sanitize.text.function = function(x) {x}, size = "small",
      floating = FALSE)
@
 }
}
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.3}
  \framesubtitle{Part a)}
  
<<echo = F, fig.height = 2.5, fig.width = 4>>=
with(ex1.4, 
     ForestPlot(thetahat = c(fiso, fisr), 
                se = c(se_fiso, se_fisr), 
                scepticalCI = T, 
                metaAn = T, 
                title = study))
@
  
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 2.3}
  \framesubtitle{Part b)}
  
<<echo = F, fig.height = 2.5, fig.width = 4>>=
with(ex1.4, 
     pValFunPlot(thetao = fiso, thetar = fisr, 
                 seo = se_fiso, ser = se_fisr))
@
  
\end{frame}


\begin{frame}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Design of replication studies}}
   \end{center}
\end{frame}


\begin{frame}{Design of replication studies}
\begin{block}{Sample size of replication study}
  \begin{itemize}
  \item Direct replication $\rightarrow$ procedures of replication study as closely matched as possible to original study 
\item \alert{But} same sample size as in original study can lead to a very low power \citep{Goodman1992}
\item[] $\rightarrow$ proper sample size calculation is essential 
  \end{itemize}
\end{block}
\centering
\includegraphics[width=0.8\textwidth]{images_presentation/goodmana.pdf}
\end{frame}

\begin{frame}{Two strategies}
\begin{block}{Sample size calculation}
\vspace{1.2cm}
\begin{itemize}
  \item Based on the two-trials rule 
  \item[] {\color{gray} Standard practice}\\[1cm]
  \item Based on the sceptical $p$-value
  \item[] {\color{gray} New developments}
\end{itemize}
\end{block}
\end{frame}


\begin{frame}{Two strategies}
\begin{block}{Sample size calculation}
\vspace{1.2cm}
\begin{itemize}
  \item {\bf Based on the two-trials rule} 
   \item[] {\bf \color{gray} Standard practice} \\[1cm]
  \item Based on the sceptical $p$-value
   \item[] {\color{gray} New developments}
\end{itemize}
\end{block}
\end{frame}


\begin{frame}[fragile]{What is used in practice}
\begin{block}{Standard sample size calculation}
  \begin{itemize}
<< echo = FALSE, eval = FALSE >>=
sampleSizeZtest = function(delta, sd, sig.level = 0.05, power){
  u <- qnorm(p = power)
  v <- qnorm(p = 1 - sig.level/2)
  n <- 2*(u + v)^2*sd^2/delta^2
  return(n)
}
sampleSizeZtest(delta = 0.25, sd = 0.4, sig.level = 0.01, power = 0.95)
@
    \item Goal is to have high power (usually 80\%-95\%) to achieve a 
    {\color{red} significant replication $p$-value $p_r$.}
    \item Conditional on the {\color{red}{effect estimate from the original study}}.
    \item Original effect estimate is sometimes shrunken by a factor of 50\%.
    \item Uncertainty of original effect estimate is ignored
  \end{itemize}
\end{block}
\end{frame}

\begin{frame}{Standard sample size calculation}
<<echo = F>>=
sampleSizeZtest = function(delta, sd, sig.level = 0.05, power){
  u <- qnorm(p = power)
  v <- qnorm(p = 1 - sig.level/2)
  n <- 2*(u + v)^2*sd^2/delta^2
  return(n)
}

grid <- seq(0.09, 0.225, 0.001)
deltahat <- 0.15
se <- 0.025
ss <- sampleSizeZtest(delta = grid, sd = 0.4, sig.level = 0.01, power = 0.95)
ss1 <- sampleSizeZtest(delta = deltahat, sd = 0.4, sig.level = 0.01, power = 0.95)

set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)

legend("topright", 
       "Power = 95%", 
       bty = "n", 
       cex = 1.75)

@

\end{frame}


\begin{frame}{Standard sample size calculation}
<<echo = F>>=

set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)
lines(rep(deltahat, 2), 
      c(0, ss1), 
      lty=2,
      lwd = 2)
points(deltahat, 
       ss1, 
       pch=19, 
       cex=1.2, 
       col=1) 
points(deltahat, 
       0, 
       pch=19, 
       cex=1.2, 
       col=1) 
lines(c(0, deltahat), 
      rep(ss1, 2), 
      lty = 2,
      col = 1, 
      lwd = 2)
axis(2, 
     at=ss1, 
     label=round(ss1), 
     col=1, 
     col.axis=1, 
     cex.axis = 1.2)

legend("topright", 
       "Power = 95%", 
       bty = "n",
       cex = 1.75)

@

\end{frame}
\begin{frame}{Incorporation of uncertainty}
<<echo = F>>=

set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)
lines(rep(deltahat, 2), 
      c(0, ss1), 
      lty=2,
      lwd = 2)
points(deltahat, 
       ss1, 
       pch=19, 
       cex=1.2, 
       col=1) 
points(deltahat, 
       0, 
       pch=19, 
       cex=1.2, 
       col=2) 
lines(c(0, deltahat), 
      rep(ss1, 2), 
      lty = 2,
      col = 1, 
      lwd = 2)
axis(2, 
     at=ss1, 
     label=round(ss1), 
     col=1, 
     col.axis=1, 
     cex.axis = 1.2)

plotCI(x = deltahat,
       y = 0, 
       li = quantile(deltahat2, 0.025), 
       ui = quantile(deltahat2, 0.975),
       col=2, lwd=2, add=TRUE, err="x")


legend("topright", 
       "Power = 95%", 
       bty = "n",
       cex = 1.75)

@
\end{frame}

\begin{frame}{Incorporation of uncertainty}
<<echo = F>>=
set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)
lines(rep(deltahat, 2), 
      c(0, ss1), 
      lty=2,
      lwd = 2)
points(deltahat, 
       ss1, 
       pch=19, 
       cex=1.2, 
       col=1) 
points(deltahat, 
       0, 
       pch=19, 
       cex=1.2, 
       col=2) 
points(min(grid), 
       mean(ss2), 
       pch=19, 
       cex=1.2, 
       col=2) 
lines(c(0, deltahat), 
      rep(ss1, 2), 
      lty = 2,
      col = 1, 
      lwd = 2)
axis(2, 
     at=ss1, 
     label=round(ss1), 
     col=1, 
     col.axis=1, 
     cex.axis = 1)

plotCI(x = deltahat, y=0, li=quantile(deltahat2, 0.025), ui = quantile(deltahat2, 0.975),
       col=2, lwd=2, add=TRUE, err="x")

plotCI(x = min(grid), y=mean(ss2), li=quantile(ss2, 0.025), ui = quantile(ss2, 0.975),
       col=2, lwd=2, add=TRUE, err="y")
lines(rep(quantile(deltahat2, 0.025), 2), 
      c(0, quantile(ss2, 0.975)), 
      lty=2, col=2,  
      lwd = 2)
lines(rep(quantile(deltahat2, 0.975), 2), 
      c(0, quantile(ss2, 0.025)), 
      lty=2, col=2, 
      lwd = 2)
lines(c(0, quantile(deltahat2, 0.975)), 
      rep(quantile(ss2, 0.025), 2), 
      lty=2, 
      col=2, 
      lwd = 2)
lines(c(0, quantile(deltahat2, 0.025)), 
      rep(quantile(ss2, 0.975), 2), 
      lty =2, 
      col=2, 
      lwd = 2)
axis(2, 
     at=mean(ss2), 
     label=round(mean(ss2)), 
     col = 2, 
     col.axis = 2, 
     cex.axis = 1.2)

legend("topright", 
       "Power = 95%", 
       bty = "n",
       cex = 1.75)

@
\end{frame}


\begin{frame}{Incorporation of uncertainty}
\begin{block}{Design prior}
\begin{itemize}
\item{\color{red} \emph{Conditional}}: ignores uncertainty of original study
\item {\color{red} \emph{Predictive}}: reflects that there is 
uncertainty about the true effect after the original experiment
\end{itemize}
\end{block}
\end{frame}

\begin{frame}{}
 \begin{center}
  {\Huge \bf \color{foo} Exercise session 3}
  \\~\\
  {\LARGE Design based on the two-trials rule}
 \end{center}
\end{frame}


\begin{frame}{Design based on the two-trials rule} 
%%    \framesubtitle{Functions}
  \begin{block}{}
Two functions: 
    \begin{itemize}
    \item \texttt{powerSignificance()} and \texttt{sampleSizeSignificance()}
    \end{itemize}

\pause

Main arguments (\texttt{default}):
\begin{itemize}
\item \texttt{zo}
\item \texttt{c} (\texttt{1})
\item \texttt{power}
\item \texttt{designPrior} (\texttt{"conditional"})
\item \texttt{shrinkage} (\texttt{0})
\item \texttt{level} (\texttt{0.025})
\item \texttt{alternative} (\texttt{"one.sided"})
\end{itemize}

\end{block}
\end{frame}

\begin{frame}[fragile]{Example from \citet{Pyc2010}}
% \framesubtitle{No shrinkage}
  \begin{block}{}
    \begin{itemize}
      \item $p$-value $p_o =$ \Sexpr{round(study$po/2, 3)}
      \item relative sample size $c =$ \Sexpr{round(study$c,1)}
    \end{itemize}

  \end{block}
  
<<>>=

# power calculation
powerSignificance(zo = p2z(0.011, alternative = "one.sided"), 
                  c = 9.2, 
                  designPrior = "conditional")
@
  
\end{frame}

% \begin{frame}[fragile]{Example from \citet{Pyc2010}}
% \framesubtitle{With 50\% shrinkage}
%   \begin{block}{}
%     \begin{itemize}
%       \item $p$-value $p_o =$ \Sexpr{round(study$po/2, 3)}
%       \item relative sample size $c =$ \Sexpr{round(study$c,1)}
%     \end{itemize}
% 
%   \end{block}
%   
<<echo = F, eval = F>>=

# power calculation
powerSignificance(zo = p2z(0.011, alternative = "one.sided"),
                  c = 9.2,
                  shrinkage = 0.5,
                  designPrior = "conditional")
@
%   
% \end{frame}

\begin{frame}{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{Exercise 3.1}
We have five original studies that we want to replicate. The one-sided $p$-values are 
$0.0001$, $0.001$, $0.005$, $0.01$, and $0.025$, respectively. 
We decide to use the same sample size as in the original study ($c = 1$). 
\begin{itemize}
\item Compute and plot the conditional and predictive power of the five replication studies.
\end{itemize}
  \end{block}
  \begin{block}
    {\color{darkred} Useful function: \texttt{powerSignificance(..., designPrior = c("conditional", "predictive))}}
  \end{block}
<<echo = FALSE, eval = F>>=

pval.or <- c(0.0001, 0.001, 0.005, 0.01, 0.03, 0.05)
pow.cond <- powerSignificance(zo = p2z(pval.or), c = 0.6, designPrior = "conditional")
pow.pred <- powerSignificance(zo = p2z(pval.or), c = 0.6, designPrior = "predictive")
plot(pval.or, pow.cond, type = "p", col = "red", ylim = c(0,100))
lines(pval.or, pow.pred, col = "blue")
  @
\end{frame}

\begin{frame}{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 3.2}
% We now know that taking the same sample size as in the original study is not optimal and want to perform a proper sample size calculation. 
\begin{itemize}
\item Compute and plot the relative sample sizes of the five studies to achieve a power of 80\% with the conditional and the predictive design prior. Use the function \texttt{sampleSizeSignificance()}.
\end{itemize}
  \end{block}
  
    \begin{block}
    {\color{darkred} Useful function: \texttt{sampleSizeSignificance(..., designPrior = c("conditional", "predictive))}}
  \end{block}
  
\end{frame}


\begin{frame}{}
  \begin{center}
  {\color{foo} \Huge\bf  Solutions}
  \end{center}
\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 3.1}

<<echo = FALSE, eval = T, fig.height = 8>>=
par(las = 1)

pval.or <- c(0.0001, 0.001, 0.005, 0.01, 0.025)
pow.cond <- powerSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional")
pow.condRS <- powerReplicationSuccess(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional")
pow.condshrink <- powerSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional", shrinkage=0.25)
pow.pred <- powerSignificance(zo = p2z(pval.or, alternative = "one.sided"),
                              c = 1, designPrior = "predictive")
pow.predRS <- powerReplicationSuccess(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "predictive")
ss.cond <- sampleSizeSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              power=0.8, designPrior = "conditional")
ss.condshrink <- sampleSizeSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              power=0.8, designPrior = "conditional", shrinkage=0.25)
ss.pred <- sampleSizeSignificance(zo = p2z(pval.or, alternative = "one.sided"),
                              power=0.8, designPrior = "predictive")
plot(pval.or, pow.cond*100, type = "p", col = "red", ylim = c(0,100), 
     xlab = "One-sided original p-value",
     ylab = "Power (in %)", pch = 20, cex = 1.75, 
     cex.lab = 1.5, 
     cex.axis = 1.5)
points(pval.or, pow.pred*100, col = "blue", pch = 20, cex = 1.75)
legend("topright", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       pch = 20, bty = "n", 
       cex = 2.2)
  @

\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 3.1}
<<echo = FALSE, eval = T, fig.height = 8>>=
par(las = 1)

po.plot <- seq(0.000001, 0.025, by = 0.0001)
pow.cond1 <- powerSignificance(zo = p2z(po.plot, alternative = "one.sided"),
                               c = 1, designPrior = "conditional")
pow.pred1 <- powerSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                               c = 1, designPrior = "predictive")
plot(po.plot, pow.cond1*100, col = "red", ylim = c(0,100), type = "l", 
           xlab = "One-sided original p-value",
     ylab = "Power (in %)", lwd = 1.8, 
     cex.lab = 1.5, 
     cex.axis = 1.5)
lines(po.plot, pow.pred1*100, col = "blue", lwd = 2)
points(pval.or, pow.cond*100, col = "red", pch = 20, cex = 1.75)
points(pval.or, pow.pred*100, col = "blue", pch = 20, cex = 1.75)
abline(h = 50, lty = 3)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")

legend("topright", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       lty = 1, bty = "n", 
       cex = 2.2, lwd = 2)

  @

\end{frame}





\begin{frame}<handout:0>{Solution: Exercise 3.2}
<<echo = FALSE, fig.height = 8>>=
par(las = 1)

ss.cond1 <- sampleSizeSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                                  power = 0.8, designPrior = "conditional")
ss.pred1 <- sampleSizeSignificance(zo = p2z(po.plot, alternative = "one.sided"),
                                  power = 0.8, designPrior = "predictive" )

plot(po.plot, ss.cond1, type = "l", ylim = c(0, 4), col = "red", 
     xlab = "One-sided original p-value", 
     ylab = "Relative sample size", 
     lwd = 2,
     cex.lab = 1.5, 
     cex.axis = 1.5)
lines(po.plot, ss.pred1, col = "blue", lwd = 2)
abline(h = c(1, 2, 3), col = "grey", lty = 2)
points(pval.or, ss.cond, col = "red", pch = 20, cex = 1.75)
points(pval.or, ss.pred, col = "blue", pch = 20, cex = 1.75)
legend("topleft", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       lty = 1, bty = "n", 
       cex = 2.2, 
       lwd = 2,
       bg = "white")


@
  
\end{frame}





\begin{frame}{Two strategies}
\begin{block}{Sample size calculation}
\vspace{1.2cm}
\begin{itemize}
  \item {Based on the two-trials rule} 
   \item[] {\color{gray} Standard practice} \\[1cm]
  \item  {\bf Based on the sceptical $p$-value}
   \item[] {\color{gray} \bf New developments}
\end{itemize}
\end{block}
\end{frame}


\begin{frame}{Sample size calculation based on $p_S$}
  \begin{itemize}
  \item Goal is to have high power to achieve 
  {\color{red} a `significant' {\it sceptical} $p$-value}: $p_S < 0.025$ (controlled or golden)
  \item {\color{red} Conditional} on the original effect estimate
  \item Can also take into account its uncertainty $\rightarrow$ {\color{red} predictive}
  \end{itemize}
\end{frame}








\begin{frame}
  \section{Exercise 3 -- Design of replication studies}
  % \begin{block}{}
  \begin{center}
  {\color{uzh@blue}\Huge \textbf{Exercise Session 4}}
  \\~\\
  {\LARGE Design based on the sceptical $p$-value}
   \end{center}
  % \end{block}
\end{frame}


\begin{frame}{Design based on replication success}
\begin{block}{}
Two functions:
    \begin{itemize}
    \item \texttt{powerReplicationSuccess()} and \texttt{sampleSizeReplicationSuccess()}
    \end{itemize}

\pause

Main arguments (\texttt{default}):
\begin{itemize}
\item \texttt{zo}
\item \texttt{c} (\texttt{1})
\item \texttt{power}
\item \texttt{designPrior} (\texttt{"conditional"})
\item \texttt{shrinkage} (\texttt{0})
\item \texttt{level} (\texttt{0.025})
\item \texttt{alternative} (\texttt{"one.sided"})
\item \texttt{type} (\texttt{"golden"})
\end{itemize}

\end{block}
\end{frame}

\begin{frame}[fragile]{Example from \citet{Pyc2010}}
    \begin{itemize}
      \item $p$-value $p_o =$ \Sexpr{round(study$po/2, 3)}
      \item relative sample size $c = $ \Sexpr{round(study$c,1)}
    \end{itemize}
<<>>=
# power calculation
powerReplicationSuccess(zo = p2z(0.011, alternative = "one.sided"), 
                        c = 9.2, 
                        designPrior = "conditional")

@

% Explain here why we use alpha level of 0.065 and one-sided test
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 4.1}
    \begin{itemize}
    \item For the same original studies as in exercise 2.1 and $c = 1$, 
    compare the power of the two-trials rule with the power of the 
    golden sceptical $p$-value (only conditional). 
    \item Repeat the exercise above but with the controlled sceptical 
    $p$-value instead of the golden one. 
    \end{itemize}
  \end{block}

\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 4.2}
    \begin{itemize}
    \item For the same original studies, compute and plot the relative
    sample sizes to achieve a conditional power of 80\% with the two-trials 
    rule and the golden sceptical $p$-value.
    \item Repeat the exercise above but with the controlled sceptical 
    $p$-value instead of the golden one. 
    \end{itemize}
  \end{block}

\end{frame}



\begin{frame}{}
  \begin{center}
  {\color{foo} \Huge\bf  Solutions}
  \end{center}
\end{frame}
\begin{frame}<handout:0>[fragile]{Solution: Exercise 4.1}

<<echo = F, fig.height = 8>>=
par(las = 1)
pow.cond2 <- powerReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                     c = 1, designPrior = "conditional", 
                                     alternative = "one.sided")

pow.pred2 <- powerReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                     c = 1, designPrior = "predictive", 
                                     alternative = "one.sided")

plot(po.plot, pow.cond2*100, type = "l", col = "red", ylim = c(0,100), 
     lwd = 2.1, 
     xlab = "One-sided original p-value", 
     ylab = "Power (in %)", 
     cex.lab = 1.5, 
     cex.axis = 1.5, 
     lty = 1)
lines(po.plot, pow.cond1*100, col = "blue", lwd = 2.1, lty = 1)
abline(h = 50, lty = 3, lwd = 1.5)
# points(pval.or, pow.condRS*100, col = "red", pch = 20, cex = 1.75)
# points(pval.or, pow.predRS*100, col = "blue", pch = 20, cex = 1.75)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")

legend("topright", 
        c("two-trials rule", expression(paste("golden ", p[S]))), 
        col = c("blue", "red"), 
       lty = 1.5, bty = "n", 
       cex = 2.2, 
       lwd = 2)

@

\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 4.1}

<<echo = F, fig.height = 8>>=
par(las = 1)
pow.cond3 <- powerReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                     c = 1, designPrior = "conditional", 
                                     alternative = "one.sided", 
                                     type = "controlled")

pow.pred3 <- powerReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                     c = 1, designPrior = "predictive", 
                                     alternative = "one.sided", 
                                     type = "controlled")

plot(po.plot, pow.cond3*100, type = "l", col = "red", ylim = c(0,100), 
     lwd = 2.1, 
     xlab = "One-sided original p-value", 
     ylab = "Power (in %)", 
     cex.lab = 1.5, 
     cex.axis = 1.5, 
     lty = 1)
lines(po.plot, pow.cond1*100, col = "blue", lwd = 2.1, lty = 1)
abline(h = 50, lty = 3, lwd = 1.5)
# points(pval.or, pow.condRS*100, col = "red", pch = 20, cex = 1.75)
# points(pval.or, pow.predRS*100, col = "blue", pch = 20, cex = 1.75)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")

legend("topright", 
        c("two-trials rule", expression(paste("controlled ", p[S]))), 
        col = c("blue", "red"), 
       lty = 1.5, bty = "n", 
       cex = 2.2, 
       lwd = 2)

@

\end{frame}

\begin{frame}<handout:0>[fragile]{Solution: Exercise 4.2}

 <<echo = F, fig.height = 7>>=
par(mfrow = c(1,1),
    las = 1)

ss.cond2 <- sampleSizeReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                         power = 0.8,
                                         alternative = "one.sided",
                                         type = "golden",
                                         designPrior = "conditional",
                                         level = 0.025)
ss.cond3 <- sampleSizeReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                         power = 0.8,
                                         alternative = "one.sided",
                                         type = "controlled",
                                         designPrior = "conditional",
                                         level = 0.025)

ss.pred2 <- sampleSizeReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                         power = 0.8,
                                         alternative = "one.sided",
                                         designPrior = "predictive",
                                         type = "golden",
                                         level = 0.025)
plot(po.plot,
     ss.cond2,
     type = "l",
     col = "red",
     ylim = c(0, 12),
     cex.lab = 1.5,
     cex.axis = 1.5,
     ylab = "Relative sample size",
      xlab = "One-sided original p-value",
     lwd = 2)

lines(po.plot,
      ss.cond1,
      type = "l",
      col = "blue",
      lwd = 2)

legend("topleft", 
        c("two-trials rule", expression(paste("golden ", p[S]))), 
        col = c("blue", "red"), 
       lty = 1.5, bty = "n", 
       cex = 2.2, 
       lwd = 2)
@
\end{frame}


\begin{frame}<handout:0>[fragile]{Solution: Exercise 4.2}


 <<echo = F, fig.height = 7>>=

par(mfrow = c(1,1),
    las = 1)

plot(po.plot,
     ss.cond3,
     type = "l",
     col = "red",
     ylim = c(0, 4),
     cex.lab = 1.5,
     cex.axis = 1.5,
     ylab = "Relative sample size",
      xlab = "One-sided original p-value",
     lwd = 2)

lines(po.plot,
      ss.cond1,
      type = "l",
      col = "blue",
      lwd = 2)

legend("topright", 
        c("two-trials rule", expression(paste("controlled ", p[S]))), 
        col = c("blue", "red"), 
       lty = 1.5, bty = "n", 
       cex = 2.2, 
       lwd = 2)

 @
\end{frame}


% 19.2.2021 Removed from time reason
% \begin{frame}[fragile]{Exercises}
% \framesubtitle{(Solutions available at \url{https://osf.io/fcrj6/})}
%   \begin{block}{Exercise 3.2}
%   For the experimental economics replication project
%   \begin{itemize}
%   \item Calculate the conditional power for replication success of each study with the controlled threshold
%     \item Compare it to the predictive power for replication success
%   \end{itemize}
%   \end{block}
% \end{frame}


% \begin{frame}[fragile]{Solution: Exercise 3.2}
<<echo = FALSE, fig.height=8, eval = F >>=
pow_c2 <- powerReplicationSuccess(zo = p2z(eco$po),
                                  c = eco$se_fiso^2/eco$se_fisr^2, 
                                  alternative = "one.sided",
                                  designPrior = "conditional")
pow_p2 <- powerReplicationSuccess(zo = p2z(eco$po),
                                  c = eco$se_fiso^2/eco$se_fisr^2, 
                                  alternative = "one.sided",
                                  designPrior = "predictive")

mat2 <- matrix(c(rep(eco$study, times=2),
                 pow_c2*100, pow_p2*100,rep(c("Conditional","Predictive"), 
                                            times=c(nrow(eco),nrow(eco)))), ncol=3)

colnames(mat2) <- c("ID","power", "group")
mat2 <- as.data.frame(mat2)
mat2$ID <- as.factor(mat2$ID)
mat2$group <- factor(mat2$group, levels=c("Conditional","Predictive"), order=TRUE)
mat2$power <- as.numeric(as.character(mat2$power))

bwplot(power~group, data=mat2, groups = ID, panel = panel_bw, 
        xlab=list(""),
        ylab=list("Power (in %)", cex = 2),
        between = list(x = 1), scales = list(x = "free", y="free", rot=0, cex =2),
        pch = "|")
@
% \end{frame}

% \begin{frame}{Exercises}
% \framesubtitle{(Solutions available at \url{https://osf.io/fcrj6/})}
%   \begin{block}{Exercise 3.3}
%   For the experimental philosophy replicability project
%   \begin{itemize}
%   \item Calculate for each study the required relative sample size to reach a power for replication success of 95\%. Use the  function \texttt{sampleSizeReplicationSuccess()} with conditional design prior and the controlled threshold ($\alpha$ = 0.065). 
%   \item Compare the results to the actually used relative sample sizes.
%   \end{itemize}
%   \end{block}
% \end{frame}
% 
% 
% \begin{frame}[fragile]{Solution: Exercise 3.3}
% \framesubtitle{Replication success}

<<fig.height = 7, echo = F, eval = F>>=
par(mai = c(1,1.5,1,1))

ss_c2 <- sampleSizeReplicationSuccess(zo = p2z(philo$po), power = 0.95, 
                             alternative = "one.sided",
                             designPrior = "conditional")

plot(ss_aut, ss_c2, 
     xlim = c(0.01,50), 
     ylim = c(0.01,50), 
     xlab = "Reported relative sample size", 
     ylab = "Calculated relative sample size", 
     pch = 20, 
     cex = 2.2, 
     cex.lab = 1.7, 
     cex.axis = 1.7, log = "xy",
     xaxt = "n", 
     yaxt = "n")
abline(a = 0, b = 1, 
       col = "lightpink")
axis(1, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)
axis(2, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)
@

% \end{frame}
% 
% \begin{frame}[fragile]{Solution: Exercise 2.4}
% \framesubtitle{Significance}

<<fig.height = 7, echo = FALSE, eval = F>>=
par(mai = c(1,1.5,1,1))
ss_aut <- philo$se_fiso^2/philo$se_fisr^2
ss_cond1 <- sampleSizeSignificance(zo = p2z(philo$po), power = 0.95,
                             designPrior = "conditional")

plot(ss_aut, ss_cond1, 
     xlim = c(0.01,50), 
     ylim = c(0.01,50), 
     xlab = "Reported relative sample size", 
     ylab = "Calculated relative sample size", 
     pch = 20, 
     cex = 2.2, 
     cex.lab = 1.7, 
     cex.axis = 1.7, 
     log = "xy", 
     xaxt = "n", 
     yaxt = "n")
abline(a = 0, b = 1, 
       col = "lightpink")

axis(1, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"),cex.axis = 1.4)
axis(2, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)


@

% \end{frame}



\begin{frame}
  \frametitle{}
  \centering
    \color{foo}{\Huge \bf Thank you for your attention!}
\end{frame}



\begin{frame}
  \frametitle{Acknowledgments}
  
  \begin{columns}
    \begin{column}{0.5\textwidth}
    \begin{center}
      \includegraphics[height=0.275\paperheight]{images_presentation/CRS.png}% \\
    \end{center}
    \begin{center}
    \includegraphics[width=4cm]{images_presentation/SwissRNLogowide.png} \\
    \end{center}
      \end{column}
      \begin{column}{0.5\textwidth}
      \vspace{0.5cm}
    \begin{center}
    \includegraphics[width=5cm]{images_presentation/logo.png}\\
    {\scriptsize \url{http://p3.snf.ch/Project-189295}}
    \end{center}
    \begin{center}
    \vspace{0.5cm}
      \includegraphics[width=1.65cm]{images_presentation/pawel_samuel.jpg}\\
    {\scriptsize Samuel Pawel}
    \end{center}
    \end{column}
  \end{columns}

\end{frame}



% ============================================================================
\nocite{Pyc2010, open2015, Camerer2016, Camerer2018, Cova2018, Pawel2020, 
Held2020, HeldMichPaw2021, MicheloudHeld2021, Protzko2020, Errington2021}
\begin{frame}[allowframebreaks]{References}
  \tiny
  \bibliographystyle{apalike}
  \bibliography{antritt}
\end{frame}
  



\end{document}
