\documentclass[english]{beamer}


% Leos shortcuts
\input{newCommands.tex}
\def\SE{\mbox{se}}
\def\PE{\mbox{PE}}
\def\OR{\mbox{OR}}
\def\HR{\mbox{HR}}
\def\RR{\mbox{RR}}
\def\EF{\mbox{EF}}
\def\RV{\mbox{RV}}
\def\RD{\mbox{RD}}
\def\ARR{\mbox{ARR}}
\def\RRR{\mbox{RRR}}
\def\NNT{\mbox{NNT}}
% nicer tables
\usepackage{booktabs}

% define same colors as in plots
\definecolor{purple3}{RGB}{125,38,205}
\definecolor{springgreen4}{RGB}{0, 139, 69}
\definecolor{Rred}{RGB}{255,0,0}
\definecolor{tan3}{RGB}{205,133,63}
\definecolor{foo}{rgb}{0.2,0.2,0.7}

\usepackage{colortbl}
\definecolor{Gray}{gray}{0.85}
\newcolumntype{a}{>{\columncolor{Gray}}c}
% citing
\usepackage[round]{natbib}

% biostat beamer theme
\usepackage{beamerthemebiostat}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{wasysym}
\definecolor{darkred}{rgb}{0.8,0,0}
\usepackage{color}
\definecolor{magenta}{cmyk}{0,1,0,0}
\newcommand{\dmin}{d_{\tiny \mbox{min}}}
\setbeamertemplate{footline}[page number]


% hyperref options
\usepackage{hyperref}  
\hypersetup{
  bookmarksopen=true, 
  breaklinks=true,
  pdftitle={Design and Analysis of Replication Studies}, 
  pdfauthor={Leonhard Held, Charlotte Micheloud, Samuel Pawel},
  colorlinks=false
}

% Installation of non-free fonts in ubuntu 18.04:
% cd Downloads/
% wget -q https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts
% sudo texlua ./install-getnonfreefonts
% sudo getnonfreefonts --sys -a
\def\uzhunit{}
\def\uzhunitext{}
\title{\centering Design and Analysis of Replication Studies}
\author{\centering \bf  Leonhard Held, Charlotte Micheloud}
\institute{University of Zurich}

  
\date{Feb 6-9, 2022}


% ----------------------------------------------------------------------------
<< include = FALSE, purl = FALSE >>=
library(knitr)
opts_chunk$set(fig.path = "figures/fig", 
               cache = TRUE, 
               fig.align = "center",
               fig.height = 8,
               fig.width = 10,
               dpi = 1000,
               echo = TRUE,
               size = "scriptsize",
               warning = FALSE,
               message = FALSE)
@
% ----------------------------------------------------------------------------

\begin{document}

\begin{frame}
\vspace{1cm}
\maketitle
\vspace{-0.5cm}
\begin{columns}
  \begin{column}{0.5\textwidth}
  \begin{center}
\includegraphics[width=0.6\textwidth]{images_presentation/CRS.png}
  \end{center}
  \end{column}
    \begin{column}{0.5\textwidth}
  \includegraphics[width=0.8\textwidth]{images_presentation/logo.png}
    \end{column}
  \end{columns}
    \begin{center}
    {\color{darkred} Winter School 2022, Les Diablerets}
    \end{center}
\end{frame}

\begin{frame}
\section{Introduction}
  \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Introduction}} 
   \end{center}
  \end{block}
\end{frame}

\begin{frame}{Replication studies}
\begin{block}{Direct replication}
  \begin{itemize}
    \item Repeating original study using the same methodology
    \item[$\rightarrow$] Tool to assess credibility of scientific discoveries
    \item[$\rightarrow$] Regulatory requirement
  \end{itemize}
\end{block}
\pause
\begin{block}{Replication crisis}
  \begin{itemize}
    \item Low replicability of many scientific discoveries
    \item[$\rightarrow$] Large-scale replication projects
  \end{itemize}
\end{block}
\end{frame}

\begin{frame}{Large-scale replication projects}
\begin{block}{}
  \begin{itemize}
    \item<1->                {2015: Reproducibility project psychology}
    \item<2->                {2016: Experimental economics replication project}
    \item<3->                {2018: Experimental philosophy replicability project}
    \item<4->               {2018: Social sciences replication project}
    \item<5->                {2021: Reproducibility Project: Cancer Biology}
  \end{itemize}
\end{block}
\begin{minipage}[t][5cm][t]{\textwidth}
  \centering
  \only<1>{
  \includegraphics[width=0.8\textwidth]{images_presentation/osc2015.png}
  }
  \only<2>{
  \includegraphics[width=0.9\textwidth]{images_presentation/camerer2016.png}
  }
  \only<3>{
  \includegraphics[width=0.6\textwidth]{images_presentation/cova2018.png}
  }
  \only<4>{
  \includegraphics[width=0.7\textwidth]{images_presentation/camerer2018.png}
  }
  \only<5>{
  \includegraphics[width=0.8\textwidth]{images_presentation/errington2021.png}
  }
%%  \only<6>{
%%  \includegraphics[width=0.7\textwidth]{images_presentation/camerer2018.png}
%%  }
\end{minipage}
\end{frame}


\begin{frame}
\frametitle{The four horsemen of irreproducibility}
%% \framesubtitle{Dorothy Bishop, Oxford Reproducibility Lecture  (2017)}
\framesubtitle{Dorothy Bishop (2019) in Nature}
%\vspace{-.5cm}
\begin{multicols}{2}
\begin{center}
\begin{minipage}{7cm}
\begin{center}
\vspace{-1cm}
%%\includegraphics[width=2.5cm]{figures/Bishop.jpg} \\[.5cm]
    \includegraphics[width=7cm]{horsemen.jpg}\\
%\hspace{-2cm}
%%    \includegraphics[width=5cm]{figures/King1995Top2.pdf}
\end{center}
{\scriptsize $\qquad \quad$ Questionable research practices (QRPs)}
\end{minipage}
\end{center}
   \hspace{2cm}
  \begin{minipage}{3cm}
\vspace{.5cm}
\includegraphics[width=3cm]{Bishop.jpg}
\end{minipage}
\end{multicols}
  
\end{frame}
\begin{frame}{Large-scale replication projects}
\begin{block}{}
  \begin{itemize}
    \item<1-> \color<1>{gray}{2015: Reproducibility project psychology}
    \item<1-> \color<1>{gray}{2016: Experimental economics replication project}
    \item<1-> \color<1>{gray}{2018: Experimental philosophy replicability project}
    \item<1-> \color<1>{red}{2018: Social sciences replication project}
    \item<1-> \color<1>{gray}{2021: Reproducibility Project: Cancer Biology}
  \end{itemize}
\end{block}
\begin{minipage}[t][5cm][t]{\textwidth}
  \centering
  \only<1>{
  \includegraphics[width=0.7\textwidth]{images_presentation/camerer2018.png}
  }
\end{minipage}
\end{frame}


\begin{frame}[fragile]{Social sciences replication project} 
<< size = "normalsize" >>=
 library(ReplicationSuccess)
 data("RProjects")
 social <- subset(RProjects, 
                  project == "Social Sciences")
 @
\end{frame}

\begin{frame}[fragile]{Social sciences replication project}
  \framesubtitle{Correlation scale}
<< echo = FALSE >>=
library(ReplicationSuccess)
library(ggplot2)
data("RProjects")
SSRP <- subset(RProjects, project == "Social Sciences")

gg_r <-  ggplot(data = SSRP, aes(x = ro, y = rr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 7, shape = 21, 
             fill = "midnightblue") +
  labs(x = expression(paste("Original effect estimate ", r[o])), 
       y = expression(paste("Replication effect estimate ", r[r]))) +
  lims(x = c(-0.15, 1), y = c(-0.15, 1)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)); gg_r
@
\end{frame}




\begin{frame}[fragile]{Statistical framework of package}
\begin{block}{}
\begin{itemize}
\item Effect estimates are assumed to be {\color{red} normally distributed} after suitable transformation \\
$\rightarrow$ {\color{red} Fisher's $z$-transformation} for correlation 
coefficients $r$ with (effective) sample size $n - 3$
\end{itemize}
\end{block}
<< fig.height = 4.5, echo = FALSE>>=
r <- seq(-1, 1, 0.001)
ztrans_df <- data.frame(r, z = atanh(r))
ggplot(data = ztrans_df, aes(x = r, y = z)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, size = 1,
              alpha = 0.6) +
  geom_line(size = 1) + 
  labs(x = expression(paste("Correlation ", italic(r))), 
       y = expression(paste("Fisher-", italic(z)))) +
  theme_bw() +
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30))
@
\end{frame}

\begin{frame}[fragile]{Social sciences replication project}
  \framesubtitle{Fisher-$z$ scale}
<< echo = FALSE >>=
library(ReplicationSuccess)
library(ggplot2)
data("RProjects")
SSRP <- subset(RProjects, project == "Social Sciences")

gg_z <- ggplot(data = SSRP, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 7, shape = 21, 
             fill = "midnightblue") +
  labs(x = expression(paste("Original effect estimate ", hat(theta)[o])), 
       y = expression(paste("Replication effect estimate ", hat(theta)[r]))) +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)); gg_z
@
\end{frame}


\begin{frame}[fragile]{Correlation vs Fisher-$z$ scale}
<< echo = FALSE >>=
library(ReplicationSuccess)
library(ggplot2)
library(gridExtra)

gg_r2 <- ggplot(data = SSRP, aes(x = ro, y = rr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 5, shape = 21, 
             fill = "midnightblue") +
  labs(x = "Original effect estimate", 
       y = "Replication effect estimate") +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 15), 
        axis.title = element_text(size = 15)) + 
  ggtitle("Correlation scale ") + 
  theme(plot.title = element_text(color = "red", size = 25))

gg_z2 <- ggplot(data = SSRP, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.7, size = 5, shape = 21, 
             fill = "midnightblue") +
  labs(x = "Original effect estimate", 
       y = "Replication effect estimate") +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 15), 
        axis.title = element_text(size = 15)) +
  ggtitle("Fisher-z scale") + 
  theme(plot.title = element_text(color = "red", size = 25))

grid.arrange(gg_r2, gg_z2, 
             ncol = 2)
@
\end{frame}

\begin{frame}{Social sciences replication project}
  \framesubtitle{Pyc and Rawson (2010), Science}
<< echo = FALSE >>=
study <- subset(SSRP,
                study == "Pyc and Rawson (2010), Science")

ggplot(data = SSRP, aes(x = fiso, y = fisr)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_abline(intercept = 0, slope = 1, col = "grey") +
  geom_point(alpha = 0.2, size = 7, shape = 21, 
             fill = "midnightblue") +
  geom_point(data = study,
             alpha = 1, size = 7, shape = 21, 
             fill = "red") +
  
   labs(x = expression(paste("Original effect estimate ", hat(theta)[o])), 
       y = expression(paste("Replication effect estimate ", hat(theta)[r]))) +
  lims(x = c(-0.5, 2), y = c(-0.5, 2)) + 
  coord_fixed() +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
@
\end{frame}

\begin{frame}{\citet{Pyc2010}. Science}
\framesubtitle{Original discovery: ``Testing improves memory'' }
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
library(biostatUZH)
options(scipen = 5)
plot_df <- data.frame(Study = c("Original study", 
                                "Replication study"),
                      z = c(study$fiso, study$fisr),
                      r = c(study$ro, study$rr),
                      p = formatPval(x = c(study$po/2,
                                           study$pr/2)),
                      se = c(study$se_fiso, study$se_fisr),
                      n = c(1/study$se_fiso^2 + 3, 
                            1/study$se_fisr^2 + 3)) 
study_plot <- ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
   labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
study_plot
@
\begin{center}
\vspace{-.6cm}
\hspace{.75cm}
{\small
\begin{tabular}{rcl}
$n_o$ $\qquad$ & Sample size & $\qquad$ $n_r$ \\
$\hat \theta_o$ $\qquad$ & Effect estimate & $\qquad$ $\hat \theta_r$ \\
$\sigma_o$ $\qquad$ & Standard error & $\qquad$ $\sigma_r$ \\
 $p_o$ $\qquad$ & one-sided $p$-value &$\qquad$  $p_r$ \\
  &&
  \end{tabular}
}
\end{center}
\end{minipage}
\end{frame}

\begin{frame}{\citet{Pyc2010}. Science}
\framesubtitle{Original discovery: ``Testing improves memory'' }
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
library(biostatUZH)
options(scipen = 5)
plot_df <- data.frame(Study = c("Original study", 
                                "Replication study"),
                      z = c(study$fiso, study$fisr),
                      r = c(study$ro, study$rr),
                      p = formatPval(x = c(study$po/2,
                                           study$pr/2)),
                      se = c(study$se_fiso, study$se_fisr),
                      n = c(1/study$se_fiso^2 + 3, 
                            1/study$se_fisr^2 + 3)) 
study_plot <- ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  annotate("text", x = 1.5, y = study$ro, 
           label = "?", size = 55, 
           color = "red") + 
  ylim(-0.05, 1) +
   labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
study_plot
@
\vspace{-0.5cm}
\begin{block}{}
\begin{itemize}
  \item[] {\color{red} Relative effect size} $d = \hat\theta_r/\hat\theta_o = 
  \Sexpr{round(study$fisr/study$fiso, 2)}$
  \item[] {\color{red} Relative sample size} $c = n_r/n_o = 9$
\end{itemize}
\end{block}
\end{minipage}
\end{frame}

\begin{frame}{When is a replication successful?}
\section{When is a replication successful?}
\begin{minipage}[t][3cm][t]{\textwidth}
\vspace{-1.5em}
\begin{block}{Some proposed criteria}
  \begin{enumerate}
    \item Two-trials rule (statistical significance)
    \item Compatibility of effect estimates
    \item Meta-analysis of estimates
    \item Sceptical $p$-value
  \end{enumerate}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
study_plot
@
\end{minipage}
\end{frame}


\begin{frame}{1. Two-trials rule}
\begin{minipage}[t][3cm][t]{\textwidth}
\begin{block}{}
{\large \textit{Are both estimates statistically significant in the same direction?}} 

$\rightarrow$ Which threshold? \\
$\rightarrow$ one-sided {$\color{red} \alpha = 0.025$} 
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 10, color = "red") +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 10, color = "red") +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
   labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
@
\end{minipage}
\end{frame}

\begin{frame}{2. Compatibility of effect estimates}
\begin{minipage}[t][3cm][t]{\textwidth}
\begin{block}{}
% {\large \textit{Is the replication estimate contained in its prediction interval?}} \\
{\large \textit{Is the meta-analytic $Q$-test of the estimates statistically 
significant?}} 

% Replication effect contained in its prediction interval? \\ 
% $\rightarrow$ function \texttt{predictionInterval()} \\
% $\rightarrow$ $Q$-test statistically significant at two-sided $\alpha = 0.05$? \\ 
$\rightarrow$ Which threshold? \\
$\rightarrow$ two-sided {\color{springgreen4}$\alpha = 0.05$}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
pi_df <- predictionInterval(thetao = study$fiso,
                            seo = study$se_fiso,
                            ser = study$se_fisr)
pi_df <- tanh(pi_df)
q_pval <- Qtest(thetao = study$fiso, thetar = study$fisr, 
                seo = study$se_fiso, ser = study$se_fisr)

ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  annotate(geom = "text", x = 1.47, y = 0.8,
           label = paste("italic(p)[Q] ==~", formatPval(q_pval)),
           color = "springgreen4", size = 10, parse = TRUE) +
   geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
  labs(x = " ", y = "Effect Size") + 
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
@
\end{minipage}
\end{frame}

\begin{frame}{3. Meta-analysis of effect estimates}
\begin{minipage}[t][3cm][t]{\textwidth}
\begin{block}{}
{\large \textit{Is a meta-analytic estimate statistically significant?}} 

$\rightarrow$ Which threshold? \\
$\rightarrow$ {\color{tan3} one-sided $\alpha = 0.025$ or $0.0025$} used in 
practice\\
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
var_ma_estimate <- with(study, 1/(1/se_fiso^2 + 1/se_fisr^2))
ma_estimate <- with(study, fiso/se_fiso^2 + fisr/se_fisr^2)*
               var_ma_estimate
p_ma <- pnorm(abs(ma_estimate/sqrt(var_ma_estimate)),
              lower.tail = FALSE)*2
ma_data <- data.frame(se = sqrt(var_ma_estimate),
                      ma_estimate = ma_estimate,
                      ma_estimate_r = tanh(ma_estimate),
                      p_ma = formatPval(p_ma),
                      stringsAsFactors = FALSE)

ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_pointrange(data = ma_data,
                  aes(x = 1.5, y = ma_estimate_r, 
                      ymin = ma_estimate - qnorm(0.975)*se,
                      ymax = ma_estimate + qnorm(0.975)*se),
                  size = 1.5, color = "tan3") +
  geom_text(data = ma_data, color = "tan3",
            aes(x = 1.4, y = ma_estimate_r, 
                label = paste("italic(p)[M] ==~", p_ma)),
            nudge_y = 0.31, nudge_x = 0.12, 
            size = 10, parse = TRUE) +
    geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  ylim(-0.05, 1) +
  labs(x = " ", y = "Effect Size") + 
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 30))
@
\end{minipage}
\end{frame}

\begin{frame}{4. Sceptical $p$-value}
\framesubtitle{New definition of replication success}
\vspace{1cm}
\begin{columns}
\begin{column}{0.5\textwidth}
  % \centering
\includegraphics[width=1.1\textwidth]{images_presentation/Held2020.png}

\vspace{6em}
\begin{center}
{\scriptsize \url{https://doi.org/10.1111/rssa.12493}}\\
  \color{white}{\scriptsize published in JRSSA}
\end{center}
\end{column}

\begin{column}{0.5\textwidth}
\includegraphics[width=0.95\textwidth]{images_presentation/Heldetal2021.png}

\vspace{0.8em}
\begin{center}
{\scriptsize \url{https://arxiv.org/abs/2009.07782}}\\
  \color{darkred}{\scriptsize AOAS, to appear}
  \end{center}
\end{column}
\end{columns}
\end{frame}


\begin{frame}{4. Sceptical $p$-value}
\framesubtitle{New definition of replication success}
\begin{minipage}[t][2.7cm][t]{\textwidth}
\vspace{-2.5em}
\begin{block}{}
{\large \textit{Can we convince a sceptic whose priof beliefs make
the original study not significant?}}
\vspace{0.5em}
% 
% $\rightarrow$ \texttt{pSceptical()} returns one-sided sceptical $p$-value $p_S$ \\
% % per default 
% $\rightarrow$ recalibration by default

\vspace{.15cm}
\begin{center}
{\color{purple3} If $p_S \leq \alpha$ we have replication success at level $\alpha$} 
\end{center}
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
ssv <- function(zo, so, a) {
  tau2 <- so^2/(zo^2/qnorm(p = a/2, lower.tail = FALSE)^2 - 1)
  return(tau2)
}
S <- function(U, L) (U - L)^2/(4*sqrt(U*L))

ps_uncalibrated <- pSceptical(zo = study$fiso/study$se_fiso, 
                              zr = study$fisr/study$se_fisr, 
                              c = study$se_fiso^2/study$se_fisr^2,
                              alternative = "one.sided", 
                              type = "nominal")
ps <- pSceptical(zo = study$fiso/study$se_fiso, 
                 zr = study$fisr/study$se_fisr, 
                 c = study$se_fiso^2/study$se_fisr^2,
                 alternative = "one.sided",
                 type = "golden")

s <- S(U = study$fiso + qnorm(0.975)*study$se_fiso,
       L = study$fiso - qnorm(0.975)*study$se_fiso)
tau2 <- ssv(zo = study$fiso/study$se_fiso, 
            so = study$se_fiso, a = ps_uncalibrated*2)
sprior_df <- data.frame(x = 1.5, mu = 0,
                        upper = qnorm(p = 0.975)*sqrt(tau2),
                        lower = qnorm(p = 0.025)*sqrt(tau2))
scept_plot <- ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_pointrange(data = sprior_df, 
                  aes(x = 1.5, y = 0, 
                      ymin = lower, ymax = upper),
                  color = "purple3", size = 1.5) +
  geom_text(data = sprior_df, 
            aes(x = 1.5, y = upper,
                label = "sceptical prior"),
            nudge_y = 0.15, nudge_x = 0,
            color = "purple3", size = 9) +
  geom_text(data = data.frame(x = 1.5, y = 0.9, 
                              ps = formatPval(ps)),
            aes(x = x, y = y, 
                label = paste("italic(p)[S] ==~", ps, sep = "")),
            parse = TRUE, size = 10, color = "purple3") +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8) +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8) +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  labs(x = " ", y = "Effect Size") + 
  ylim(-0.35, 1) +
  theme_bw() + 
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30)) 
scept_plot
@
\end{minipage}
\end{frame}


\begin{frame}{Assessement of replication success}
\begin{minipage}[t][3cm][t]{\textwidth}
\vspace{-1.5em}
\begin{block}{}
  \begin{itemize}
    \item {\color{Rred} Two-trials rule} doesn't take into account effect size
    \item {\color{springgreen4}$Q$-test} doesn't take into account significance
    \item {\color{tan3}Meta-analysis} assumes exchangeability
    \item {\color{purple3}Sceptical $p$-value} takes into account effect size
    and significance
%%    \item Estimates can be compatible but provide no information about true effect
  \end{itemize} 
\end{block}
\end{minipage}
\begin{minipage}[t][6cm][t]{\textwidth}
<< fig.height = 4.5, echo = FALSE >>=
ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.5) +
  geom_text(data = data.frame(x = 1.5, y = 0.9, 
                              ps = formatPval(ps)),
            aes(x = x, y = y, 
                label = paste("italic(p)[S] ==~", ps, sep = "")),
            parse = TRUE, size = 10, color = "purple3") +
  geom_text(data = ma_data, color = "tan3",
          aes(x = 1.4, y = ma_estimate_r, 
              label = paste("italic(p)[M] ==~", p_ma)),
          nudge_y = -0.31, nudge_x = 0.12, 
          size = 10, parse = TRUE) +
    annotate(geom = "text", x = 1.47, y = 0.7, 
             label = paste("italic(p)[Q] ==~", formatPval(q_pval)),
             color = "springgreen4", size = 10, parse = TRUE) +
  geom_text(aes(label = paste("italic(p)[o] ==~", 
                              p[1], sep = "")), parse = TRUE, 
            x = 1, y = 0.8, size = 8, color = "red") +
    geom_text(aes(label = paste("italic(p)[r] ==~", 
                              p[2], sep = "")), parse = TRUE, 
            x = 2, y = 0.8, size = 8, color = "red") +
  geom_text(aes(label = paste("hat(theta)[o] ==~", 
                              round(z[1], 2), 
                              sep = "")), parse = TRUE, 
            x = 0.7, y = 0.38, size = 8) +
   geom_text(aes(label = paste("hat(theta)[r] ==~", 
                              round(z[2], 2), 
                              sep = "")), parse = TRUE, 
           x = 2.3,y = 0.25, size = 8) +
  geom_text(aes(label = paste("italic(n)[o] ==~", n[1], sep = "")),
            parse = TRUE, 
            x = 0.7, y = 0.25, size = 8) +
   geom_text(aes(label = paste("italic(n)[r] ==~", n[2], sep = "")),
            parse = TRUE, 
             x = 2.3, y = 0.1, size = 8) +
  geom_pointrange(data = ma_data,
                  aes(x = 1.5, y = ma_estimate_r, 
                      ymin = ma_estimate - qnorm(0.975)*se,
                      ymax = ma_estimate + qnorm(0.975)*se),
                  size = 1.5, color = "tan3") + 
   labs(x = " ", y = "Effect Size") +  
  ylim(-0.05, 1) +
  theme_bw() +
  theme(axis.text = element_text(size = 25), 
        axis.title = element_text(size = 30))
@
\end{minipage}
\end{frame}

\begin{frame}[fragile]{The Relative Effect Size}
  \framesubtitle{in the assessment of replication success}
    
    \begin{block}{}
      \begin{itemize}
        \item Relative effect size {\color{red} $d = \hat\theta_r/\hat\theta_o$}
        can be used in the assessment of replication success
                \item[] $\rightarrow$ success if {\color{red} $d >\dmin$, the
                minimum relative effect size}
                \pause
        \item {\color{red} $\dmin$} depends on 
          \begin{itemize}
            \item {\color{foo} relative sample size} $c$ 
            \item {\color{foo} original $p$-value} $p_o$  
            \item {\color{foo} one-sided level} $\alpha$
          \end{itemize}
          \item Equivalent to assessment based on (sceptical) $p$-value
      \end{itemize}
    \end{block}
\end{frame}

\begin{frame}[fragile]{The Relative Effect Size}
\framesubtitle{in the assessment of replication success}
  
  \begin{block}{Pyc and Rawson example}
<<echo = FALSE>>=

dmin2TR <-  effectSizeSignificance(zo = study$fiso/study$se_fiso, 
                                   c = study$se_fiso^2/study$se_fisr^2, 
                                   level = 0.025, 
                                   alternative = "one.sided")

dminRS <- effectSizeReplicationSuccess(zo = study$fiso/study$se_fiso, 
                                   c = study$se_fiso^2/study$se_fisr^2, 
                                   level = 0.025, 
                                   type = "golden", 
                                   alternative = "one.sided")
@
 

  
    \begin{itemize}
      \item {\color{foo} $d = \Sexpr{round(study$fisr, 2)}/\Sexpr{round(study$fiso, 2)} = 
      \Sexpr{round(study$fisr/study$fiso, 2)}$ }
      \item Minimum relative effect size
        \begin{itemize}
\visible<2->{  
          \item With the two-trials rule: \\
            \begin{center} 
            {\color{springgreen4} $\dmin = \Sexpr{round(dmin2TR, 2)} < \Sexpr{round(study$fisr/study$fiso, 2)}\quad$ 
              Replication Success} \end{center}}
\visible<3->{  
          \item With the 
          sceptical $p$-value: \begin{center} 
            {\color{red} $\dmin = \Sexpr{round(dminRS, 2)} > \Sexpr{round(study$fisr/study$fiso, 2)}\quad$  No Replication Success} 
            \end{center}}
        \end{itemize}
    \end{itemize}
      \pause
  \end{block}
  
\visible<4->{  
      \begin{center}
    {\color{darkred} Why do the two methods disagree?}
    \end{center}
    }
    
\end{frame}

% \begin{frame}[fragile]{The Relative Effect Size}
% \framesubtitle{in the assessment of replication success}
% 
% \vspace{0.75cm}
% \begin{multicols}{2}
% 
% \begin{minipage}{0.4\textwidth}
% \visible<1->{
%   \alert{Goal}: Comparison of 
% \begin{itemize}
%    \item {\bf two-trials rule} 
%    \item {\bf meta-analysis} 
%    \item {\bf sceptical $p$-value}
%    \end{itemize}
%    }
% \end{minipage}
% \begin{minipage}{0.5\textwidth}
% \visible<2->{
% \alert{Key}: Formulation in terms of
% \begin{enumerate}
%    \item {\bf Original $p$-value} $p_o$ 
%    \item {\bf Relative effect size} $d=\hat \theta_r / \hat \theta_o$
%    \item {\bf Relative sample size} $c = n_r / n_o$ 
%    \end{enumerate}
% }
%  \end{minipage}
% \end{multicols}
% \vspace{.25cm}
% \begin{multicols}{2}
% 
% \begin{minipage}{0.6\textwidth}
% \visible<3->{
%   \alert{Criterion}: Success if $d > \dmin$
% }
% \end{minipage}
% % \begin{minipage}{0.5\textwidth}
% % \visible<4->{
% %    \begin{center}
% %   \includegraphics[width=5cm]{images_presentation/Held-etal2021.png} \\
% %   \color{darkred}{\scriptsize AOAS, to appear \\ \url{https://arxiv.org/abs/2009.07782}}
% % \end{center}
% % }
% %  \end{minipage}
% \end{multicols}
% 
% \end{frame}


<<echo=FALSE>>=
mygrey <- "gray30"
## source("Rcode/plotAncred.R")
source("Rcode/plotLevel.R")
source("Rcode/plotLevel2.R")
@

<<echo = F>>=
mycval <- 0.5 
@
\begin{frame}[fragile]{Comparison of Success Regions}
\framesubtitle{Relative sample size $c=\Sexpr{mycval}$}

\vspace{1cm}
\begin{center}
Success if {\color{darkred} $d > \dmin$}
\end{center}
\vspace{-1cm}

\makebox[1\textwidth][c]{  
  \resizebox{1.3\textwidth}{!} {
<<plot1, fig.height = 6, fig.weight=12, cache=TRUE, out.width="1\\linewidth", echo = FALSE>>=
 
par(mfrow = c(1,3))

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "signif") # Significance
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "meta") # Meta-Analysis
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval, # choosing one value of c
          level = 0.025,
          type = "golden",
          alternative = "one.sided",
          minRES = T, # not showing minres
          method = "RS") # Replication Success
points(0.011, 0.38, col=4, pch=19)

@
  }
}
\end{frame}


<<echo = F>>=
mycval <- 1
@
\begin{frame}[fragile]{Comparison of Success Regions}
\framesubtitle{Relative sample size $c=\Sexpr{mycval}$}

\vspace{1cm}
\begin{center}
Success if {\color{darkred} $d > \dmin$}
\end{center}
\vspace{-1cm}
\makebox[1\textwidth][c]{  
  \resizebox{1.3\textwidth}{!} {
<<plot1b, fig.height = 6, fig.weight=12, cache=TRUE, out.width="1\\linewidth", echo = FALSE>>=

par(mfrow = c(1,3))

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "signif") # Significance
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "meta") # Meta-Analysis
points(0.011, 0.38, col=4, pch=19)
plotLevel(c = mycval, # choosing one value of c
          level = 0.025,
          type = "golden",
          alternative = "one.sided",
          minRES = T, # not showing minres
          method = "RS") # Replication Success
points(0.011, 0.38, col=4, pch=19)

@
  }
}
\end{frame}


<<echo = F>>=
mycval <- 2
@
\begin{frame}[fragile]{Comparison of Success Regions}
\framesubtitle{Relative sample size $c=\Sexpr{mycval}$}

\vspace{1cm}
\begin{center}
Success if {\color{darkred} $d > \dmin$}
\end{center}
\vspace{-1cm}

\makebox[1\textwidth][c]{  
  \resizebox{1.3\textwidth}{!} {
<<plot1c, fig.height = 6, fig.weight=12, cache=TRUE, out.width="1\\linewidth", echo = F>>=

par(mfrow = c(1,3))

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "signif") # Significance
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "meta") # Meta-Analysis
points(0.011, 0.38, col=4, pch=19)
plotLevel(c = mycval, # choosing one value of c
          level = 0.025,
          type = "golden",
          alternative = "one.sided",
          minRES = T, # not showing minres
          method = "RS") # Replication Success
points(0.011, 0.38, col=4, pch=19)

@
  } 
}
\end{frame}

<<echo = F>>=
mycval <- 5
@
\begin{frame}[fragile]{Comparison of Success Regions}
\framesubtitle{{Relative sample size} $c=\Sexpr{mycval}$}

\vspace{1cm}
\begin{center}
Success if {\color{darkred} $d > \dmin$}
\end{center}
\vspace{-1cm}
\makebox[1\textwidth][c]{  
  \resizebox{1.3\textwidth}{!} {
<<plot1d, fig.height = 6, fig.weight=12, cache=FALSE, out.width="1\\linewidth", echo = F>>=

par(mfrow = c(1,3))

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "signif") # Significance
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "meta") # Meta-Analysis
points(0.011, 0.38, col=4, pch=19)
plotLevel(c = mycval, # choosing one value of c
          level = 0.025,
          type = "golden",
          alternative = "one.sided",
          minRES = T, # not showing minres
          method = "RS") # Replication Success
points(0.011, 0.38, col=4, pch=19)

@
  }
}
\end{frame}

<<echo = F>>=
mycval <- 9
@
\begin{frame}[fragile]{Comparison of Success Regions}
\framesubtitle{Relative sample size $c=\Sexpr{mycval}$}

\vspace{1cm}
\begin{center}
Success if {\color{darkred} $d > \dmin$}
\end{center}
\vspace{-1cm}

\makebox[1\textwidth][c]{  
  \resizebox{1.3\textwidth}{!} {
<<plot1e, fig.height = 6, fig.weight=12, cache=TRUE, out.width="1\\linewidth", echo = F>>=

par(mfrow = c(1,3))

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "signif") # Significance
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "meta") # Meta-Analysis
points(0.011, 0.38, col=4, pch=19)
plotLevel(c = mycval, # choosing one value of c
          level = 0.025,
          type = "golden",
          alternative = "one.sided",
          minRES = T, # not showing minres
          method = "RS") # Replication Success
points(0.011, 0.38, col=4, pch=19)

@
  } 
} 
\end{frame}
<<echo = F>>=
mycval <- 1000
@
\begin{frame}[fragile]{Comparison of Success Regions}
\framesubtitle{Relative sample size $c=\Sexpr{mycval}$}

\vspace{1cm}
\begin{center}
Success if {\color{darkred} $d > \dmin$}
\end{center}
\vspace{-1cm}

\makebox[1\textwidth][c]{  
  \resizebox{1.3\textwidth}{!} {
<<plot1f, fig.height = 6, fig.weight=12, cache=TRUE, out.width="1\\linewidth", echo = F>>=

par(mfrow = c(1,3))

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "signif") # Significance
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval,
          level = 0.025,
          type = "nominal",
          alternative = "one.sided",
          minRES = F,
          method = "meta") # Meta-Analysis
points(0.011, 0.38, col=4, pch=19)

plotLevel(c = mycval, # choosing one value of c
          level = 0.025,
          type = "golden",
          alternative = "one.sided",
          minRES = T, # not showing minres
          method = "RS") # Replication Success
points(0.011, 0.38, col=4, pch=19)

@
  } 
}
\end{frame}


\begin{frame}{Shrinkage}
  \framesubtitle{Definition and example}
  \begin{block}{Shrinkage}
    \begin{itemize}
      \item is defined as {\color{foo} $s = 1 - d$}
      \item represents how much the {\color{red} replication effect estimate}
      is decreased as compared to the {\color{red} original effect estimate}
      \item Pyc and Rawson example: {\color{foo} $s = 1 - 
      \Sexpr{round(study$fisr/study$fiso, 2)} = 
      \Sexpr{round(1 -study$fisr/study$fiso, 2) }$}
      \item[] $\rightarrow$ replication effect is 
      {\color{red} $\Sexpr{round(1 -study$fisr/study$fiso, 2)*100}$\% smaller} 
      than original one
    \end{itemize}
      \pause 
  \end{block}
    \begin{center}
    {\color{darkred} Shrinkage is penalized in the sceptical $p$-value 
  approach}
    \end{center}
\end{frame}

\begin{frame}{Shrinkage penalization}
  \framesubtitle{in the sceptical $p$-value approach}
    \vspace{1cm}
  \begin{center}
    Bordeline significant original studies 
    {\color{red} ($p_o = \alpha$)}
    can only lead to success if there is no shrinkage {\color{foo} ($d > 1$)}
  \end{center}

    \vspace{-1.5cm}
\makebox[1\textwidth][c]{  
  \resizebox{0.5\textwidth}{!} { 
<<echo = F, fig.width = 5>>=

par(mfrow = c(1,1))
plotLevel(c = Inf, 
          level = 0.025,  
          type = "golden", 
          alternative = "one.sided", 
          minRES = T, 
          method = "RS")
segments(x0 = 0.025, y0 = 1, x1 = 0, y1 = 1, 
         col = "red", cex = 1.5, 
         lty = 2)

segments(x0 = 0.025, y0 = 0, x1 = 0.025, y1 = 1, 
         col = "red", cex = 1.5, 
         lty = 2)

points(x = 0.025, y = 1, 
       col = "red", 
       pch = 19)
axis(1, 0.025, 0.025, col.axis = "red", col.ticks = "red", 
     cex.axis = 0.5)

@
  } 
}

\end{frame}


\begin{frame}
\section{Exercise 1 -- Analysis of replication studies}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Exercise Session 1}} 
  \\~\\
  {\LARGE Analysis of replication studies}
   \end{center}
  % \end{block}
\end{frame}


\begin{frame}[fragile]{Package ReplicationSuccess}
% \begin{itemize}
  % \item Statistical methods and functionality for the design and analysis of replication studies \\
  %% $\rightarrow$ Traditional methods \\
  %% $\rightarrow$ Sceptical $p$-value \citep{Held2020}
  % \end{itemize}
%%   \centering
%% \includegraphics[width=0.75\textwidth]{images_presentation/Held2019.png}
  
%% \end{frame}
\vspace{-0.8cm}
%% \begin{frame}[fragile]{Installation}
  \begin{block}{}
    \begin{itemize}
      %% \item Statistical methods and functionality for the design and analysis of replication studies (work in progress!)
      \item Installation
<< eval = FALSE, size = "small" >>=
install.packages("ReplicationSuccess")
@
      \item Usage
    << size = "small", eval = FALSE >>=
library(ReplicationSuccess)
vignette("ReplicationSuccess")
?pSceptical # documentation
news(package = "ReplicationSuccess") # news page
@
  \end{itemize}
  \end{block}
\end{frame}

\begin{frame}[fragile]{Statistical framework}
\begin{block}{}
\begin{itemize}
\item Effect estimates are assumed to be {\color{red} normally distributed} 
after suitable transformation \\
$\rightarrow$ {\color{red} Fisher's $z$-transformation} for correlation 
coefficients $r$ with (effective) sample size $n - 3$
\end{itemize}
\end{block}
<< echo = FALSE, fig.height = 4.5 >>=
# Second axis for Fisher z-scale
lims_r <- tanh(seq(0, 1, 0.5))
labs_r <- round(lims_r, 2)

ggplot(data = plot_df, aes(x = Study, y = z)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = z - qnorm(0.975)*se, 
                      ymax = z + qnorm(0.975)*se),
                  size = 1.25) +
  geom_text(aes(label = paste("italic(r) ==~", 
                              round(r, 2), 
                              sep = "")), parse = TRUE, 
            nudge_x = c(-0.31, 0.27), nudge_y = 0.1, size = 6) +
  geom_text(aes(label = paste("'fis' ==~", 
                              round(z, 2), 
                              sep = "")), parse = TRUE, 
            nudge_x = c(-0.31, 0.27), nudge_y = -0.1, size = 6) +
  scale_y_continuous(limits = c(-0.05, 1.2), 
                     breaks = seq(0, 2.5, 0.5),
                     sec.axis = sec_axis(trans = ~tanh(.), 
                                         breaks = lims_r,
                                         labels = labs_r,
                                         name = expression(paste("Correlation ", italic(r))))) + 
  labs(x = " ", y = expression(paste("Fisher-",italic(z)))) + 
  theme_bw() + 
  theme(axis.text = element_text(size = 20), 
        axis.title = element_text(size = 25)) 
@
\end{frame}

\begin{frame}[fragile]{Data sets}
<<eval=FALSE, size = "small" >>=
?RProjects # Documentation
@
\begin{block}{Most important variables}
\begin{table}
\centering
\begin{tabular}{l l}
  \texttt{project} & Replication project \\
  \texttt{ro} & Original effect on correlation scale \\
  \texttt{rr} & Replication effect on correlation scale \\
  \texttt{fiso} & Original effect on Fisher-$z$ scale \\
  \texttt{fisr} & Replication effect on Fisher-$z$ scale \\
  \texttt{se\_fiso} & Standard error of \texttt{fiso} \\
  \texttt{se\_fisr} & Standard error of \texttt{fisr} 
\end{tabular}
\end{table}
\end{block}
\end{frame}

\begin{frame}[fragile]{Statistical framework of package}
<< echo = FALSE >>=
po <- study$po
pr <- study$pr
to <- study$fiso/study$se_fiso
tr <- study$fisr/study$se_fisr
c <- study$se_fiso^2/study$se_fisr^2
@

\begin{block}{Key quantities}
\begin{itemize}
\item $z$-value $z_o$ or (one-sided) $p$-value $p_o$ of original study
<< size = "small" >>=
RProjects$zo <- RProjects$fiso/RProjects$se_fiso
RProjects$po1 <- z2p(RProjects$zo, 
                     alternative = "one.sided")
@
\pause
\item $z$-value $z_r$ or (one-sided) $p$-value $p_r$ of replication study
<< size = "small" >>=
RProjects$zr <- RProjects$fisr/RProjects$se_fisr
RProjects$pr1 <- z2p(RProjects$zr, 
                     alternative = "one.sided")
@
\pause
\item relative sample size (or variance ratio) $c = \sigma_o^2/\sigma_r^2 =  n_r/n_o$
<< size = "small" >>=
RProjects$c <- RProjects$se_fiso^2/RProjects$se_fisr^2
@
\end{itemize}
\end{block}
\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
Load the package and the data sets with
\vspace{-0.5em}
<< size = "small", eval = FALSE >>=
library(ReplicationSuccess)
data("RProjects") 
@
Compute the key quantities $z_o$, $z_r$, $c$, and the one-sided $p$-values $p_o$ and $p_r$ with
<< size = "small" >>=
RProjects$zo <- RProjects$fiso/RProjects$se_fiso
RProjects$zr <- RProjects$fisr/RProjects$se_fisr
RProjects$c <- RProjects$se_fiso^2/RProjects$se_fisr^2
RProjects$po1 <- z2p(RProjects$zo, 
                     alternative = "one.sided")
RProjects$pr1 <- z2p(RProjects$zr, 
                     alternative = "one.sided")
@
\end{block}
\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{}
For all studies from the replication projects investigate
\end{block}
  \begin{block}{Exercise 1.1}
     How many study pairs fulfill the \textbf{two-trials rule} criterion for 
     replication success? Use a threshold of $\alpha = 0.025$ for the one-sided 
     $p$-values.
  \end{block}
  \begin{block}{Exercise 1.2}
    For how many study pairs do you find evidence for \textbf{incompatible} effect 
    estimates (on Fisher $z$-scale)? Use the function
    \texttt{Qtest()} and a threshold of $\alpha = 0.05$ for the resulting $p$-value.
  \end{block}
\end{frame}


\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}

For all studies from the replication projects investigate
  \begin{block}{Exercise 1.3}
    Compute the one-sided \textbf{sceptical $p$-value}. How many replication 
    studies are successful at $0.025$? 
      Use the function \texttt{pSceptical()}
  \end{block}
  \begin{block}{Exercise 1.4}
    Look closer at the studies which show \textbf{discrepancies} in terms of replication 
    success based on the two-trials rule and the sceptical $p$-value. How do their 
    effect estimates and sample sizes compare?
  \end{block}
\end{frame}

\begin{frame}[fragile]{Exercises}
  \begin{block}{Exercise 1.5 (if time permits)}
Calculate the \textbf{relative effect size $d = \hat\theta_r/\hat\theta_o$} for the 
discrepant studies, {\bf as well as the minimum relative effect size $\dmin$}
with the two approaches (two-trials rule and sceptical $p$-value). 
\\~\\
Use the functions \texttt{effectSizeSignificance} and 
\texttt{effectSizeReplicationSuccess}.
  \end{block}

\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.1}  
<< echo = FALSE, results = "asis" >>=
# for (p in unique(RProjects$project)) {
#   data_project <- subset(RProjects, project == p)
#   significant_O <- data_project$po < 0.05
#   significant_R <- data_project$pr < 0.05
#   success <- significant_O & significant_R & 
#       (sign(data_project$fiso) == sign(data_project$fisr))
#   cat(paste0(p, ": \n"))
#   cat(paste0(round(mean(significant_O)*100, 1), "% original studies significant (", 
#              sum(significant_O), "/", length(significant_O), ")\n"))
#   cat(paste0(round(mean(significant_R)*100, 1), "% replications significant (", 
#              sum(significant_R), "/", length(significant_R), ")\n"))
#   cat(paste0(round(mean(success)*100, 1), 
#              "% both significant, same direction (",
#              sum(success), "/", length(success), ") \n \n"))
# }

## compute for all projects
significant_O <- RProjects$po1 < 0.025
significant_R <- RProjects$pr1 < 0.025
RProjects$TTR <- significant_O & significant_R
allDF <- data.frame(project = "all", success = mean(RProjects$TTR)*100, 
                    type = "significance",
                    successFormat = paste0(round(mean(RProjects$TTR)*100, 0), "\\% (", 
                                           sum(RProjects$TTR), "/", 
                                           length(RProjects$TTR), ")"))

## compute for each project
signSuccessList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  success <- data_project$TTR
  data.frame(project = p, success = mean(success)*100, type = "significance",
             successFormat = paste0(round(mean(success)*100, 0), "\\% (", 
                                    sum(success), "/", length(success), ")"))
})
signSuccessDF <- do.call("rbind", signSuccessList)

## table
library(xtable)
dfTable1 <- rbind(signSuccessDF, allDF)[,c(1, 4)]
Table1 <- xtable(dfTable1, digits = 1)
colnames(Table1) <- c("Project", "Both $p$-values < 0.025")
print(Table1, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x})
@
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.1}
<< echo = FALSE >>=
## Plots of effect estimates
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  data_project <- subset(RProjects, project == p)
  significant_O <- data_project$po1 < 0.025
  significant_R <- data_project$pr1 < 0.025
  success <- significant_O & significant_R
  col_success <- color <- ifelse(success == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(mean(success)*100, 0), 
                  "% (", sum(success), "/", length(success), ")")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_success, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", 
         legend = c(expression(paste("both ", italic(p), "-values < 0.025")), 
                    expression(paste("not both ", italic(p), "-values < 0.025"))),
         # c("both significant", "not both significant"), 
         pch = 20, pt.cex = 2, cex = 1.4,
         # title = "signficant in same direction (5%)",
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.2}
\makebox[1 \textwidth][c]{  
  \resizebox{1\textwidth}{!} {
<< echo = FALSE, results = "asis" >>=
## computing zo, zr, c
RProjects$zo <- with(RProjects, fiso/se_fiso)
RProjects$zr <- with(RProjects, fisr/se_fisr)
RProjects$c <- with(RProjects, se_fiso^2/se_fisr^2)

## compute for all projects
RProjects$pQ <- Qtest(thetao = RProjects$fiso, thetar = RProjects$fisr,
                      seo = RProjects$se_fiso, ser = RProjects$se_fisr)
RProjects$Qincompatible <- RProjects$pQ <= 0.05
allQDF <- data.frame(project = "all", incomp = mean(RProjects$Qincompatible)*100, 
                     type = "Q-test",
                     incompFormat = paste0(round(mean(RProjects$Qincompatible)*100, 0),
                                           "\\% (", sum(RProjects$Qincompatible),
                                           "/", length(RProjects$Qincompatible), ")"))

## compute for each project
QList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  data.frame(project = p, incomp = mean(data_project$Qincompatible)*100, type = "Q-test",
             incompFormat = paste0(round(mean(data_project$Qincompatible)*100, 0), 
                                    "\\% (", sum(data_project$Qincompatible), "/", 
                                    length(data_project$Qincompatible), ")"))
})
QDF <- do.call("rbind", QList)


## table
dfTable2 <- rbind(QDF, allQDF)[,c(1, 4)]
Table2 <- xtable(dfTable2, digits = 1)
colnames(Table2) <- c("Project", 
                      "Incompatible estimates ($p_Q < 0.05$)")
print(Table2, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x}, floating = FALSE)
@
  }
}
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.2}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  pval_Q_project <- Qtest(thetao = data_project$fiso,
                          thetar = data_project$fisr,
                          seo = data_project$se_fiso,
                          ser = data_project$se_fisr)
  incompatible <- pval_Q_project < 0.05
  PropIncomp <- mean(incompatible)
  color <- ifelse(incompatible == FALSE, "#333333B3", "#8B0000B3")
  # PI <- predictionInterval(thetao = data_project$fiso,
  #                          seo = data_project$se_fiso,
  #                          ser = data_project$se_fisr)
  # PI <- tanh(PI) # transforming back to correlation scale
  # within <- (data_project$rr < PI$upper) & (data_project$rr > PI$lower)
  # coverage <- mean(within)
  # color <- ifelse(within == TRUE, "#333333B3", "#8B0000B3")
  # studynr <- seq(1, nrow(data_project))
  # plot(data_project$rr, studynr, col = color, pch = 20,
  #      xlim = c(-0.5, 1), xlab = expression(italic(r)[r]),
  #      main = paste0(p, ": ", round(coverage*100, 0), "% compatible"),
  #      cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5, yaxt = "n",
  #      ylab = "")
  # arrows(PI$lower, studynr, PI$upper, studynr, length = 0.02,
  #        angle = 90, code = 3, col = color)
  # abline(v = 0, lty = 3)
  title <- paste0(p, ": ", round(PropIncomp*100, 0), '% incompatible')
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = color, pch = 20,
       cex.main = 1.7, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", 
         c(expression(italic(p)[Q] < 0.05), expression(italic(p)[Q] >= 0.05)),
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.3}
<< echo = FALSE, fig.height = 4, results = "asis" >>=
## computing one.sided sceptical p-value for replication projects
RProjects$ps <- with(RProjects, pSceptical(zo = zo, zr = zr, c = c, 
                                           alternative = "one.sided",
                                           type = "golden"))

## compute for all projects
RProjects$pSsuccess <- RProjects$ps < 0.025
allpsDF <- data.frame(project = "all", success = mean(RProjects$pSsuccess)*100, 
                      type = "psceptical",
                      successFormat = paste0(round(mean(RProjects$pSsuccess)*100, 0),
                                             "\\% (", sum(RProjects$pSsuccess), 
                                             "/", length(RProjects$pSsuccess), ")"))

## compute for each project
psList <- lapply(X = unique(RProjects$project), FUN = function(p) {
  data_project <- subset(RProjects, project == p)
  data.frame(project = p, success = mean(data_project$pSsuccess)*100, 
             type = "psceptical",
             successFormat = paste0(round(mean(data_project$pSsuccess)*100, 0), 
                                    "\\% (", sum(data_project$pSsuccess), "/",
                                    length(data_project$pSsuccess), ")"))
})
psDF <- do.call("rbind", psList)

## table
dfTable3 <- rbind(psDF, allpsDF)[,c(1, 4)]
Table3 <- xtable(dfTable3, digits = 1)
colnames(Table3) <- c("Project", "sceptical $p$-value $< 0.025$")
print(Table3, include.rownames = FALSE, booktabs = TRUE,
      add.to.row = list(pos = list(4), command = "\\midrule \n"),
      sanitize.text.function = function(x) {x})
@
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.3}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  success <- data_project$ps < 0.025
  col_success <- ifelse(success == FALSE, "#333333B3", "#8B0000B3")
  title <- paste0(p, ": ", round(mean(success)*100, 0), "% (",
                  sum(success), "/",  length(success), ")")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = title, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_success, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", c(expression(italic(p)[s] < 0.025),
                      expression(italic(p)[s] >= 0.025)),
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#333333B3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.4}
<< echo = FALSE >>=
par(mfrow = c(2, 2), las = 1, mai = rep(0.68, 4))
for (p in unique(RProjects$project)) {
  data_project <- subset(RProjects, project == p)
  discrep <- data_project$pSsuccess != data_project$TTR
  col_discord <- ifelse(discrep == TRUE,
                 ifelse(data_project$pSsuccess == TRUE,
                        "#8B0000B3", "#00008AB3"), "#B2B2B299")
  plot(rr ~ ro, data = data_project, ylim = c(-0.5, 1), cex = 2.5,
       xlim = c(-0.5, 1), main = p, xlab = expression(italic(r)[o]),
       ylab = expression(italic(r)[r]), col = col_discord, pch = 20,
       cex.main = 1.8, cex.axis = 1.5, cex.lab = 1.5)
  legend("topleft", legend = c(expression(paste(italic(p)[s], " only")),
                      "significance only"),
         title = "success",
         pch = 20, pt.cex = 2, cex = 1.4,
         col = c("#8B0000B3", "#00008AB3"), bty = "n")
  abline(h = 0, lty = 2)
  abline(a = 0, b = 1, col = "grey")
}
@
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.4}
\makebox[1 \textwidth][c]{  
  \resizebox{1.2\textwidth}{!} {
<< echo = FALSE, fig.height = 4, results = "asis" >>=
phighlighfun <- function(p) {
 ifelse(p > 0.025,
        paste0("\\textcolor{red}{", biostatUZH::formatPval(p), "}"),
        paste0("\\textcolor{black}{",  biostatUZH::formatPval(p), "}"))
}
RProjects$study2 <- RProjects$study
RProjects$study2[RProjects$study == "K Oberauer"] <- "Oberauer (2008)"
RProjects$study2[RProjects$study == "JR Schmidt, D Besner"] <- 
  "Schmidt and Besner (2008)"
RProjects$study2[RProjects$study == "BK Payne, MA Burkley, MB Stokes"] <- 
  "Payne, Burkley, and Stokes (2008)"
RProjects$study2[RProjects$study == "Balafoutas and Sutter (2012), Science"] <- 
  "Balafoutas and Sutter (2012)"
RProjects$study2[RProjects$study == "Pyc and Rawson (2010), Science"] <- 
  "Pyc and Rawson (2010)"
RProjects$study2[RProjects$study == "Nichols (2006)"] <- 
  "Nichols (2006)"

## discrepant studies
discrepantDF <- subset(RProjects, pSsuccess != TTR)[, c("study2", "c", "ro", 
                                                        "rr", "po1", "pr1", "ps", "zo", "se_fiso", "se_fisr", "fiso", "fisr")]
discrepantDF$c <- as.character(round(discrepantDF$c, 1))
discrepantDF$ro <- as.character(round(discrepantDF$ro, 2))
discrepantDF$rr <- as.character(round(discrepantDF$rr, 2))
discrepantDF$po1 <- phighlighfun(discrepantDF$po1)
discrepantDF$pr1 <- phighlighfun(discrepantDF$pr1)
discrepantDF$ps <- phighlighfun(discrepantDF$ps)

discTab <- xtable(discrepantDF[, 1:(ncol(discrepantDF)-5)])
colnames(discTab) <- c("Study", "$n_r / n_o$", "$r_o$", "$r_r$", "$p_o$", 
                       "$p_r$", "$p_s$")
print(discTab, include.rownames = FALSE, booktabs = TRUE,
      sanitize.text.function = function(x) {x}, size = "small",
      floating = FALSE)
@
 }
}
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.5}

\makebox[1 \textwidth][c]{  
  \resizebox{1.2\textwidth}{!} {
<<echo = F, results = 'asis'>>=

phighlighfun2 <- function(dmin, d) {
 ifelse(dmin > d,
        paste0("\\textcolor{red}{", round(dmin, 2), "}"),
        paste0("\\textcolor{black}{",  round(dmin, 2), "}"))
}

discrepantDF$d <- discrepantDF$fisr/discrepantDF$fiso
discrepantDF$dminSign <- effectSizeSignificance(zo = discrepantDF$zo,
                                c = discrepantDF$se_fiso^2/discrepantDF$se_fisr^2, level = 0.025)
discrepantDF$dminRS <- effectSizeReplicationSuccess(zo = discrepantDF$zo,
                                        c = discrepantDF$se_fiso^2/discrepantDF$se_fisr^2, level = 0.025,
                             type = "golden")
discrepantDF$dminSign <- phighlighfun2(dmin = discrepantDF$dminSign, d = discrepantDF$d)
discrepantDF$dminRS <- phighlighfun2(dmin = discrepantDF$dminRS, d = discrepantDF$d)
discrepantDF$d <- paste0("\\textcolor{blue}{", round(discrepantDF$d, 2) , "}")



discTab2 <- xtable(discrepantDF[, -c(3:4, 6:12)])
colnames(discTab2) <- c("Study", "$n_r / n_o$", "$p_o$",
                        "$d$", "$d_{min} (2TR)$", "$d_{min} (RS)$")
print(discTab2, include.rownames = FALSE, booktabs = TRUE,
      sanitize.text.function = function(x) {x}, size = "small",
      floating = FALSE)

@
  } 
}
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 1.5 (extended)}
  \begin{center}
  Minimum relative effect size $\dmin$ with the 
  {\color{foo} two-trials rule} 
  vs the {\color{foo} sceptical $p$-value}
  \end{center}
  
  \makebox[1\textwidth][c]{  
  \resizebox{0.75\textwidth}{!} {
<<echo = F>>=
dmin_sign <- effectSizeSignificance(zo = RProjects$zo,
                                    c = RProjects$c,
                                    level = 0.025)
dmin_rs <- effectSizeReplicationSuccess(zo = RProjects$zo,
                                        c = RProjects$c,
                                        level = 0.025,
                                        type = "golden",
                                        alternative = "one.sided")
dmin_DF <- as.data.frame(cbind(dmin_sign, dmin_rs,
                               RProjects$se_fiso^2/RProjects$se_fisr^2))
colnames(dmin_DF) <-  c("dmin_sign", "dmin_rs", "c")
                               
                               
ggplot(data= dmin_DF, aes(x = dmin_sign, y = dmin_rs)) +
   geom_point(aes(size  = c, sie = 10)) +
  xlim(0, 2) +
  ylim(0, 2) +
  geom_abline(intercept = 0, slope = 1, color = "grey") + 
  xlab(expression(paste(d[min], " (two-trials rule)"))) + 
  ylab(expression(paste(d[min], " (sceptical p-value)"))) + 
    theme_bw()  + 
  theme(axis.text = element_text(size = 20), 
        axis.title = element_text(size = 25))
@

  } 
} 
\end{frame}

\begin{frame}
\section{Exercise 2 -- Design of replication studies}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Design of replication studies}}
   \end{center}
  % \end{block}
\end{frame}


\begin{frame}{Design of replication studies}
\begin{block}{Sample size of replication study}
  \begin{itemize}
  \item Direct replication $\rightarrow$ procedures of replication study as closely matched as possible to original study 
\item \alert{But} same sample size as in original study can lead to a very low power \citep{Goodman1992}
\item[] $\rightarrow$ proper sample size calculation is essential 
  \end{itemize}
\end{block}
\centering
\includegraphics[width=0.8\textwidth]{images_presentation/goodmana.pdf}
\end{frame}

\begin{frame}[fragile]{What is used in practice}
\begin{block}{Standard sample size calculation}
  \begin{itemize}
<< echo = FALSE, eval = FALSE >>=
sampleSizeZtest = function(delta, sd, sig.level = 0.05, power){
  u <- qnorm(p = power)
  v <- qnorm(p = 1 - sig.level/2)
  n <- 2*(u + v)^2*sd^2/delta^2
  return(n)
}
sampleSizeZtest(delta = 0.25, sd = 0.4, sig.level = 0.01, power = 0.95)
@
    \item Goal is to have between 80\%  and 95\% power in the replication study to detect the {\color{red}{effect estimate from the original study}}.
    \item Original effect estimate is sometimes shrunken by a factor of 50\%.
    \item Uncertainty of original effect estimate is ignored
  \end{itemize}
\end{block}
\end{frame}

\begin{frame}{Standard sample size calculation}
<<echo = F>>=
sampleSizeZtest = function(delta, sd, sig.level = 0.05, power){
  u <- qnorm(p = power)
  v <- qnorm(p = 1 - sig.level/2)
  n <- 2*(u + v)^2*sd^2/delta^2
  return(n)
}

grid <- seq(0.09, 0.225, 0.001)
deltahat <- 0.15
se <- 0.025
ss <- sampleSizeZtest(delta = grid, sd = 0.4, sig.level = 0.01, power = 0.95)
ss1 <- sampleSizeZtest(delta = deltahat, sd = 0.4, sig.level = 0.01, power = 0.95)

set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)

legend("topright", 
       "Power = 95%", 
       bty = "n", 
       cex = 1.75)

@

\end{frame}


\begin{frame}{Standard sample size calculation}
<<echo = F>>=

set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)
lines(rep(deltahat, 2), 
      c(0, ss1), 
      lty=2,
      lwd = 2)
points(deltahat, 
       ss1, 
       pch=19, 
       cex=1.2, 
       col=1) 
points(deltahat, 
       0, 
       pch=19, 
       cex=1.2, 
       col=1) 
lines(c(0, deltahat), 
      rep(ss1, 2), 
      lty = 2,
      col = 1, 
      lwd = 2)
axis(2, 
     at=ss1, 
     label=round(ss1), 
     col=1, 
     col.axis=1, 
     cex.axis = 1.2)

legend("topright", 
       "Power = 95%", 
       bty = "n",
       cex = 1.75)

@

\end{frame}
\begin{frame}{Incorporation of uncertainty}
<<echo = F>>=

set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)
lines(rep(deltahat, 2), 
      c(0, ss1), 
      lty=2,
      lwd = 2)
points(deltahat, 
       ss1, 
       pch=19, 
       cex=1.2, 
       col=1) 
points(deltahat, 
       0, 
       pch=19, 
       cex=1.2, 
       col=2) 
lines(c(0, deltahat), 
      rep(ss1, 2), 
      lty = 2,
      col = 1, 
      lwd = 2)
axis(2, 
     at=ss1, 
     label=round(ss1), 
     col=1, 
     col.axis=1, 
     cex.axis = 1.2)

plotCI(x = deltahat,
       y = 0, 
       li = quantile(deltahat2, 0.025), 
       ui = quantile(deltahat2, 0.975),
       col=2, lwd=2, add=TRUE, err="x")


legend("topright", 
       "Power = 95%", 
       bty = "n",
       cex = 1.75)

@
\end{frame}

\begin{frame}{Incorporation of uncertainty}
<<echo = F>>=
set.seed(12345)
nsim <- 100000
deltahat2 <- rnorm(nsim, mean=deltahat, sd=se)
ss2 <- sampleSizeZtest(delta = deltahat2, sd = 0.4, sig.level = 0.01, power = 0.95)

library(gplots)
par(las=1)

plot(grid, 
     ss, 
     type="l", 
     xlab="Original effect estimate", 
     ylab="Replication sample size", 
     ylim=c(0, 800), 
     cex.lab = 1.5, 
     cex.axis = 1.2, 
     lwd = 2)
lines(rep(deltahat, 2), 
      c(0, ss1), 
      lty=2,
      lwd = 2)
points(deltahat, 
       ss1, 
       pch=19, 
       cex=1.2, 
       col=1) 
points(deltahat, 
       0, 
       pch=19, 
       cex=1.2, 
       col=2) 
points(min(grid), 
       mean(ss2), 
       pch=19, 
       cex=1.2, 
       col=2) 
lines(c(0, deltahat), 
      rep(ss1, 2), 
      lty = 2,
      col = 1, 
      lwd = 2)
axis(2, 
     at=ss1, 
     label=round(ss1), 
     col=1, 
     col.axis=1, 
     cex.axis = 1)

plotCI(x = deltahat, y=0, li=quantile(deltahat2, 0.025), ui = quantile(deltahat2, 0.975),
       col=2, lwd=2, add=TRUE, err="x")

plotCI(x = min(grid), y=mean(ss2), li=quantile(ss2, 0.025), ui = quantile(ss2, 0.975),
       col=2, lwd=2, add=TRUE, err="y")
lines(rep(quantile(deltahat2, 0.025), 2), 
      c(0, quantile(ss2, 0.975)), 
      lty=2, col=2,  
      lwd = 2)
lines(rep(quantile(deltahat2, 0.975), 2), 
      c(0, quantile(ss2, 0.025)), 
      lty=2, col=2, 
      lwd = 2)
lines(c(0, quantile(deltahat2, 0.975)), 
      rep(quantile(ss2, 0.025), 2), 
      lty=2, 
      col=2, 
      lwd = 2)
lines(c(0, quantile(deltahat2, 0.025)), 
      rep(quantile(ss2, 0.975), 2), 
      lty =2, 
      col=2, 
      lwd = 2)
axis(2, 
     at=mean(ss2), 
     label=round(mean(ss2)), 
     col = 2, 
     col.axis = 2, 
     cex.axis = 1.2)

legend("topright", 
       "Power = 95%", 
       bty = "n",
       cex = 1.75)

@
\end{frame}


\begin{frame}{Incorporation of uncertainty}
\begin{block}{Design prior}
\begin{itemize}
\item{\color{red} \emph{Conditional}}: ignores uncertainty of original study
\item {\color{red} \emph{Predictive}}: reflects that there is 
uncertainty about the true effect after the original experiment
\end{itemize}
\end{block}
\end{frame}

\begin{frame}{Power of the two-trials rule} 
  \framesubtitle{in absolute terms}
  \begin{block}{Conditional design prior}
    \begin{eqnarray*}
  \mbox{Power} = \Phi\left(\frac{\hat\theta_o \sqrt{n_r}}{\sigma} - z_{1 - \alpha}\right)
    \end{eqnarray*}
  \end{block}
  \pause
    \begin{block}{Predictive design prior}
    \begin{eqnarray*}
   \mbox{Power} = \Phi\left({\color{red} \sqrt{\frac{n_o}{n_o + n_r}}}
   \left(\frac{\hat\theta_o \sqrt{n_r}}{\sigma} - z_{1 - \alpha}\right)\right)
    \end{eqnarray*}
  \end{block}
\end{frame}


\begin{frame}{Power of the two-trials rule} 
  \framesubtitle{in relative terms}
  \begin{block}{Conditional design prior}
    \begin{eqnarray*}
  \mbox{Power} = \Phi\left(z_o \sqrt{c} - z_{1- \alpha}\right)
    \end{eqnarray*}
  \end{block}
  \pause
    \begin{block}{Predictive design prior}
    \begin{eqnarray*}
   \mbox{Power} = \Phi\left({\color{red} \sqrt{\frac{1}{c+1}}}
   \left(z_o \sqrt{c} - z_{1- \alpha}\right)\right)
    \end{eqnarray*}
  \end{block}
\end{frame}


\begin{frame}{Power of the two-trials rule} 
  \framesubtitle{with shrinkage}
  \begin{block}{Conditional design prior}
    \begin{eqnarray*}
  \mbox{Power} = \Phi\left({\color{foo} (1 - s)} z_o \sqrt{c} - z_{1- \alpha}\right)
    \end{eqnarray*}
  \end{block}
  \pause
    \begin{block}{Predictive design prior}
    \begin{eqnarray*}
   \mbox{Power} = \Phi\left({\color{black} \sqrt{\frac{1}{c+1}}}
   \left( {\color{foo} (1 - s)} z_o \sqrt{c} - z_{1- \alpha}\right)\right)
    \end{eqnarray*}
  \end{block}
\end{frame}


\begin{frame}
\section{Exercise 2 -- Design of replication studies}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Exercise session 2}}
  \\~\\
  {\LARGE Design based on the two-trials rule}
   \end{center}
  % \end{block}
\end{frame}

\begin{frame}{Design based on the two-trials rule} 
%%    \framesubtitle{Functions}
  \begin{block}{}
Two functions: 
    \begin{itemize}
    \item \texttt{powerSignificance()} and \texttt{sampleSizeSignificance()}
    \end{itemize}

\pause

Main arguments (\texttt{default}):
\begin{itemize}
\item \texttt{zo}
\item \texttt{c} (\texttt{1})
\item \texttt{power}
\item \texttt{designPrior} (\texttt{"conditional"})
\item \texttt{shrinkage} (\texttt{0})
\item \texttt{level} (\texttt{0.025})
\item \texttt{alternative} (\texttt{"one.sided"})
\end{itemize}

\end{block}
\end{frame}

\begin{frame}[fragile]{Example from \citet{Pyc2010}}
\framesubtitle{No shrinkage}
  \begin{block}{}
    \begin{itemize}
      \item $p$-value $p_o =$ \Sexpr{round(study$po/2, 3)}
      \item relative sample size $c =$ \Sexpr{round(c,1)}
    \end{itemize}

  \end{block}
  
<<>>=

# power calculation
powerSignificance(zo = p2z(0.011, alternative = "one.sided"), 
                  c = 9.2, 
                  designPrior = "conditional")
@
  
\end{frame}
\begin{frame}[fragile]{Example from \citet{Pyc2010}}
\framesubtitle{With 50\% shrinkage}
  \begin{block}{}
    \begin{itemize}
      \item $p$-value $p_o =$ \Sexpr{round(study$po/2, 3)}
      \item relative sample size $c =$ \Sexpr{round(c,1)}
    \end{itemize}

  \end{block}
  
<<>>=

# power calculation
powerSignificance(zo = p2z(0.011, alternative = "one.sided"), 
                  c = 9.2, 
                  shrinkage = 0.5, 
                  designPrior = "conditional")
@
  
\end{frame}

\begin{frame}{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
\begin{block}{Exercise 2.1}
We have five original studies that we want to replicate. The one-sided $p$-values are 
$0.0001$, $0.001$, $0.005$, $0.01$, and $0.025$, respectively. 
We decide to use the same sample size as in the original study ($c = 1$). 
\begin{itemize}
\item Compute and plot the conditional and predictive power of the five replication studies. Use the function \texttt{powerSignificance()} % Goal: bordeline significant original study: very low power with both methods
\item Shrink the original effect estimate by a factor of 25\% and use a conditional design prior. How does the power compare to the conditional power without shrinkage?
\end{itemize}
  \end{block}
<<echo = FALSE, eval = F>>=

pval.or <- c(0.0001, 0.001, 0.005, 0.01, 0.03, 0.05)
pow.cond <- powerSignificance(zo = p2z(pval.or), c = 0.6, designPrior = "conditional")
pow.pred <- powerSignificance(zo = p2z(pval.or), c = 0.6, designPrior = "predictive")
plot(pval.or, pow.cond, type = "p", col = "red", ylim = c(0,100))
lines(pval.or, pow.pred, col = "blue")
  @
\end{frame}

\begin{frame}{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 2.2}
% We now know that taking the same sample size as in the original study is not optimal and want to perform a proper sample size calculation. 
\begin{itemize}
\item Compute and plot the relative sample sizes of the five studies to achieve a power of 80\% with the conditional and the predictive design prior. Use the function \texttt{sampleSizeSignificance()}.
\item Shrink the original effect estimate by a factor of 25\% and use a conditional design prior. How does the required relative sample size change compared to not shrinking the estimate?  
\end{itemize}
  \end{block}
  
\end{frame}

\begin{frame}[fragile]{Solution: Exercise 2.1}

<<echo = FALSE, eval = T, fig.height = 8>>=
par(las = 1)

pval.or <- c(0.0001, 0.001, 0.005, 0.01, 0.025)
pow.cond <- powerSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional")
pow.condRS <- powerReplicationSuccess(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional")
pow.condshrink <- powerSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional", shrinkage=0.25)
pow.pred <- powerSignificance(zo = p2z(pval.or, alternative = "one.sided"),
                              c = 1, designPrior = "predictive")
pow.predRS <- powerReplicationSuccess(zo = p2z(pval.or, alternative = "one.sided"), 
                              c = 1, designPrior = "predictive")
ss.cond <- sampleSizeSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              power=0.8, designPrior = "conditional")
ss.condshrink <- sampleSizeSignificance(zo = p2z(pval.or, alternative = "one.sided"), 
                              power=0.8, designPrior = "conditional", shrinkage=0.25)
ss.pred <- sampleSizeSignificance(zo = p2z(pval.or, alternative = "one.sided"),
                              power=0.8, designPrior = "predictive")
plot(pval.or, pow.cond*100, type = "p", col = "red", ylim = c(0,100), 
     xlab = "One-sided original p-value",
     ylab = "Power (in %)", pch = 20, cex = 1.75, 
     cex.lab = 1.5, 
     cex.axis = 1.5)
points(pval.or, pow.pred*100, col = "blue", pch = 20, cex = 1.75)
legend("topright", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       pch = 20, bty = "n", 
       cex = 2.2)
  @

\end{frame}

\begin{frame}[fragile]{Solution: Exercise 2.1}
<<echo = FALSE, eval = T, fig.height = 8>>=
par(las = 1)

po.plot <- seq(0.000001, 0.025, by = 0.0001)
pow.cond1 <- powerSignificance(zo = p2z(po.plot, alternative = "one.sided"),
                               c = 1, designPrior = "conditional")
pow.pred1 <- powerSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                               c = 1, designPrior = "predictive")
plot(po.plot, pow.cond1*100, col = "red", ylim = c(0,100), type = "l", 
           xlab = "One-sided original p-value",
     ylab = "Power (in %)", lwd = 1.8, 
     cex.lab = 1.5, 
     cex.axis = 1.5)
lines(po.plot, pow.pred1*100, col = "blue", lwd = 2)
points(pval.or, pow.cond*100, col = "red", pch = 20, cex = 1.75)
points(pval.or, pow.pred*100, col = "blue", pch = 20, cex = 1.75)
abline(h = 50, lty = 3)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")

legend("topright", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       lty = 1, bty = "n", 
       cex = 2.2, lwd = 2)

  @

\end{frame}

\begin{frame}[fragile]{Solution: Exercise 2.1}
<<echo = FALSE, eval = T, fig.height = 8>>=
par(las = 1)

pow.cond2 <- powerSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                              c = 1, designPrior = "conditional")
pow.condshrink2 <- powerSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                                    c = 1, designPrior = "conditional", 
                                    shrinkage = 0.25)
plot(po.plot, pow.cond2*100, col = "red", ylim = c(0,100), type = "l", 
      xlab = "One-sided original p-value",
     ylab = "Power (in %)", 
     lwd = 2, 
    cex.lab = 1.5, 
     cex.axis = 1.5)
lines(po.plot, pow.condshrink2*100, col = "red", lty = 2,
      lwd = 2)
abline(h = 50, lty = 3)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")
points(pval.or, pow.cond*100, col = "red", pch = 20, cex = 1.75)
points(pval.or, pow.condshrink*100, col = "red", pch = 20, cex = 1.75)
legend("topright", 
        c("Conditional without shrinkage", "Conditional with 25% shrinkage"), 
        col = c("red", "red"), 
       lty = c(1, 2), bty = "n", 
       cex = 2.2, 
       lwd = 2)

  @

\end{frame}






\begin{frame}{Solution: Exercise 2.2}
<<echo = FALSE, fig.height = 8>>=
par(las = 1)

ss.cond1 <- sampleSizeSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                                  power = 0.8, designPrior = "conditional")
ss.pred1 <- sampleSizeSignificance(zo = p2z(po.plot, alternative = "one.sided"),
                                  power = 0.8, designPrior = "predictive" )

plot(po.plot, ss.cond1, type = "l", ylim = c(0, 4), col = "red", 
     xlab = "One-sided original p-value", 
     ylab = "Relative sample size", 
     lwd = 2,
     cex.lab = 1.5, 
     cex.axis = 1.5)
lines(po.plot, ss.pred1, col = "blue", lwd = 2)
abline(h = c(1, 2, 3), col = "grey", lty = 2)
points(pval.or, ss.cond, col = "red", pch = 20, cex = 1.75)
points(pval.or, ss.pred, col = "blue", pch = 20, cex = 1.75)
legend("topleft", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       lty = 1, bty = "n", 
       cex = 2.2, 
       lwd = 2,
       bg = "white")


@
  
\end{frame}


\begin{frame}{Solution: Exercise 2.2}
<<echo = FALSE, fig.height = 8>>=
par(las = 1)

ss.condshrink1 <- sampleSizeSignificance(zo = p2z(po.plot, alternative = "one.sided"), 
                                        power = 0.8, designPrior = "conditional", 
                                        shrinkage = 0.25)

plot(po.plot, ss.cond1, type = "l", ylim = c(0, 4), col = "red", 
     xlab = "One-sided original p-value", 
     ylab = "Relative sample size", 
     lwd = 2, 
     cex.lab = 1.5, 
     cex.axis = 1.5)
lines(po.plot, ss.condshrink1, col = "red", lty = 2, 
      lwd = 2)
abline(h = c(1, 2, 3), col = "grey", lty = 2)
points(pval.or, ss.cond, col = "red", pch = 20, cex = 1.75)
points(pval.or, ss.condshrink, col = "red", pch = 20, cex = 1.75)
legend("topleft", 
        c("Conditional without shrinkage", "Conditional with 25% shrinkage"), 
        col = c("red", "red"), 
       lty = c(1, 2), bty = "n", 
       cex = 2.2, 
       lwd = 2)

@
  
\end{frame}

% 19.02.2021 : removed exercises 2.3 and 2.4 for time reason
%\begin{frame}[fragile]{Exercises}
% \framesubtitle{(Solutions available at \url{https://osf.io/fcrj6/})}
% 
%   \begin{block}{Exercise 2.3}
%   For the experimental economics replication project
%   \begin{itemize}
%   \item Calculate the conditional power for significance of each study.
%     \item Calculate now the predictive power and compare.
%   \end{itemize}

<<echo = F, eval = F>>=
eco <- subset(RProjects, project == "Experimental Economics")
@

%   \end{block}
% \end{frame}


% \begin{frame}[fragile]{Solution: Exercise 2.3}

<<echo = FALSE, fig.height=8, eval = F>>=
library("lattice")

pow_c1 <- powerSignificance(zo = p2z(eco$po),
      c = eco$se_fiso^2/eco$se_fisr^2, level = 0.025, 
                             alternative = "one.sided",
                             designPrior = "conditional")

pow_p1 <- powerSignificance(zo = p2z(eco$po),
      c = eco$se_fiso^2/eco$se_fisr^2, level = 0.025, 
                             alternative = "one.sided",
                             designPrior = "predictive")


mat1 <- matrix(c(rep(eco$study, times=2),pow_c1*100, pow_p1*100,rep(c("Conditional","Predictive"), times=c(nrow(eco),nrow(eco)))), ncol=3)

colnames(mat1) <- c("ID","power", "group")
mat1 <- as.data.frame(mat1)
mat1$ID <- as.factor(mat1$ID)
mat1$group <- factor(mat1$group, levels=c("Conditional","Predictive"), order=TRUE)
mat1$power <- as.numeric(as.character(mat1$power))

trellis.par.set(
 list(
   plot.symbol = list(col = 1, pch = 20, cex = 0.7),
   box.rectangle = list(col = alpha("black",0.5)),
   box.umbrella = list(lty = 1, col = alpha("black",0.5)),
   strip.background = list(col = "white")
 )
)
panel_bw <- function(x, y, groups, subscripts, ...) {
 panel.bwplot(x = x, y = y, ...)
 tapply(1:length(y), groups[subscripts], function(i) {
   llines(
     x = 1:nlevels(x),
     y = y[i][order(x[i])],
     col = rgb(.2, .2, .2, .2)
   )
   lpoints(
    x = 1:nlevels(x),
    y = y[i][order(x[i])],
    col = rgb(.2, .2, .2, .2),
    pch = 16,
    cex = 1.2
   )
 })
  panel.abline(h=50, col="red", lty=2)

}
bwplot(power~group, data=mat1, groups = ID, panel = panel_bw, 
        xlab=list(""),
        ylab=list("Power (in %)", cex = 2),
        between = list(x = 1), scales = list(x = "free", y="free", rot=0, cex =2),
        pch = "|")

@

% \end{frame}


% \begin{frame}{Exercises}
% \framesubtitle{(Solutions available at \url{https://osf.io/fcrj6/})}
% 
%   \begin{block}{Exercise 2.4}
%   For the experimental philosophy replicability project
%   \begin{itemize}
%   \item Calculate for each study the required relative sample size to reach a power for significance of 95\%. Use the conditional design prior.
%   \item Compare them to the actually used relative sample sizes.
%   \end{itemize}

<<size = "scriptsize", echo = F, eval = F>>=
philo <- subset(RProjects, 
                 project == "Experimental Philosophy")
@

  
%   \end{block}
% \end{frame}




% \begin{frame}[fragile]{Solution: Exercise 2.4}


<<fig.height = 7, echo = FALSE, eval = F>>=
par(mai = c(1,1.5,1,1))
ss_aut <- philo$se_fiso^2/philo$se_fisr^2
ss_cond1 <- sampleSizeSignificance(zo = p2z(philo$po), power = 0.95,
                             designPrior = "conditional")

plot(ss_aut, ss_cond1, 
     xlim = c(0.01,50), 
     ylim = c(0.01,50), 
     xlab = "Reported relative sample size", 
     ylab = "Calculated relative sample size", 
     pch = 20, 
     cex = 2.2, 
     cex.lab = 1.7, 
     cex.axis = 1.7, 
     log = "xy", 
     xaxt = "n", 
     yaxt = "n")
abline(a = 0, b = 1, 
       col = "lightpink")

axis(1, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"),cex.axis = 1.4)
axis(2, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)


@

% \end{frame}


\begin{frame}
  \section{Exercise 3 -- Design of replication studies}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{Exercise Session 3}}
  \\~\\
  {\LARGE Design based on replication success (sceptical $p$-value)}
   \end{center}
  % \end{block}
\end{frame}

\begin{frame}{Power for replication success}
  \begin{block}{Conditional design prior}
    \begin{eqnarray*}
    \mbox{Power} = \Phi\left(\sqrt{c} z_o (1 - \dmin)\right)
    \end{eqnarray*}
  \end{block}
  
  \pause
  
    \begin{block}{Predictive design prior}
    \begin{eqnarray*}
    \mbox{Power} = \Phi\left({\color{red} \sqrt{\frac{1}{c + 1}}}
    \left(\sqrt{c} z_o (1 - \dmin)\right)\right)
    \end{eqnarray*}
  \end{block}
\end{frame}


\begin{frame}{Design based on replication success}
\begin{block}{}
Two functions:
    \begin{itemize}
    \item \texttt{powerReplicationSuccess()} and \texttt{sampleSizeReplicationSuccess()}
    \end{itemize}

\pause

Main arguments (\texttt{default}):
\begin{itemize}
\item \texttt{zo}
\item \texttt{c} (\texttt{1})
\item \texttt{power}
\item \texttt{designPrior} (\texttt{"conditional"})
\item \texttt{level} (\texttt{0.025})
\item \texttt{alternative} (\texttt{"one.sided"})
\item \texttt{type} (\texttt{"golden"})
\end{itemize}

\end{block}
\end{frame}

\begin{frame}[fragile]{Example from \citet{Pyc2010}}
    \begin{itemize}
      \item $p$-value $p_o =$ \Sexpr{round(study$po/2, 3)}
      \item relative sample size $c = $ \Sexpr{round(c,1)}
    \end{itemize}
<<>>=
# power calculation
powerReplicationSuccess(zo = p2z(0.011, alternative = "one.sided"), 
                        c = 9.2, 
                        designPrior = "conditional")

@

% Explain here why we use alpha level of 0.065 and one-sided test
\end{frame}

\begin{frame}{TO DO}

  \begin{itemize}
  \item Think about the exercises for this part 
  \item Currently not so good as sample size for RS explodes for large po.
  \end{itemize}
\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 3.1}
    \begin{itemize}
    \item Compute and plot the conditional and predictive power for replication success. 
      % using the controlled ($\alpha$ = 0.065) threshold. 
      Use the function
    \texttt{powerReplicationSuccess()} with
   $c = 1$ and $p_o = 0.0001, 0.001, 0.005, 0.01$ and $0.025$.
    \item Compare conditional power for replication success with conditional power for significance (exercise 2.1).
    \end{itemize}
  \end{block}

\end{frame}

\begin{frame}[fragile]{Exercises}
\framesubtitle{(Solutions: {\scriptsize \url{https://gitlab.uzh.ch/charlotte.micheloud/replicationstudies}})}
  \begin{block}{Exercise 3.2}
\begin{itemize}
  \item Compute and plot the relative sample sizes of the five
studies to achieve a power of 80\% with the conditional
and the predictive design prior. Use the function
\texttt{sampleSizeReplicationSuccess()}.

    \item Compare the relative sample sizes with the ones
    obtained in exercise 2.2 (only for the conditional 
    design prior).
  \end{itemize}
  \end{block}
\end{frame}




\begin{frame}[fragile]{Solution: Exercise 3.1}

<<echo = F, fig.height = 8>>=
par(las = 1)
pow.cond2 <- powerReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                     c = 1, designPrior = "conditional", 
                                     alternative = "one.sided")

pow.pred2 <- powerReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                     c = 1, designPrior = "predictive", 
                                     alternative = "one.sided")

plot(po.plot, pow.cond2*100, type = "l", col = "red", ylim = c(0,100), 
     lwd = 1.5, 
     xlab = "One-sided original p-value", 
     ylab = "Power (in %)", 
     cex.lab = 1.5, 
     cex.axis = 1.5, 
     lty = 1)
lines(po.plot, pow.pred2*100, col = "blue", lwd = 1.5, lty = 1)
abline(h = 50, lty = 3, lwd = 1.5)
points(pval.or, pow.condRS*100, col = "red", pch = 20, cex = 1.75)
points(pval.or, pow.predRS*100, col = "blue", pch = 20, cex = 1.75)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")

legend("topright", 
        c("Conditional", "Predictive"), 
        col = c("red", "blue"), 
       lty = 1.5, bty = "n", 
       cex = 2.2, 
       lwd = 1.5)
# legend("bottomleft", 
#        c("Replication success"), 
#        lty = c(1), 
#        bty = "n", 
#        cex = 2.2, 
#        lwd = 1.5)
@

\end{frame}


\begin{frame}[fragile]{Solution: Exercise 3.1}
 
<<echo = F, fig.height = 8>>=
par(las = 1)
plot(po.plot, pow.cond2*100, type = "l", col = "red", ylim = c(0,100), 
     lwd = 1.5, 
     xlab = "One-sided original p-value", 
     ylab = "Power (in %)", 
     cex.lab = 1.5, 
     cex.axis = 1.5, 
     lty = 1)
## lines(po.plot, pow.pred2*100, col = "blue", lwd = 1.5, 
##       lty = 1)
lines(po.plot, pow.cond1*100, col = "red", lty = 2,
      lwd = 1.5)
## lines(po.plot, pow.pred1*100, col = "blue", lty = 2, 
##       lwd = 1.5)
abline(h = 50, 
       lty = 3, 
       lwd = 1.5)
points(pval.or, pow.condRS*100, col = "red", pch = 20, cex = 1.75)
## points(pval.or, pow.predRS*100, col = "blue", pch = 20, cex = 1.75)
points(pval.or, pow.cond*100, col = "red", pch = 20, cex = 1.75)
## points(pval.or, pow.pred*100, col = "blue", pch = 20, cex = 1.75)
axis(2, at = 50, label = "50", cex.axis = 1.5,
     col = "gray40")

## legend("topright", 
##         c("Conditional", "Predictive"), 
##         col = c("red", "blue"), 
##        lty = 1.5, bty = "n", 
##        cex = 2.2, 
##        lwd = 1.5)

legend("topright", 
       c("Replication success", "Significance"), 
       lty = c(1, 2), col=2, 
       bty = "n", 
       cex = 2.2, 
       lwd = 1.5)
  @
\end{frame}



\begin{frame}[fragile]{Solution: Exercise 3.2}

<<echo = F, fig.height = 7>>=
par(mfrow = c(1,1), 
    las = 1)

ss.cond2 <- sampleSizeReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"),
                                         power = 0.8, 
                                         alternative = "one.sided", 
                                         type = "golden", 
                                         designPrior = "conditional",
                                         level = 0.025)

ss.pred2 <- sampleSizeReplicationSuccess(zo = p2z(po.plot, alternative = "one.sided"), 
                                         power = 0.8, 
                                         alternative = "one.sided", 
                                         designPrior = "predictive",
                                         type = "golden", 
                                         level = 0.025)
plot(po.plot, 
     ss.cond2, 
     type = "l", 
     col = "red", 
     ylim = c(0, 10), 
     cex.lab = 1.5, 
     cex.axis = 1.5, 
     ylab = "Relative sample size", 
      xlab = "One-sided original p-value", 
     lwd = 2)

lines(po.plot, 
      ss.pred2, 
      type = "l", 
      col = "blue", 
      lwd = 2)

legend("topleft", 
       c("Conditional", "Predictive"), 
       col = c("red", "blue"), 
       lty = 1, 
       bty = "n", 
       cex = 1.75, 
       lwd = 2)
@
\end{frame}


\begin{frame}[fragile]{Solution: Exercise 3.2}


<<echo = F, fig.height = 7>>=

par(mfrow = c(1,1), 
    las = 1)
plot(po.plot, ss.cond1, type = "l", ylim = c(0, 10), col = "red", 
     xlab = "One-sided original p-value", 
     ylab = "Relative sample size", 
     lwd = 2,
     cex.lab = 1.5, 
     cex.axis = 1.5, 
     lty = 2)

lines(po.plot, ss.cond2, 
      col = "red", 
      lty = 1, 
      lwd = 2)

legend("topleft", 
       c("Replication Success", "Significance"),
       lty = c(1, 2), 
       col = "red",
       bty = "n", 
       cex = 1.75, 
       lwd = 2)

@

\end{frame}
% 19.2.2021 Removed from time reason
% \begin{frame}[fragile]{Exercises}
% \framesubtitle{(Solutions available at \url{https://osf.io/fcrj6/})}
%   \begin{block}{Exercise 3.2}
%   For the experimental economics replication project
%   \begin{itemize}
%   \item Calculate the conditional power for replication success of each study with the controlled threshold
%     \item Compare it to the predictive power for replication success
%   \end{itemize}
%   \end{block}
% \end{frame}


% \begin{frame}[fragile]{Solution: Exercise 3.2}
<<echo = FALSE, fig.height=8, eval = F >>=
pow_c2 <- powerReplicationSuccess(zo = p2z(eco$po),
                                  c = eco$se_fiso^2/eco$se_fisr^2, 
                                  alternative = "one.sided",
                                  designPrior = "conditional")
pow_p2 <- powerReplicationSuccess(zo = p2z(eco$po),
                                  c = eco$se_fiso^2/eco$se_fisr^2, 
                                  alternative = "one.sided",
                                  designPrior = "predictive")

mat2 <- matrix(c(rep(eco$study, times=2),
                 pow_c2*100, pow_p2*100,rep(c("Conditional","Predictive"), 
                                            times=c(nrow(eco),nrow(eco)))), ncol=3)

colnames(mat2) <- c("ID","power", "group")
mat2 <- as.data.frame(mat2)
mat2$ID <- as.factor(mat2$ID)
mat2$group <- factor(mat2$group, levels=c("Conditional","Predictive"), order=TRUE)
mat2$power <- as.numeric(as.character(mat2$power))

bwplot(power~group, data=mat2, groups = ID, panel = panel_bw, 
        xlab=list(""),
        ylab=list("Power (in %)", cex = 2),
        between = list(x = 1), scales = list(x = "free", y="free", rot=0, cex =2),
        pch = "|")
@
% \end{frame}

% \begin{frame}{Exercises}
% \framesubtitle{(Solutions available at \url{https://osf.io/fcrj6/})}
%   \begin{block}{Exercise 3.3}
%   For the experimental philosophy replicability project
%   \begin{itemize}
%   \item Calculate for each study the required relative sample size to reach a power for replication success of 95\%. Use the  function \texttt{sampleSizeReplicationSuccess()} with conditional design prior and the controlled threshold ($\alpha$ = 0.065). 
%   \item Compare the results to the actually used relative sample sizes.
%   \end{itemize}
%   \end{block}
% \end{frame}
% 
% 
% \begin{frame}[fragile]{Solution: Exercise 3.3}
% \framesubtitle{Replication success}

<<fig.height = 7, echo = F, eval = F>>=
par(mai = c(1,1.5,1,1))

ss_c2 <- sampleSizeReplicationSuccess(zo = p2z(philo$po), power = 0.95, 
                             alternative = "one.sided",
                             designPrior = "conditional")

plot(ss_aut, ss_c2, 
     xlim = c(0.01,50), 
     ylim = c(0.01,50), 
     xlab = "Reported relative sample size", 
     ylab = "Calculated relative sample size", 
     pch = 20, 
     cex = 2.2, 
     cex.lab = 1.7, 
     cex.axis = 1.7, log = "xy",
     xaxt = "n", 
     yaxt = "n")
abline(a = 0, b = 1, 
       col = "lightpink")
axis(1, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)
axis(2, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)
@

% \end{frame}
% 
% \begin{frame}[fragile]{Solution: Exercise 2.4}
% \framesubtitle{Significance}

<<fig.height = 7, echo = FALSE, eval = F>>=
par(mai = c(1,1.5,1,1))
ss_aut <- philo$se_fiso^2/philo$se_fisr^2
ss_cond1 <- sampleSizeSignificance(zo = p2z(philo$po), power = 0.95,
                             designPrior = "conditional")

plot(ss_aut, ss_cond1, 
     xlim = c(0.01,50), 
     ylim = c(0.01,50), 
     xlab = "Reported relative sample size", 
     ylab = "Calculated relative sample size", 
     pch = 20, 
     cex = 2.2, 
     cex.lab = 1.7, 
     cex.axis = 1.7, 
     log = "xy", 
     xaxt = "n", 
     yaxt = "n")
abline(a = 0, b = 1, 
       col = "lightpink")

axis(1, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"),cex.axis = 1.4)
axis(2, las = 1, at = c(0.01, 0.1, 1, 10, 50), labels = c("1/100", "1/10", "1", "10", "50"), cex.axis = 1.4)


@

% \end{frame}




% \begin{frame}{Outlook}
% \section{Outlook}
% \begin{itemize}
%   
%   \item \alert{Between-study heterogeneity} \\
%   $\rightarrow$ relative heterogeneity \texttt{h} can be specified in some functions
%   % $= \tau^2/\sigma^2_o$
%   
%   \item \alert{Data-driven shrinkage} with empirical Bayes \\
%   $\rightarrow$ \texttt{designPrior = "EB"}
%   
%   \item \alert{Interim analysis} \\
%   $\rightarrow$ \texttt{powerSignificanceInterim()}
%   
%   \item Sample size based on \alert{relative effect size}
% \end{itemize}
% \end{frame}

\begin{frame}
\section{More advanced topics}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\Huge \textbf{More advanced topics}}
   \end{center}
  % \end{block}
\end{frame}

\begin{frame}
\section{More advanced topics}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\huge \textbf{Meta-analysis and multiple replication studies}}
   \end{center}
  % \end{block}
\end{frame}

\begin{frame}[fragile]{TODO}
  \begin{itemize}
    \item Introducing meta-analysis 
    \item Introducing multiple replication studies per original study
    \item Preparing an exercise with the dataset from Protzo
    \end{itemize}
<<>>=
data("protzko2020")
head(protzko2020, 10)
@
  
\end{frame}

\begin{frame}[fragile]
\frametitle{Show Protzko et al paper (published by now?)}
\end{frame}

\begin{frame}
\frametitle{Forest plots}
  \frametitle{for the $16$ experiments}

\makebox[1\textwidth][c]{  
  \resizebox{1\textwidth}{!} {
<<echo = F>>=
# graphics.off()
parOld <- par(mar = c(5, 8, 4, 2), mfrow = c(4, 4))
experiments <- unique(protzko2020$experiment)
for (ex in experiments) {
  ## compute CIs
  dat <- subset(protzko2020, experiment == ex)
  za <- qnorm(p = 0.975)
  plotDF <- data.frame(lower = dat$smd - za*dat$se,
                       est = dat$smd,
                       upper = dat$smd + za*dat$se)
colpalette <- c("#000000", "#1B9E77", "#D95F02")
cols <- colpalette[dat$type]
yseq <- seq(1, nrow(dat))

## forestplot
plot(x = plotDF$est, y = yseq, xlim = c(-0.15, 0.8),
     ylim = c(0.8*min(yseq), 1.05*max(yseq)), type = "n",
     yaxt = "n", xlab = "Effect estimate (SMD)", ylab = "")
abline(v = 0, col = "#0000004D")
arrows(x0 = plotDF$lower, x1 = plotDF$upper, y0 = yseq, angle = 90,
       code = 3, length = 0.05, col = cols)
points(y = yseq, x = plotDF$est, pch = 20, lwd = 2, col = cols)
axis(side = 2, at = yseq, las = 1, labels = dat$type, cex.axis = 0.85)
title(main = ex)
}
par(parOld)
@
  }
} 
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}
\frametitle{Effect Measures}
\begin{itemize}
\item For \alert{continuous outcomes}
 \begin{itemize}
\item    Difference in means $\theta$ between treatment groups
\end{itemize}
 \item For \alert{binary/event outcomes} relative treatment effects
    are preferred:
  \begin{itemize}
\item  Relative risk $\RR$
  \item Odds ratio $\OR$
    \item Hazard ratio $\HR$
      \end{itemize}
  \item These are usually considered on a log-scale: $\theta=\log(\RR)$, 
    $\theta=\log(\OR)$, $\theta=\log(\HR)$
\end{itemize}
\end{frame}

\begin{frame}
\frametitle{Example: Incidence of Preeclampsia in nine RCTs}
\framesubtitle{Effect measure: Odds ratio for diuretic vs.~control}

\begin{center}
    \begin{tabular}{lrlrlr}
      \textbf{Study}   & \multicolumn{2}{c}{\textbf{Diuretic}} & \multicolumn{2}{c}{\textbf{Control}} %
      & \textbf{OR} \\ \hline
      Weseley           & 11\% & (14/131)       & 10\% & (14/136)       & 1.04 \\
      Flowers           &  5\% & (21/385)       & 13\% & (17/134)       & 0.40 \\
      Menzies           & 25\% & (14/57)        & 50\% & (24/48)        & 0.33 \\
      Fallis            & 16\% & (6/38)         & 45\% & (18/40)        & 0.23 \\
      Cuadros           &  1\% & (12/1011)      &  5\% & (35/760)       & 0.25 \\
      Landesman         & 10\% & (138/1370)     & 13\% & (175/1336)     & 0.74 \\
      Krans             &  3\% & (15/506)       &  4\% & (20/524)       & 0.77 \\
      Tervila           &  6\% & (6/108)        &  2\% & (2/103)        & 2.97 \\
      Campbell          & 42\% & (65/153)       & 39\% & (40/102)       & 1.14 \\  \hline
    \end{tabular}
\end{center}

\end{frame}

<<ch1, echo=F>>=

preeclampsia <- read.table("data/preeclampsia.txt", header = TRUE)

diuretics <- with (preeclampsia,
                   c (sum (Diuretic[Preeclampsia == "yes"]), sum (Diuretic[Preeclampsia == "no"]))
                   )
controls <- with (preeclampsia,
                   c (sum (Control[Preeclampsia == "yes"]), sum (Control[Preeclampsia == "no"]))
                   )
logOddsRatio <- log (diuretics[1] * controls[2] / diuretics[2] / controls[1])
standardError <- sqrt (sum (1/diuretics) + sum (1/controls))
waldKiLogOddsRatio <- logOddsRatio + c (-1, 1) * 1.96 * standardError
waldData <- list (logOddsRatio, waldKiLogOddsRatio)


## compute data
oddsRatio <- function (square)
    (square[1,1] * square[2,2]) / (square[1,2] * square[2,1])

variance <- function (square)
    sum (1 / square)

groups <- split (subset (preeclampsia, select = c (Diuretic, Control)),
                 preeclampsia[["Trial"]])

logOddsRatios <- log (sapply (groups, oddsRatio))
variances <- sapply (groups, variance)
w <- 1/variances
num <- sum(w*logOddsRatios)
den <- sum(w)
theta.hat <- num/den
se.theta.hat <- 1/sqrt(sum(w))
wald.z <- (theta.hat)/se.theta.hat
wald.p <- 2*pnorm(abs(wald.z), lower.tail=FALSE)

t.homo <- sum(w*(logOddsRatios-theta.hat)^2)
n <- length(logOddsRatios)
p.homo <- pchisq(t.homo, df=n-1, lower.tail=FALSE)

@ 

\begin{frame}[fragile]
\frametitle{Graphical Summary with 95\% CIs}
\framesubtitle{Forest Plot}
\begin{center}
\setkeys{Gin}{width=0.75\textwidth}
<<ch2, echo=FALSE>>=
## mar <- par("mar")
## mar[2] <- 12
## par(mar=c(5.1, 12, 4.1, 2.1))

## plot intervals with point estimates
library (lattice)

## study effects
postSd <- sqrt (variances)
postLower <- logOddsRatios - postSd * 1.96
postUpper <- logOddsRatios + postSd * 1.96

## plot intervals with point estimates

panel.ci <- function(x, y, lx, ux, subscripts, ...)
{
    x <- as.numeric(x)
    y <- as.numeric(y)

    lx <- as.numeric(lx[subscripts])
    ux <- as.numeric(ux[subscripts])

    panel.dotplot(x, y, lty = 2, ...)            # normal dotplot for point estimates
    panel.arrows(lx, y, ux, y,          # draw intervals
                 length = 0.1, unit = "native",
                 angle = 90,            # deviation from line
                 code = 3,              # left and right whisker
                 ...)
    panel.abline (v = 0, lty = 2)       # reference line
}

studyNames <- c (names (postLower))
studyNames <- ordered (studyNames, levels = rev (studyNames)) # levels important for order!

ciData <- data.frame (low = postLower, 
                      up = postUpper,
                      mid = logOddsRatios,
                      names = studyNames
                      )
ciData[["signif"]] <- with (ciData,
                            up < 0 | low > 0)
ciData[["farbe"]] <- with (ciData,
                           ifelse (signif, "black", "black"))

randomEffectsCiPlot <- with (ciData,
                             dotplot (names ~ mid,
                                      panel = panel.ci,
                                      lx = low, ux = up,
                                      pch = 19, col = farbe,
                                      xlim = c (-3, 3), xlab = "Log Odds Ratio",
                                      scales = list (cex = 1)
                                      )
                             )
print (randomEffectsCiPlot)


@
\end{center}
\end{frame}

%% \begin{frame}[fragile]
%% \frametitle{Forest Plot in \texttt{R}}


%% <<echo=FALSE>>=

%% Preeclampsia <- data.frame(study=names(logOddsRatios), logOR=logOddsRatios, se=sqrt(variances), 
%%                            row.names=NULL)

%% @ 

%% <<>>=
%% head(Preeclampsia)
%% library(meta)

%% @ 

%% \end{frame}

\section{Meta-Analysis}
\subsection{Fixed Effect Model}

\begin{frame}
\frametitle{Notation and Overall Effect}
\framesubtitle{Fixed effect model}
\begin{itemize}
\item Notation: 
  \begin{itemize}
\item $i=1,\ldots, n$ trials
\item $\theta_i$, $\hat \theta_i$: true and estimated study-specific treatment effect
\item standard error $\sigma_i = \se(\hat \theta_i)$ of $\hat \theta_i$
\item variance $v_i = \sigma_i^2$
%%\item $w_i=1/v_i$: (estimated) precision of $\hat \theta_i$ 
\end{itemize}
\item \alert{Homogeneity} assumption: $\theta_i = \theta$ for all $i$
\item The estimate $\hat \theta$ of the overall treatment effect $\theta$ is then a
  \alert{weighted average} of study-specific estimates $\hat \theta_i$
  with \alert{inverse variance weights} $w_i=1/v_i$:
  \[
  \hat \theta = \frac{\sum w_i \hat \theta_i}{\sum w_i}
\mbox{  with }
  \se(\hat \theta) =  1/\sqrt{\sum w_i}.
  \]
%% \item[$\rightarrow$]  Wald test statistic $z=\hat \theta/\se(\hat \theta)$
%% for $H_0$: $\theta = 0$.
%% \item For the preeclampsia study we obtain for $\theta=\log(\OR)$: $\hat
%%   \theta=\Sexpr{format(theta.hat,digits=2, nsmall=2)}$, so $\widehat{\OR}=
%%   \exp(\Sexpr{format(theta.hat,digits=2, nsmall=2)}) = 
%%   \Sexpr{format(exp(theta.hat),digits=2, nsmall=2)}$, with  $\se(\hat
%%   \theta)=\Sexpr{format(se.theta.hat,digits=2, nsmall=2)}$ %% and $z=\Sexpr{round(wald.z, 2)}$ 
%%   ($p\Sexpr{format.pval(wald.p,digits=2, eps=0.0001, scientific=FALSE)}$ for $H_0$: $\theta = 0$.).
\end{itemize}
\end{frame}

\begin{frame}[fragile]
\frametitle{Presentation in Forest Plot}
\framesubtitle{Fixed effect model}
\vspace{2cm}

\begin{center}
\begin{figure}[h!]
\setkeys{Gin}{width = 1\textwidth}
%%\vspace*{-1cm}
<<ch4.0, echo = FALSE>>=

pree <- read.csv("data/preeclampsia.csv", header = TRUE, sep = ",", dec = ".", fill = TRUE)     
pree <- pree[order(pree$study),]

#transformVarNames(pree, "pree")
study       <- pree$study
treatedPre <- pree$diur_pre
treatedTot <- pree$diur_tot
controlPre <- pree$plac_pre
controlTot <- pree$plac_tot
a <- treatedPre
b <- treatedTot
c <- controlPre
d <- controlTot
@ 
\vspace*{-2cm}

<<ch4b.0, echo = TRUE, fig.height=7.5, fig.width=9.75>>=
library(meta)
meta1 <- metabin(event.e = treatedPre, n.e = treatedTot, 
                 event.c = controlPre, n.c = controlTot, 
                 sm = "OR" , method = "Inverse", studlab = study)
forest(meta1, comb.fixed=TRUE, comb.random=FALSE) 
@ 

\end{figure}
\end{center}
%% \vspace{1cm}
<<ch5.0, echo=F>>=

or.fixed <- exp(meta1$TE.fixed)
or.lower <- exp(meta1$lower.fixed)
or.upper <- exp(meta1$upper.fixed)
ci.fixed <- c(or.lower, or.upper)

or.random <- exp(meta1$TE.random)
or.lower <- exp(meta1$lower.random)
or.upper <- exp(meta1$upper.random)
ci.random <- c(or.lower, or.upper)



@ 
\end{frame}


\subsection{Cochran's Test for Heterogeneity}

\begin{frame}
\frametitle{Test for Heterogeneity}
\begin{itemize}
\item Under the \alert{homogeneity} assumption, we have
\[
Q = \sum w_i (\hat \theta_i - \hat \theta)^2 \sima \chi^2_{n-1}
\]
\item This can be used to calculate the $p$-value of \alert{Cochran's test for heterogeneity}. 
\item For the preeclampsia data, this test yields $Q = \Sexpr{round(t.homo, 1)}$ at $n-1=8$ degrees of freedom ($p=\Sexpr{format.pval(p.homo,digits=1, eps=0.0001, scientific=FALSE)}$).
\item[$\rightarrow$] Strong evidence for heterogeneity between studies. 
\item[$\rightarrow$]  Fixed effect model questionable. 
  %% \item But: ``test lacks power'', ``limited usefulness in the context
%%   of meta-analysis''
\end{itemize}
\end{frame}


\subsection{Random Effects Model}

\begin{frame}
\frametitle{Random Effects Model}
\begin{itemize}
\item 
Assumes that the $\theta_i$'s come from a normal distribution with
mean $\theta^*$ and \alert{heterogeneity variance} $\tau^2$:
\[
\hat \theta_i \given \theta_i  \sim   \Nor(\theta_i, v_i) \quad \mbox{ and }
\quad \theta_i   \sim   \Nor(\theta^*, \tau^2),
\]
so marginally
\[
\hat \theta_i \sim   
\Nor(\theta^*, v_i + \tau^2).
\]
\item The overall effect estimate $\hat \theta^*$ is now based on the weights
  $$w_i^*  =  {1}/{(v_i + \tau^2)}.$$
%% \[
%%   \hat \theta^*  = \frac{\sum w_i^* \hat \theta_i}{\sum w_i^*}, 
%%   \mbox{ with }
%% %% w_i^*  =  \frac{1}{v_i + \tau^2} \mbox{ and }
%%   \se(\hat \theta^*) = {1}/{\sqrt{\sum w_i^*}}.
%% \]
%% with weights $w_i^*  =  {1}/{(v_i + \tau^2)}$.
\item Compared to the fixed effect model, 
\begin{itemize}
\item the confidence intervals for the
  overall treatment effect will become wider, 
\item  large studies will obtain less weight. 
\end{itemize}
%% \item[$\rightarrow$] $z^*=\hat \theta^*/\se(\hat \theta^*)$ can be used to test $H_0$: $\theta^*=0$.
%  under heterogeneity.
%\item For the preeclampsia data, the test gives $\chi^2_1 = 6.4$ ($p=0.011$)
\end{itemize}
\end{frame}

\begin{frame}
\frametitle{Estimate of Heterogeneity Variance and Higgins' $I^2$}
  \begin{itemize}
  \item \alert{Moment estimator} of heterogeneity variance compares
    $Q$-statistic to its expectation $n-1$ under homogeneity.
\item Truncation at zero and appropriate scaling gives 
  \[
  \hat \tau^2 = \left\{Q-(n-1)\right\}_{+} / \left\{\textstyle\sum w_i - \textstyle\sum w_i^2/\textstyle\sum w_i\right\}
  \]
\item Standard \alert{DerSimonian-Laird} approach plugs $\hat \tau^2$ in $w_i^* = {1}/{(v_i + \tau^2)}$,  
  the alternative \alert{Hartung-Knapp} adjustment accounts for 
  the uncertainty of $\hat \tau^2$. 
%\item Standard deviation $\hat \tau$ rather than $\hat \tau^2$ is often reported. 
%where $Q = \sum w_i (\hat \theta_i - \hat \theta)^2$
<<ch3, echo=F>>=

Q <- t.homo
sigma2.hat <- max(0, (Q-(n-1))/(sum(w)-sum(w^2)/sum(w)))
w.star <- 1/(variances+sigma2.hat)
num.star <- sum(w.star*logOddsRatios)
den.star <- sum(w.star)
theta.star.hat <- num.star/den.star
se.theta.star.hat <- 1/sqrt(sum(w.star))
wald.star.z <- (theta.star.hat)/se.theta.star.hat
wald.star.p <- 2*pnorm(abs(wald.star.z), lower.tail=FALSE)

@ 
\item Easier to interpret is \alert{Higgins $I^2$}: 
  {Percentage of variance} that is attributable to study heterogeneity.
%% \item For the preeclampsia data we obtain $\hat
%%   \tau^2=\Sexpr{round((sigma2.hat),2)}$, 
%%   $\hat \theta^*=\Sexpr{round(theta.star.hat,2)}$, {\it i.e.} $\widehat{\OR}=\Sexpr{format(exp(theta.star.hat),digits=2, nsmall=2)}$, with  
%%   $\se(\hat \theta^*)=\Sexpr{round(sqrt(se.theta.star.hat),2)}$.
%%   \item The Wald test for $H_0$: $\theta^*=0$ now gives $z^*
%%     =\Sexpr{round(wald.star.z,2)}$
%%     ($p=\Sexpr{format.pval(wald.star.p,digits=2,eps=0.0001, scientific=FALSE)}$).
\end{itemize}
\end{frame}

\begin{frame}[fragile]
\frametitle{Presentation in Forest Plot}
\framesubtitle{Random effects model}
\vspace{2cm}

\begin{center}
\begin{figure}[h!]
\setkeys{Gin}{width = 1\textwidth}
%%\vspace*{-1cm}
<<ch4, echo = FALSE>>=

pree <- read.csv("data/preeclampsia.csv", header = TRUE, sep = ",", dec = ".", fill = TRUE)     
pree <- pree[order(pree$study),]

#transformVarNames(pree, "pree")
study       <- pree$study
treatedPre <- pree$diur_pre
treatedTot <- pree$diur_tot
controlPre <- pree$plac_pre
controlTot <- pree$plac_tot
a <- treatedPre
b <- treatedTot
c <- controlPre
d <- controlTot
@ 
\vspace*{-2cm}

<<ch4b, echo = TRUE, fig.height=7.5, fig.width=9.75>>=

library(meta)
forest(meta1, comb.fixed=TRUE, comb.random=TRUE)
@ 

\end{figure}
\end{center}
\vspace{1cm}
<<ch5, echo=F>>=

or.fixed <- exp(meta1$TE.fixed)
or.lower <- exp(meta1$lower.fixed)
or.upper <- exp(meta1$upper.fixed)
ci.fixed <- c(or.lower, or.upper)

or.random <- exp(meta1$TE.random)
or.lower <- exp(meta1$lower.random)
or.upper <- exp(meta1$upper.random)
ci.random <- c(or.lower, or.upper)



@ 
\end{frame}

\begin{frame}
\frametitle{Exercises}
\begin{itemize}
\item Compute fixed- and random-effects meta-analysis of Protzko (external) replications
\item Study heterogeneity estimates ($I^2$)
\item Feed this into 2TR and sceptical $p$; how many replication successes with each method?
\end{itemize}
  
\end{frame}


\begin{frame}
\section{More advanced topics}
  % \begin{block}{}
  \begin{center}
  \color{uzh@blue}{\huge \textbf{Replication studies with a sequential design}}
   \end{center}
  % \end{block}
\end{frame}


\begin{frame}
\frametitle{Social Sciences Replication Project}
\begin{columns}
\begin{column}{0.5\textwidth}
\begin{center}
\includegraphics[width = 1\textwidth]{images_presentation/camerer2018.png}
\end{center}
\begin{itemize}
\item[--] 21 studies replicated
\pause
\item[--] \textcolor{purple!50!red}{11 stopped} at stage 1
\item[] \textcolor{white}{10 continued in stage 2}
\end{itemize}
% \vspace{-2.5cm}
\end{column}



\begin{column}{0.5\textwidth}
<<fig.width = 10, fig.height = 5, echo = F>>=
plot(NA, 
     axes= F, 
     xlim = c(0, 5), 
     ylim = c(0, 1), 
     xlab = "", 
     ylab = "")

segments(0, 0.5, 2, 0.5, lwd = 2)
segments(2, 0.5, 5, 0.5, lwd = 2, col = "white")
points(2, 0.5, pch = "|", cex = 2)
text(1, 0.7, "Stage 1", cex = 2)
text(3.5, 0.7, "Stage 2", cex = 2, col = "white")
@


\vspace{-1cm}
\begin{itemize}
\item[] {\scriptsize Significant $p$-value and effect in the same direction:
\textcolor{purple!50!red}{stop}}
\item[] \textcolor{gray!20}{ \scriptsize Otherwise: stage 2}
\end{itemize}
\end{column}
\end{columns}
\end{frame}

\begin{frame}
\frametitle{Social Sciences Replication Project}
\begin{columns}
\begin{column}{0.5\textwidth}
\begin{center}
\includegraphics[width = 1\textwidth]{images_presentation/camerer2018.png}
\end{center}
\begin{itemize}
\item[--] 21 studies replicated
\item[--] \textcolor{purple!50!red}{11 stopped} at stage 1
\item[--] \textcolor{purple!50!red}{10 continued} in stage 2
\end{itemize}
% \vspace{-2.5cm}
\end{column}




\begin{column}{0.5\textwidth}
<<fig.width = 10, fig.height = 5, echo = F>>=
plot(NA, 
     axes= F, 
     xlim = c(0, 5), 
     ylim = c(0, 1), 
     xlab = "", 
     ylab = "")

segments(0, 0.5, 2, 0.5, lwd = 2)
segments(2, 0.5, 5, 0.5, lwd = 2)
points(2, 0.5, pch = "|", cex = 2)
text(1, 0.7, "Stage 1", cex = 2)
text(3.5, 0.7, "Stage 2", cex = 2)
points(5, 0.5, pch = "|", cex = 2)
@

\vspace{-1cm}
\begin{itemize}
\item[] \textcolor{gray!20} {\scriptsize Significant $p$-value and effect in the same direction:
\textcolor{gray!20}{stop}}
\item[] { \scriptsize Otherwise: stage 2}
\end{itemize}
\end{column}
\end{columns}
\end{frame}

\begin{frame}{Interim power}

  \begin{block}{}
    \begin{itemize}
    \item Power of a replication study taking into account 
    {\bf data from an interim analysis}
    \item {\it Conditional} vs {\it predictive} 
    \item Depends on {\bf $p_o$}, {\bf $c$}, but also
      \begin{itemize}
        \item {\color{red} $p_i$:} the $p$-value at interim
        \item {\color{red} $f$:} the fraction of the replication study already
        completed
      \end{itemize}
    \end{itemize}
  \end{block}
\end{frame}

\begin{frame}
\frametitle{Conditional power at interim}
\framesubtitle{Uncertainty of original result is ignored}
<<schema2, fig.height = 5, echo = F>>=
par(mfrow = c(1,1))
## Conditional
plot(NULL, xlim = c(0,12), ylim = c(0,5), 
     axes = F,
     xlab = "", 
     ylab = "", 
     # main = "Conditional power at interim"
     )
# title(main = "Conditional power at interim", 
#       line = -1,
#       cex.main = 1.5)


segments(0,1,5,1)
points(0,1, pch = "|")
points(5,1, pch = "|")
text(2.5, 3.5, "Original study", cex = 1.5)
segments(7,1,8.5,1, lty = 1)
segments(8.5,1,12,1, lty = 2)
points(7,1, pch = "|")
# points(8.5, 1, pch = "|", col = "red")
points(12,1, pch = "|")
text(9.5, 3.5, "Replication study", cex = 1.5)

## To do CI
#######
segments(2.5, 2.4, 2.5, 3, col = "grey",
         lwd = 2)
points(2.5, 3, pch = "--", col = "grey", 
       cex = 2)
points(2.5, 2.4, pch = "--", col = "grey", 
       cex = 2)
points(2.5, 2.7, pch = 20, 
       cex = 1.5)
text(3,2.7, expression(hat(theta)[o]), 
     cex = 1.3)
#######

segments(8.5, 0.7, 8.5, 1.3, col = "darkgrey")
text(8.5, 2, " Interim power\ 
calculation", col = "darkgrey", cex = 1.5)

@ 
\end{frame}


\begin{frame}
\frametitle{Predictive power at interim}
\framesubtitle{Uncertainty of original result is \textbf{not} ignored}

<<schema3, fig.height  = 5, echo = F>>=

par(mfrow = c(1,1))


# Informed predictive
plot(NULL, xlim = c(0,12), ylim = c(0,5), 
     axes = F,
     xlab = "", 
     ylab = "", 
     # main = "Informed predictive power at interim"
     )
# title(main = "Informed predictive power at interim", 
#       line = -1,
#       cex.main = 1.5)

segments(0,1,5,1)
points(0,1, pch = "|")
points(5,1, pch = "|")
text(2.5, 3.5, "Original study", cex = 1.5)
segments(7,1,8.5,1, lty = 1)
segments(8.5,1,12,1, lty = 2)
points(7,1, pch = "|")
points(12,1, pch = "|")
text(9.5, 3.5, "Replication study", cex = 1.5)

## To do the CI
#######
segments(2.5, 2.4, 2.5, 3, 
         lwd = 2)
points(2.5, 3, pch = "--", 
       cex = 2)
points(2.5, 2.4, pch = "--", 
       cex = 2)
points(2.5, 2.7, pch = 20, 
       cex = 1.5)
text(3,2.7, expression(hat(theta)[o]), 
     cex = 1.3)
#######

segments(8.5, 0.7, 8.5, 1.3, col = "darkgrey")
text(8.5, 2, "Interim power\
calculation", col = "darkgrey",
cex = 1.5)


@

\end{frame}



<<echo = F>>=
library(biostatUZH)
col0 <- function(x){
 ifelse(x< 0.05,
        paste("\\cellcolor{green!25}{", formatC(x, dig=2, format="f"), "}"),
        paste("\\cellcolor{red!25}{", formatC(x, dig=2, format="f"), "}"))
}


col1 <- function(x){
 ifelse(x< 0.025,
        paste("\\cellcolor{green!25}{", formatPval(x), "}"),
        paste("\\cellcolor{red!25}{", formatPval(x), "}"))
}

col2 <- function(x){
 ifelse(x< 30,
        paste("\\cellcolor{blue!30}{", round(x, 1), "}"),
        paste("\\cellcolor{white}{", round(x, 1), "}"))
}

col3 <- function(x){
 ifelse(x< 30,
        paste("\\cellcolor{white}{", round(x, 1), "}"),
        paste("\\cellcolor{white}{", round(x, 1), "}"))
}

col4 <- function(x){
  paste("\\cellcolor{white}{", formatPval(x), "}")
}

@

<<echo = F>>=

## Defining the variables 
level = 0.025
data("SSRP")

## ratio and relative
SSRP$c <- SSRP$se_fiso^2/SSRP$se_fisr^2
SSRP$f = SSRP$se_fisr^2/SSRP$se_fisi^2 

## we want to have everything one-sided
SSRP$zo <- SSRP$fiso/SSRP$se_fiso
SSRP$zi <- SSRP$fisi/SSRP$se_fisi
SSRP$zr <- SSRP$fisr/SSRP$se_fisr 
subs <- which(!is.na(SSRP$zr))

SSRP$po1 <- z2p(SSRP$zo, alternative = "greater")
SSRP$pi1 <- z2p(SSRP$zi, alternative = "greater")
SSRP$pr1 <- rep(NA, times = length(SSRP$zr))
SSRP$pr1[subs] <- z2p(SSRP$zr[subs], alternative = "greater")

## studies which have been stopped and final p-value
SSRP$stopped <- ifelse(is.na(SSRP$rr), 2, 1) # indicates if study has been stopped (2) or not (1) at interim
SSRP$r_final <- ifelse(is.na(SSRP$rr), SSRP$ri, SSRP$rr) # final r
SSRP$pval1_final <- ifelse(is.na(SSRP$pr1), SSRP$pi1, SSRP$pr1) # final p-value

## studies which failed to replicate at final analysis
SSRP[SSRP$stopped == 1 & SSRP$pval1_final > 0.025, "stopped"] <- 0 

## Remove Journal and Publication Year from study
SSRP$study <- gsub( ", Science|, Nature|[0-9]|et al.", "", SSRP$study)
SSRP$study <- gsub("\\(\\)", '', SSRP$study)


## new dataset: only studies not stopped at interim
SSRP_red <- SSRP[SSRP$stopped != 2,]
SSRP_red <- SSRP_red[-1, ]

@

<<preparation table interim, results = 'asis', echo = F>>=


# Conditional Power at interim
cpi <- with(SSRP_red,  
            powerSignificanceInterim(zo = zo, 
                                     zi = zi,
                                     c = c, 
                                     f = f,
                                     designPrior = "conditional",
                                     analysisPrior = "flat",
                                     level = 0.025, 
                                     alternative = "one.sided"))

# predictive power at interim
IPPi <- with(SSRP_red, 
             powerSignificanceInterim(zo = zo, 
                                      zi = zi,
                                      c = c, 
                                      f = f,
                                      designPrior = "informed predictive",
                                      analysisPrior = "flat", 
                                      level = 0.025, 
                                      alternative = "one.sided"))
# predictive power at interim
PPi <- with(SSRP_red, 
            powerSignificanceInterim(zo = zo, 
                                     zi = zi,
                                     c = c, 
                                     f = f,
                                     designPrior = "predictive",
                                     analysisPrior = "flat", 
                                     level = 0.025, 
                                     alternative = "one.sided"))

@




\begin{frame}[fragile]
\frametitle{Results}
\begin{block}{\textcolor{white}{futility boundary: 10\%}}
{\color{white} $\rightarrow$ no study stopped for futility with {\color{white} conditional power at interim}}
\end{block}


<<table-interim, echo = FALSE, results = 'asis', echo = F>>=
source("Rcode/construct_header.R")
# summary table
mat_content <- c(SSRP_red$study, 
                 col1(SSRP_red$po1),
                 SSRP_red$fiso,
                 col4(SSRP_red$pi1),
                 SSRP_red$fisi,
                 col3(cpi*100),
                 col3(IPPi*100),
                 col4(SSRP_red$pval1_final),
                 SSRP_red$fisr)

summary_table_interim <- matrix(mat_content, ncol = 9, byrow = F)

colnames(summary_table_interim) <- c("Study", "po", "ro", "pi", "ri",
                                     "CPi", "HPP",
                                     "pr","rr")

summary_table_interim <- as.data.frame(summary_table_interim)

cols <- c(3,5,9)
# make sure that c, f, r etc are numeric
summary_table_interim[,cols] = apply(summary_table_interim[,cols], 2, function (x) as.numeric(as.character(x)))

#order the table om decreasing ri
summary_table_interim <- summary_table_interim[order(summary_table_interim$ri ,summary_table_interim$pi, decreasing = c(TRUE, FALSE)),]

xt2 <- xtable(summary_table_interim,
              align =  c("l", "l","c", "c", "c", "c", "c", "c",
                         "c", "c"),
              digits = c(0, 0, 0,  2, 0,  2,1, 1, 1, 2))

names(xt2) <- c("Study",
                "\\cellcolor{Gray}$p_o$",
                "$\\hat\\theta_o$",
                " $p_i$",
                "$\\hat\\theta_i$",
                "Cond.",
                "Pred.",
                "$p_r$",
                "$\\hat\\theta_r$")
#formatting (second title row)
  a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  summary_table_interim,
  # the labels of the groups that we want to insert
  grp_names = c("", "Original", "Interim", "Interim power (in \\%)", "Replication"),
  # the number of columns each group spans
  span = c(1, 2, 2, 2, 2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

print(xt2,
      add.to.row = a_header,
      include.rownames = F,
      hline.after = F,
      sanitize.text.function=function(x){x},
      scalebox='0.6')

@

\end{frame}


\begin{frame}[fragile]
\frametitle{Results}
\begin{block}{\textcolor{white}{futility boundary: 10\%}}
{\color{white} $\rightarrow$ no study stopped for futility with {\color{white} conditional power at interim}}
\end{block}


<<echo = F, results = 'asis'>>=
mat_content2 <- c(SSRP_red$study,
                 col1(SSRP_red$po1),
                 SSRP_red$fiso,
                 col1(SSRP_red$pi1),
                 SSRP_red$fisi,
                 col3(cpi*100),
                 col3(IPPi*100),
                 col4(SSRP_red$pval1_final),
                 SSRP_red$fisr)
 
summary_table_interim2 <- matrix(mat_content2, ncol = 9, byrow = F)

colnames(summary_table_interim2) <- c("Study", "po", "ro", "pi", "ri",
                                     "CPi", "HPP",
                                     "pr","rr")

summary_table_interim2 <- as.data.frame(summary_table_interim2)

cols <- c(3,5,9)
# make sure that c, f, r etc are numeric
summary_table_interim2[,cols] = apply(summary_table_interim2[,cols], 2, function (x) as.numeric(as.character(x)))

#order the table om decreasing ri
summary_table_interim2 <- summary_table_interim2[order(summary_table_interim2$ri ,summary_table_interim2$pi, decreasing = c(TRUE, FALSE)),]

xt3 <- xtable(summary_table_interim2,
              align =  c("l", "l","c", "c", "c", "c", "c", "c",
                         "c", "c"),
              digits = c(0, 0, 0,  2, 0,  2,1, 1, 1, 2))

names(xt3) <- c("Study",
                "\\cellcolor{Gray}$p_o$",
                "$\\hat\\theta_o$",
                "\\cellcolor{Gray}$p_i$",
                "$\\hat\\theta_i$",
                "Cond.",
                "Pred.",
                "$p_r$",
                "$\\hat\\theta_r$")


print(xt3,
      add.to.row = a_header,
      include.rownames = F, 
      hline.after = F,
      sanitize.text.function=function(x){x},
      scalebox='0.6')
@


\end{frame}


\begin{frame}[fragile]
\frametitle{Results}
\begin{block}{\textcolor{red}{futility boundary: 10\%}}
$\rightarrow$ no study stopped for futility with {\color{foo} conditional power at interim}
\end{block}

<<echo = F, results = 'asis'>>=

names(xt3) <- c("Study",
                "\\cellcolor{Gray}$p_o$",
                "$\\hat\\theta_o$",
                "\\cellcolor{Gray}$p_i$",
                "$\\hat\\theta_i$",
                "\\cellcolor{Gray}Cond.",
                "Pred.",
                "$p_r$",
                "$\\hat\\theta_r$")


print(xt3,
      add.to.row = a_header,
      include.rownames = F,
      hline.after = F,
      sanitize.text.function=function(x){x},
      scalebox='0.6') 
@

\end{frame}


\begin{frame}[fragile]
\frametitle{Results}
\begin{block}{\textcolor{red}{futility boundary: 10\%}}
$\rightarrow$ four studies stopped for futility with {\color{foo} 
predictive power at interim}
\end{block}


<<echo = F, results = 'asis'>>=
mat_content3 <- c(SSRP_red$study,
                 col1(SSRP_red$po1),
                 SSRP_red$fiso,
                 col1(SSRP_red$pi1),
                 SSRP_red$fisi,
                 col3(cpi*100), 
                 col2(IPPi*100),
                 col4(SSRP_red$pval1_final),
                 SSRP_red$fisr)

summary_table_interim3 <- matrix(mat_content3, ncol = 9, byrow = F)

colnames(summary_table_interim3) <- c("Study", "po", "ro", "pi", "ri",
                                     "CPi", "HPP",
                                     "pr","rr")

summary_table_interim3 <- as.data.frame(summary_table_interim3)

cols <- c(3,5,9)
# make sure that c, f, r etc are numeric
summary_table_interim3[,cols] = apply(summary_table_interim3[,cols], 2, function (x) as.numeric(as.character(x)))

#order the table om decreasing ri
summary_table_interim3 <- summary_table_interim3[order(summary_table_interim3$ri ,summary_table_interim3$pi, decreasing = c(TRUE, FALSE)),]

xt4 <- xtable(summary_table_interim3,
              align =  c("l", "l","c", "c", "c", "c", "c", "c",
                         "c", "c"),
              digits = c(0, 0, 0,  2, 0,  2,1, 1, 1, 2))

names(xt4) <- c("Study",
                "\\cellcolor{Gray}$p_o$",
                "$\\hat\\theta_o$",
                "\\cellcolor{Gray}$p_i$",
                "$\\hat\\theta_i$",
                "Cond.",
                "\\cellcolor{Gray}Pred.",
                "$p_r$",
                "$\\hat\\theta_r$")


print(xt4,
      add.to.row = a_header,
      include.rownames = F,
      hline.after = F,
      sanitize.text.function=function(x){x},
      scalebox='0.6')
@

\end{frame}

\begin{frame}[fragile]
\frametitle{Results}
\begin{block}{\textcolor{red}{futility boundary: 10\%}}
$\rightarrow$ four studies stopped for futility with {\color{foo} 
predictive power at interim}
\end{block}

<<echo = F, results = 'asis'>>=
mat_content4 <- c(SSRP_red$study,
                 col1(SSRP_red$po1), 
                 SSRP_red$fiso,
                 col1(SSRP_red$pi1),
                 SSRP_red$fisi,
                 col3(cpi*100),
                 col2(IPPi*100),
                 col1(SSRP_red$pval1_final),
                 SSRP_red$fisr)

summary_table_interim4 <- matrix(mat_content4, ncol = 9, byrow = F)

colnames(summary_table_interim4) <- c("Study", "po", "ro", "pi", "ri",
                                     "CPi", "HPP",
                                     "pr","rr")

summary_table_interim4 <- as.data.frame(summary_table_interim4)

cols <- c(3,5,9)
# make sure that c, f, r etc are numeric
summary_table_interim4[,cols] = apply(summary_table_interim4[,cols], 2, function (x) as.numeric(as.character(x)))

#order the table om decreasing ri
summary_table_interim4 <- summary_table_interim4[order(summary_table_interim4$ri ,summary_table_interim4$pi, decreasing = c(TRUE, FALSE)),]

xt5 <- xtable(summary_table_interim4,
              align =  c("l", "l","c", "c", "c", "c", "c", "c",
                         "c", "c"),
              digits = c(0, 0, 0,  2, 0,  2,1, 1, 1, 2))

names(xt5) <- c("Study",
                "\\cellcolor{Gray}$p_o$",
                "$\\hat\\theta_o$",
                "\\cellcolor{Gray}$p_i$",
                "$\\hat\\theta_i$",
                "\\cellcolor{Gray}Cond.",
                "\\cellcolor{Gray}Pred.",
                "\\cellcolor{Gray}$p_r$",
                "$\\hat\\theta_r$")


print(xt5,
      add.to.row = a_header,
      include.rownames = F,
      hline.after = F,
      sanitize.text.function=function(x){x},
      scalebox='0.6')
@

\end{frame}


\begin{frame}{Conclusion/Outlook}

to do 
\end{frame}

\begin{frame}
  \frametitle{Acknowledgments}
  
  \begin{columns}
    \begin{column}{0.5\textwidth}
    \begin{center}
      \includegraphics[height=0.275\paperheight]{images_presentation/CRS.png}% \\
    \end{center}
    \begin{center}
    \includegraphics[width=4cm]{images_presentation/SwissRNLogowide.png} \\
    \end{center}
      \end{column}
      \begin{column}{0.5\textwidth}
      \vspace{0.5cm}
    \begin{center}
    \includegraphics[width=5cm]{images_presentation/logo.png}\\
    {\scriptsize \url{http://p3.snf.ch/Project-189295}}
    \end{center}
    \begin{center}
    \vspace{0.5cm}
      \includegraphics[width=1.65cm]{images_presentation/pawel_samuel.jpg} \vspace{.5cm}% \\
    \end{center}
    \end{column}
  \end{columns}

\end{frame}
% ============================================================================
\nocite{Pyc2010, Opensc2015, Camerer2016, Camerer2018, Cova2018, Pawel2020, Held2020, Held2020c}
\begin{frame}{References}
  \tiny
  \bibliographystyle{apalike}
  \bibliography{bibliography}
\end{frame}
  



\end{document}
